### ISSUE TITLE
Pydantic 2 Regression: Openapi error when "examples" contains models

### ISSUE THREAD

**Issue by Kludex** [tiangolo/fastapi#10321]
### Discussed in https://github.com/tiangolo/fastapi/discussions/10097

<div type='discussions-op-text'>

<sup>Originally posted by **UltimateLobster** August 17, 2023</sup>
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import uvicorn
from typing import Annotated

from pydantic import BaseModel, Field
from fastapi import Body, FastAPI

app = FastAPI()


class Toy(BaseModel):
    name: Annotated[str, Field(examples=["mouse", "ball"])]


class Cat(BaseModel):
    toys: Annotated[list[Toy], Field(examples=[
        [Toy(name="mouse"), Toy(name="ball")]
    ])]


@app.post("/cats")
async def create_cat(cat: Annotated[Cat, Body()]):
    print("cat was created")


uvicorn.run(app)
```

### Description

When using Pydantic 2 with the example code, FastAPI fails to generate openapi.json. It can't handle the `examples` field containing instances of another base model.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\fastapi\applications.py", line 244, in openapi
    return JSONResponse(self.openapi())
                        ^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\fastapi\applications.py", line 217, in openapi
    self.openapi_schema = get_openapi(
                          ^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\fastapi\openapi\utils.py", line 458, in get_openapi
    field_mapping, definitions = get_definitions(
                                 ^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\fastapi\_compat.py", line 213, in get_definitions
    field_mapping, definitions = schema_generator.generate_definitions(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\pydantic\json_schema.py", line 356, in generate_definitions
    definitions_remapping = self._build_definitions_remapping()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\pydantic\json_schema.py", line 2052, in _build_definitions_remapping
    return _DefinitionsRemapping.from_prioritized_choices(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\pydantic\json_schema.py", line 166, in from_prioritized_choices
    schemas_for_alternatives[defs_ref] = _deduplicate_schemas(schemas_for_alternatives[defs_ref])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\pydantic\json_schema.py", line 2151, in _deduplicate_schemas
    return list({_make_json_hashable(schema): schema for schema in schemas}.values())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nirschulman\PycharmProjects\pythonProject\venv\Lib\site-packages\pydantic\json_schema.py", line 2151, in <dictcomp>
    return list({_make_json_hashable(schema): schema for schema in schemas}.values())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'Toy'

### Operating System

Windows

### FastAPI Version

0.101.1

### Pydantic Version

2.1.1

### Python Version

3.11.4

### Additional Context

I think the problem is in FastAPI and not with pydantic because there is no error when generating json schema using pydantic's api directly:
```python
Cat.model_json_schema()
```</div>

**Comment by dmontagu** [comment]
The issue here is that the schema should be JSON (well, JSONable python anyway). And we don't (currently?) dump models in the `examples` attribute to JSON, I guess it's expected that those are already JSON(-able python objects).

If you change the examples to be JSONable python objects, I think it fixes your snippet:

```python
class Cat(BaseModel):
    toys: Annotated[list[Toy], Field(examples=[
        [Toy(name="mouse").model_dump(), Toy(name="ball").model_dump()]
    ])]
```

I do think this is more of a pydantic issue than a fastapi issue, it's just not coming up with the normal pydantic JSON schema generation call because fastapi is using a more complex code path for reasons related to needing to merge many schemas together.

I'm open to suggestions for how to improve this; one thing we could do is something like `TypeAdapter(Any).dump_python(examples)` when generating the JSON schema. If you'd like a solution like that, please let us know (or let us know what you might like instead, if something else); creating an issue on the pydantic repo for this might get a quicker response.

Caveat: I'm not sure how the other maintainers will react to the suggestion, but if they're on board, I don't think it would be hard to implement.

**Comment by dmontagu** [comment]
Okay I realize that this actually worked in pydantic v1 as-is even in the `schema_json` call. I think we can (non-controversially) replicate that behavior in pydantic v2 given it already worked in v1. I'll open a PR shortly.

**Comment by Kludex** [comment]
This will be resolved on the next Pydantic release (we are currently on 2.4.0), which will likely be in the next days (I presume 2.4.1).
