### ISSUE TITLE
Failed to start a server with uvicorn

### ISSUE THREAD

**Issue by abekthink** [tiangolo/fastapi#1104]
### Description
I followed the [guide](https://fastapi.tiangolo.com/), started a server with uvicorn, but I get the error:
ValueError: add_signal_handler() can only be called from the main thread.

### Additional context
Here is my code in main.py:
```
from fastapi import FastAPI
app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}

@app.get("/items/{item_id}")
def read_item(item_id: int, q: str = None):
    return {"item_id": item_id, "q": q}
```

When I run the server in the terminal:
`uvicorn main:app --reload`

I get the error:
```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [33633]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/test/PycharmProjects/fastapi-demo/venv/lib/python3.6/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/Users/test/PycharmProjects/fastapi-demo/venv/lib/python3.6/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/test/PycharmProjects/fastapi-demo/venv/lib/python3.6/site-packages/uvicorn/main.py", line 393, in serve
    self.install_signal_handlers()
  File "/Users/test/PycharmProjects/fastapi-demo/venv/lib/python3.6/site-packages/uvicorn/main.py", line 565, in install_signal_handlers
    loop.add_signal_handler(sig, self.handle_exit, sig, None)
  File "uvloop/loop.pyx", line 2816, in uvloop.loop.Loop.add_signal_handler
ValueError: add_signal_handler() can only be called from the main thread
```

Here are my requirements:
```
fastapi==0.52.0
uvicorn==0.11.3
```

**Comment by euri10** [comment]
Can't reproduce on a clean install with same python version 3.6.5 and fastapi==0.52.0
uvicorn==0.11.3, 

Could you try reinstalling your venv maybe something went wrong ?

```
(venv) ➜  fapifast python --version
Python 3.6.5
(venv) ➜  fapifast pip install fastapi
Collecting fastapi
  Using cached https://files.pythonhosted.org/packages/18/5b/46c084c174fc69b2a7e1d9c22d014f39fb677d9a7635f24734ef56e0fb53/fastapi-0.52.0-py3-none-any.whl
Collecting pydantic<2.0.0,>=0.32.2 (from fastapi)
  Using cached https://files.pythonhosted.org/packages/be/9a/a2d9613a70051615a84df6e9d697aad9787ba978bdeb4ad46c754457b3e1/pydantic-1.4-cp36-cp36m-manylinux2010_x86_64.whl
Collecting starlette==0.13.2 (from fastapi)
  Using cached https://files.pythonhosted.org/packages/37/2e/f56602beda25b376bbaaeadb626cf212b673457075ffed0dd12969ad6014/starlette-0.13.2-py3-none-any.whl
Collecting dataclasses>=0.6; python_version < "3.7" (from pydantic<2.0.0,>=0.32.2->fastapi)
  Using cached https://files.pythonhosted.org/packages/e1/d2/6f02df2616fd4016075f60157c7a0452b38d8f7938ae94343911e0fb0b09/dataclasses-0.7-py3-none-any.whl
Installing collected packages: dataclasses, pydantic, starlette, fastapi
Successfully installed dataclasses-0.7 fastapi-0.52.0 pydantic-1.4 starlette-0.13.2
(venv) ➜  fapifast pip install uvicorn
Collecting uvicorn
  Using cached https://files.pythonhosted.org/packages/fb/2a/b7fa32c8b89746308cc4acb333a320bbe2263d522665b3ef21a6fcdcd898/uvicorn-0.11.3-py3-none-any.whl
Collecting httptools==0.1.*; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy" (from uvicorn)
  Using cached https://files.pythonhosted.org/packages/b1/a6/dc1e7e8f4049ab70d52c9690ec10652e268ab2542853033cc1d539594102/httptools-0.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting h11<0.10,>=0.8 (from uvicorn)
  Using cached https://files.pythonhosted.org/packages/5a/fd/3dad730b0f95e78aeeb742f96fa7bbecbdd56a58e405d3da440d5bfb90c6/h11-0.9.0-py2.py3-none-any.whl
Collecting websockets==8.* (from uvicorn)
  Using cached https://files.pythonhosted.org/packages/bb/d9/856af84843912e2853b1b6e898ac8b802989fcf9ecf8e8445a1da263bf3b/websockets-8.1-cp36-cp36m-manylinux2010_x86_64.whl
Collecting uvloop>=0.14.0; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy" (from uvicorn)
  Using cached https://files.pythonhosted.org/packages/41/48/586225bbb02d3bdca475b17e4be5ce5b3f09da2d6979f359916c1592a687/uvloop-0.14.0-cp36-cp36m-manylinux2010_x86_64.whl
Collecting click==7.* (from uvicorn)
  Using cached https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl
Installing collected packages: httptools, h11, websockets, uvloop, click, uvicorn
Successfully installed click-7.1.1 h11-0.9.0 httptools-0.1.1 uvicorn-0.11.3 uvloop-0.14.0 websockets-8.1
(venv) ➜  fapifast uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [9822]
INFO:     Started server process [9825]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [9825]
INFO:     Stopping reloader process [9822]
```

**Comment by abekthink** [comment]
I reinstalled my venv environment, it works.

**Comment by alimcmaster1** [comment]
Good to close @euri10 @abekthink ?

**Comment by tiangolo** [comment]
Great! Can we close this issue then @abekthink ?
