### ISSUE TITLE
Asyncio wait() websocket unexpected disconnect

### ISSUE THREAD

**Issue by kmani314** [tiangolo/fastapi#1163]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.

I'm trying to listen for data on a websocket while simultaneously doing some work in another function, but if there is more data before the function exits I want to something else. I understand that this is a bit more of a Starlette problem, but I couldn't get any help there.
```
data = await websocket.receive_json()
while True:
    try:
        done, pending = await asyncio.wait({eval_worker(data, websocket), websocket.receive_json()}, return_when=asyncio.FIRST_COMPLETED)
        # do stuff with done
    except Exception:
        return
```
It results in this error: ```
ERROR:    Task exception was never retrieved
future: <Task finished name='Task-9' coro=<WebSocket.receive_json() done, defined at /***/venv/lib/python3.8/site-packages/starlette/websockets.py:94> exception=WebSocketDisconnect(1000)>
Traceback (most recent call last):
  File "/***/venv/lib/python3.8/site-packages/starlette/websockets.py", line 98, in receive_json
    self._raise_on_disconnect(message)
  File "/***/venv/lib/python3.8/site-packages/starlette/websockets.py", line 80, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1000```

I passed the websocket object to the function so that it can send data while it is also listening. I understand that this could be problematic, but even when I don't pass the websocket to the function it results in the same disconnect error.
Any insight?

**Comment by tiangolo** [comment]
Wouldn't it make sense to have the exception handling in your `eval_worker` function?

You might also want to `await websocket.close(code=1000)` in your except block.
