### ISSUE TITLE
[QUESTION] Response model with pydantic's arbitrary_types_allowed not working

### ISSUE THREAD

**Issue by datasatanic** [tiangolo/fastapi#1186]
I use pydantic model with custom type.  Set in config arbitrary_types_allowed=True. 
Without setting a parameter "response_model" it's work. But when I set this model in param:
```
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'Foo'> is a valid pydantic field type 
```
Pydantic class definition example:
```
import Foo

class Model(BaseModel):
    id: str
    custom: Optional[Foo] = Field(None)
    status: str = None
    fail_message: Optional[str] = None
    params: Dict[str, Any] = None

    @validator('custom')
    def deserialize_model(cls, v):
        return Foo.loads(v)

    class Config:
        arbitrary_types_allowed = True
        json_encoders = {Foo: lambda v: v.dumps()}
```

**Comment by andreipopovici** [comment]
I see the same issue with an `Arrow` type returned from the SQLAlchemy model. `arbitrary_types_allowed` is not working when using the pydantic model in the `response_model`.

**Comment by tiangolo** [comment]
Please create a small self-contained example with a minimal FastAPI app that shows the error and what you would expect to happen, that way I can understand what's happening and what you want to achieve.

**Comment by bcb** [comment]
@tiangolo I think the config is getting lost in the `create_cloned_field` function.

```python
new_field = create_response_field(name=field.name, type_=use_type)
```

Shouldn't it also pass `model_config`?

**Comment by bcb** [comment]
I ended up using a custom Pydantic field validator, instead of using `arbitrary_types_allowed`:

```python
class AssociationList(_AssociationList):
    """Sqlalchemy AssociationList"""

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if not isinstance(v, _AssociationList):
            raise TypeError("AssociationList required")
        return [UserOut.from_orm(u) for u in v]

class TeamOut(TeamBase):
    members: AssociationList
    ...
```

**Comment by eco-monk** [comment]
> Same problem here:
> 
> ```python
> from pydantic import BaseModel
> from fastapi import FastAPI
> 
> 
> class Pair:
>     def __init__(self, x: int, y: int):
>         self.x: int = x
>         self.y: int = y
> 
> 
> class M(BaseModel):
>     pair: Pair
>     other: int
> 
>     class Config:
>         arbitrary_types_allowed = True
> 
> 
> app = FastAPI()
> 
> 
> @app.get("/m/", response_model=M)
> def just_m():
>     return M(pair=Pair(x=5, y=7), other=8)
> ```
> 
> will report error:
> 
> ```
> fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'test.Pair'> is a valid pydantic field type
> ```

I get the same error, when the instance is a `List[Pair]` instead of `M` (as given below)

```
@app.get("/m/", response_model=List[Pair])
def just_m():
    return [Pair(x=5, y=7)]
```

**Comment by a-recknagel** [comment]
@fubupc you can monkey patch the arbitrary class to tell fastapi a way to render it:

```python
from pydantic import create_model

def validate(cls):
    yield lambda cls, v: v if isinstance(v, cls) else cls(**v)
Pair.__get_validators__ = classmethod(validate)
Pair.__pydantic_model__ = create_model("Pair", x=(int, ...), y=(int, ...))

class M(BaseModel):
    pair: Pair
    other: int

    class Config:
        # don't need arbitrary types any more now that "Pair" has a validator
        json_encoders = {
            Pair: lambda pair: {"x": pair.x, "y": pair.y, }
        }
```

More details [here](https://stackoverflow.com/a/68016156/962190).

**Comment by teplinsky-maxim** [comment]
I had the same problem, but then I found out that I forgot to inherit from `BaseModel`

```
# WRONG
class AuthorType:
    name: str
    username: str


# OK
class AuthorType(BaseModel):
    name: str
    username: str

```

**Comment by andreipopovici** [comment]
@teplinsky-maxim Your solution is great when not using an existing class provided by a library. The example provided by @karolzlot above is what I should have provided to @tiangolo [way back in April 2020](https://github.com/tiangolo/fastapi/issues/1186#issuecomment-609361164) 😅 Thank you for that.

**Comment by karolzlot** [comment]
@tiangolo please reopen 🥺🙏

**Comment by Zaffer** [comment]
Please refer to my code example here for a full working way to do this: 
https://github.com/tiangolo/sqlmodel/issues/235#issuecomment-1162063590

**Comment by tibbe** [comment]
Here's a full, stand-alone repro showing that arbitrary types can be used with custom serialization/deserialization when using raw pydantic:

```py
# repro.py
from typing import Union
import phonenumbers
import pydantic


def phone_number_validator(
        value: Union[str, phonenumbers.PhoneNumber]
) -> phonenumbers.PhoneNumber:
    if isinstance(value, phonenumbers.PhoneNumber):
        return value
    try:
        number = phonenumbers.parse(value, None)
    except phonenumbers.NumberParseException as ex:
        raise ValueError(f'Invalid phone number: {value}') from ex
    if not phonenumbers.is_possible_number(number):
        raise ValueError(f'Invalid phone number: {value}')
    return number


class MyModel(pydantic.BaseModel):
    phone_number: phonenumbers.PhoneNumber

    _validate_phone_number = pydantic.validator(
        'phone_number', pre=True, allow_reuse=True)(phone_number_validator)

    class Config:
        arbitrary_types_allowed = True
        json_encoders = {
            phonenumbers.PhoneNumber: lambda p: phonenumbers.format_number(
                p, phonenumbers.PhoneNumberFormat.E164),
        }
```

To JSON:
```
>>> repro.MyModel(phone_number=phonenumbers.example_number('CH')).json()
'{"phone_number": "+41212345678"}'
```

From JSON:
```
>>> repro.MyModel.parse_raw('{"phone_number": "+41212345678"}')
MyModel(phone_number=PhoneNumber(country_code=41, national_number=212345678, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None))
```

However, when used as a FastAPI `response_model` it fails with:

```
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'phonenumbers.phonenumber.PhoneNumber'> is a valid pydantic field type
```

**Comment by daniil-berg** [comment]
I can confirm, this is still an issue. Here is a minimal reproducible example similar to what @tibbe wrote above, but _without_ any external dependencies:
```python
from typing import Union

from fastapi import FastAPI
from pydantic import BaseModel, validator


class Foo:
    def __init__(self, value: int) -> None:
        self.value = value

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Foo):
            return NotImplemented
        return self.value == other.value


class MyModel(BaseModel):
    foo: Foo

    @validator("foo", pre=True)
    def valid_foo(cls, v: Union[str, Foo]) -> Foo:
        if isinstance(v, Foo):
            return v
        if isinstance(v, int):
            return Foo(v)
        raise TypeError("Invalid Foo type")

    class Config:
        arbitrary_types_allowed = True
        json_encoders = {
            Foo: lambda foo: foo.value,
        }


def test_json():
    obj = MyModel(foo=Foo(123))
    obj_json = obj.json()
    parsed_obj = MyModel.parse_raw(obj_json)
    assert obj == parsed_obj


def test_api():
    api = FastAPI()

    @api.get("/model/", response_model=MyModel)
    def example_route():
        return MyModel(foo=Foo(123))


if __name__ == '__main__':
    test_json()  # works
    # test_api()  # fails with "Invalid args for response field!"
```

<details>
<summary>Full error (as posted multiple times):</summary>

```
Traceback (most recent call last):
  File "/home/daniil/coding/workbench/.venv/lib/python3.10/site-packages/fastapi/utils.py", line 78, in create_response_field
    return response_field(field_info=field_info)
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class '__main__.Foo'>, see `arbitrary_types_allowed` in Config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniil/coding/workbench/so/fastapi_custom_types.py", line 52, in <module>
    test_api()  # fails with "Invalid args for response field!"
  File "/home/daniil/coding/workbench/so/fastapi_custom_types.py", line 46, in test_api
    def example_route():
  File "/home/daniil/coding/workbench/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 626, in decorator
    self.add_api_route(
  File "/home/daniil/coding/workbench/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 565, in add_api_route
    route = route_class(
  File "/home/daniil/coding/workbench/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 405, in __init__
    ] = create_cloned_field(self.response_field)
  File "/home/daniil/coding/workbench/.venv/lib/python3.10/site-packages/fastapi/utils.py", line 104, in create_cloned_field
    use_type.__fields__[f.name] = create_cloned_field(
  File "/home/daniil/coding/workbench/.venv/lib/python3.10/site-packages/fastapi/utils.py", line 107, in create_cloned_field
    new_field = create_response_field(name=field.name, type_=use_type)
  File "/home/daniil/coding/workbench/.venv/lib/python3.10/site-packages/fastapi/utils.py", line 80, in create_response_field
    raise fastapi.exceptions.FastAPIError(
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class '__main__.Foo'> is a valid pydantic field type
```

And yes, @bcb already pointed out where the error stems from. I'll see, if there already is a PR for this, and if not maybe create one.
