### ISSUE TITLE
Event loop stopped before Future completed

### ISSUE THREAD

**Issue by ZeusFSX** [tiangolo/fastapi#1194]
### Describe the bug
I use API which connects to MongoDB and gets some data. I deployed API with Docker. And after 2 - 3 days running container I can get the error:
````
Process SpawnProcess-1: Traceback (most recent call last): 
    File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() 
    File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) 
    File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started target(sockets=sockets) 
    File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 382, in run loop.run_until_complete(self.serve(sockets=sockets)) 
    File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete 
RuntimeError: Event loop stopped before Future completed. 
````
Dockerfile:
````
FROM python:3.8

WORKDIR /app
COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . /app
````
````
Python version 3.8.2

fastapi==0.52.0
uvicorn==0.11.3
uvloop==0.14.0
````

**Comment by tiangolo** [comment]
It's very difficult to help you debug your code without an example. Please create a minimal self-contained app that replicates the issue so that we can take a look.

In general, it seems like you could have an exception in your app that raised and didn't let the loop finish, or something similar.

You might want to also try https://sentry.io/
