### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BinNong** [tiangolo/fastapi#1334]
### Describe the bug
when I use fastapi to offer restful api, something bad happens like this :
Error getting request body: Invalid control character at: line 2 column 22 (char 24)

### Demo

```Python
from fastapi import FastAPI

app = FastAPI()

@app.get('/api')
async def run(text: str):
        return text
```

when i passing some textas part of the JSON input,  I get this error:
ERROR: Error getting request body: Invalid control character at: line 2 column 22 (char 24).

I think  it encounters unneeded characters in the JSON body, and is there a way to set strict = false like json.loads(request.data, strict=False)?
### Environment

- OS:  Linux
- FastAPI Version:  0.49.0
- python Version: 3.6.5

**Comment by retnikt** [comment]
Please show the code you're using to send the JSON input, and the full stack-trace ("Traceback (most recent call last): ...") you're getting. This is not an issue with FastAPI, but rather with your JSON data by the looks of it.

**Comment by tiangolo** [comment]
Thanks for the help here @retnikt ! :clap: :bow: 

If that solves the original problem, then you can close this issue :heavy_check_mark:

**Comment by espoirMur** [comment]
So I am not sure if this should be closed: 

- I tried to print the traceback of the error and I got something like this: 
```
1 validation error for Request
body -> 467
  Invalid control character at: line 2 column 466 (char 467) (type=value_error.jsondecode; msg=Invalid control character at; doc={
  "text": "There are more than a few good reasons why Yellowstone is as popular as it is. Sure, you get the family drama of the Duttons and everything that unfolds on their Montana ranch. But, we think it runs a little bit deeper than that. Yellowstone embodies our need for a great story, beckoning back to the golden era of westerns, while also building on a cast of compelling characters. Paired with the beautiful scenery of Big Sky Country, what’s not to love?

Just like you, we live and breathe Yellowstone. Writer/Creator Tyler Sheridan’s weekly masterpiece is enough to keep up with, but when you bring in cast changes, sneak peeks, trailers, fan theories, and glimpses into the production, you’re talking about a full-time commitment. And that’s exactly why we have a full-time set of writers bringing you everything Yellowstone day-in and day-out.

"
}; pos=467; lineno=2; colno=466)
Traceback (most recent call last):
  File "~/project_path/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 193, in app
    json_body = await request.json()
  File "~/project_path/.venv/lib/python3.7/site-packages/starlette/requests.py", line 228, in json
    self._json = json.loads(body)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "~/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 466 (char 467)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/project_path/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "~/project_path/.venv/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "~/project_path/.venv/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "~/project_path/.venv/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "~/project_path/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 199, in app
    raise RequestValidationError([ErrorWrapper(e, ("body", e.pos))], body=e.doc)
fastapi.exceptions.RequestValidationError: 1 validation error for Request
body -> 467
  Invalid control character at: line 2 column 466 (char 467) (type=value_error.jsondecode; msg=Invalid control character at; doc={
  "text": "There are more than a few good reasons why Yellowstone is as popular as it is. Sure, you get the family drama of the Duttons and everything that unfolds on their Montana ranch. But, we think it runs a little bit deeper than that. Yellowstone embodies our need for a great story, beckoning back to the golden era of westerns, while also building on a cast of compelling characters. Paired with the beautiful scenery of Big Sky Country, what’s not to love?

Just like you, we live and breathe Yellowstone. Writer/Creator Tyler Sheridan’s weekly masterpiece is enough to keep up with, but when you bring in cast changes, sneak peeks, trailers, fan theories, and glimpses into the production, you’re talking about a full-time commitment. And that’s exactly why we have a full-time set of writers bringing you everything Yellowstone day-in and day-out.

"
```

From that you can  see that the error is coming from this line : 

```
  File "~/project_path/.venv/lib/python3.7/site-packages/starlette/requests.py", line 228, in json
    self._json = json.loads(body)
```
If I replace the function load with the following method it kinda solved the issue temporarily 

`self._json = json.loads(body,  strict=False)`

I am going to try to override the method and see if how it goes .
but from my understanding, it is more an issue with startlette than a fast API issue? 
But  I am sure there is something that can be done on the fast API side to avoid those king of issues and on starlette.

**Comment by espoirMur** [comment]
Can we remove the label close on this while we are looking for solution? @tiangolo
