### ISSUE TITLE
Query parameters - Dictionary support? 

### ISSUE THREAD

**Issue by babu-s2** [tiangolo/fastapi#1415]
### Description

While am using this feature, I have this requirement where I need a parameter to be a Dictionary(key values list) for 'GET' query parameters.
Currently the GET operation seem to support only the following parameter types

- String
- Int
- Enum
- List[str] or List[int]
- Kwargs(variable number of args in dictionary form)

Do you have any recommendations?. One suggestion I got is to use `POST` instead of `GET` and achieve the flexible query. Is that a good idea?

**Comment by vitalik** [comment]
Can you add example of the url that you will be calling (including GET params) and expected result ?

**Comment by babu-s2** [comment]
Glad to give

I have a query like this

/s2/getNetwork?<>

Here I need to pass two parameters

1. One parameter is like this

location = [rack=r1, server=s2]

2. Second parameter is like this

timerange = [starttime=t1, endtime=t2]


Current implementation is like this.

@app.get(
    "/s2/getNetwork",
    tags=["s2Network"])
async def get_latency_metric(
        location: List[str] = Query(
            None,
            alias="slice",
        ),
        timerange: List[str] = Query(
            None,
        )):

My Requirements:.
------------------
1. First requirement is, I would like 'location' to be Dictionary so I can pass key, values inside it
 i.e. 
location = {{rack: r1}, {server:s2}}

2. Second requirement is, when specifying time as a parameter, in this example its `timerange` I need this parameter in time format so it helps to validate at client side before reaching server

**Comment by vitalik** [comment]
I guess you can use **Depends** to achieve it:


```
import json
from typing import List
from fastapi import FastAPI, Query, Depends


app = FastAPI(debug=True)


def location_dict(locations: List[str] = Query(...)):
    return list(map(json.loads, locations))


@app.get("/test")
def operation(locations: List[str] = Depends(location_dict)):
    return locations
```

![CleanShot 2020-05-15 at 13 00 21](https://user-images.githubusercontent.com/95222/82038352-15a68f80-96ac-11ea-9dca-e50b1b39682f.png)

**Comment by babu-s2** [comment]
Thanks, it worked. However, am running into crash if I miss a parameter(say '{') at input

500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/fastapi/routing.py", line 190, in app
    dependency_overrides_provider=dependency_overrides_provider,
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 510, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/Users/babu-s2/code/python/fastapis/ns/lib/python3.7/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./main.py", line 215, in location_dict
    return list(map(json.loads, locations))
  File "./main.py", line 215, in location_dict
    return list(map(json.loads, locations))
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 112, in dispatch_line
    self.user_line(frame)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 259, in user_line
    self.interaction(frame, None)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 342, in interaction
    signal.signal(signal.SIGINT, Pdb._previous_sigint_handler)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

Is there a way to validate the values either at server side or else at openapi?

Thanks

**Comment by vitalik** [comment]
you probably need to put 

`return list(map(json.loads, locations))`

into try/except (to handle invalid json)

**Comment by babu-s2** [comment]
Thanks Vitalik. Thats what I thought so.

What about for timestamp, the second problem I mentioned? Is there a way to represent time val as parameter in time format?

Thanks

**Comment by awemulya** [comment]
@vitalik How to make locations not required.

**Comment by PVMezencev** [comment]
Hi, guys! 
How to process parameters with names on the FAST API server: 
`field[0]=value0&field[1]=value1`
like a dictionary: 
`field = {"0":"value0", "1":"value1"}`
Thx!

**Comment by ffss92** [comment]
Looking at starlette documentation today, I found that you can get a dict of query params  by using request like this

`from fastapi import FastAPI, Request
from pydantic import BaseModel
from typing import Optional
from datetime import date

app = FastAPI()

class Query(BaseModel):
    msg: Optional[str] = None
    page: Optional[int] = None
    only_one: bool
    when: date

@app.get('/')
async def home(req: Request, only_one: bool, when: date, msg: str = None, page: int = None):
    query = Query(**req.query_params).dict(exclude_unset=True)
    return query`

**Comment by WingLim** [comment]
Take a look of #2230.

**Comment by JeremyAndress** [comment]
@awemulya you must add None inside of Query Object:

```python
def locations_dict(locations: List[str] = Query(None)): pass
```

**Comment by jgse** [comment]
Hi,

I have similar issue when I have a param to accept dict type query
`get_event(params: Dict[str, str] = Query(...))
`
I got error below. How do I have a param to accept dict type
```

  File "/home/gftea/.venv/eiffel/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 317, in get_dependant
    assert isinstance(
AssertionError: Param: params can only be a request body, using Body(...)
```
