### ISSUE TITLE
pypy 3.6.9 equivalent always throws an error on yield

### ISSUE THREAD

**Issue by sandys** [tiangolo/fastapi#1485]
I have already done, `pip install async-exit-stack async-generator` multiple times. However, the application still gives an error

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/site-packages/uvicorn/protocols/http/h11_impl.py", line 384, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/site-packages/fastapi/routing.py", line 190, in app
    dependency_overrides_provider=dependency_overrides_provider,
  File "/usr/local/site-packages/fastapi/dependencies/utils.py", line 512, in solve_dependencies
    async_contextmanager_dependencies_error
RuntimeError: 
FastAPI dependencies with yield require Python 3.7 or above,
or the backports for Python 3.6, installed with:
    pip install async-exit-stack async-generator

```

**Comment by phy25** [comment]
Could you provide a self-contained example? 

This is how fastapi checks support:

https://github.com/tiangolo/fastapi/blob/5984233223777313e95a92d534ab1db711bd606a/fastapi/concurrency.py#L21-L35

https://github.com/tiangolo/fastapi/blob/5984233223777313e95a92d534ab1db711bd606a/fastapi/dependencies/utils.py#L261-L263

So you might want to debug this to see which is missing and why the polyfill is not working.

**Comment by chris-allnutt** [comment]
Is there any reason why you can't use python 3.7?

**Comment by sandys** [comment]
@chris-allnutt pypy is at 3.6.9 right now. 

@phy25 - i am trying to break this down. this is part of a very large application, but i think im beginning to figure out the issue. i tested with both pypy and python 3.8 (cc @chris-allnutt ). and i believe the issue is that the yield/depends code here - https://fastapi.tiangolo.com/tutorial/sql-databases/#create-your-fastapi-path-operations - does not work with APIRouter . It works with FastAPI.

**Comment by igotinfected** [comment]
Could this be a `pip` issue? I'm using python 3.6.9 too and have no issue at all.

```bash
$ pip -V
pip 20.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
$ env/bin/pip -V
pip 20.1.1 from /home/dev/workspace/.../env/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by tiangolo** [comment]
Hey there! Have you tried recent versions of PyPy? It seems the current PyPy is equivalent to 3.7, that wouldn't have these issues.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
