### ISSUE TITLE
Error generating swagger docs when using uploadfile parameter in post

### ISSUE THREAD

**Issue by speizerj** [tiangolo/fastapi#1523]
### Describe the bug

KeyError when trying to fetch the swagger docs

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

1. Create a file with:

```Python
import base64
from fastapi import APIRouter, File, UploadFile
from starlette.requests import Request

router = APIRouter()

@router.post('/uploadfile')
def get(request: Request, file: UploadFile = File(...)):
    
    filename_parts = file.filename.split('.')
    file = file.file.read()
    if filename_parts[-1] == 'xlsx':
        file = base64.b64encode(file)

    return {"file": file}
```

3. Open the browser and call the endpoint `/docs`.
4. KeyError raised

```Python
INFO:uvicorn:('127.0.0.1', 63331) - "GET /openapi.json HTTP/1.1" 500
ERROR:uvicorn:Exception in ASGI application
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "venv/lib/python3.7/site-packages/fastapi/applications.py", line 139, in __call__
    await super().__call__(scope, receive, send)
  File "venv/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./components/requests/middleware.py", line 26, in requests_middleware
    response = await call_next(request)
  File "venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./components/metadata_db/middleware.py", line 18, in session_middleware
    response = await call_next(request)
  File "venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "venv/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "venv/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "venv/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "venv/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "venv/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "venv/lib/python3.7/site-packages/fastapi/applications.py", line 96, in openapi
    return JSONResponse(self.openapi())
  File "venv/lib/python3.7/site-packages/fastapi/applications.py", line 88, in openapi
    openapi_prefix=self.openapi_prefix,
  File "venv/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 268, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "venv/lib/python3.7/site-packages/fastapi/utils.py", line 45, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'Body_post_uploadfile_post'>
```

### Expected behavior

Swagger documentation should load

### Screenshots

![image](https://user-images.githubusercontent.com/1063758/83927444-cc44df80-a741-11ea-9e5a-33987d71edfe.png)

### Environment

- OS: macOS 10.15.3
- FastAPI Version: 0.42.0
- Python version: 3.7.3

### Additional context

Having the same issue with a singular Body parameter in a separate endpoint (as explained [here](https://fastapi.tiangolo.com/tutorial/body-multiple-params/#singular-values-in-body)). Since that example is more complex I posted this one instead

**Comment by egde** [comment]
Facing the exact issue as well...

**Comment by br3ndonland** [comment]
@speizerj I'm unable to reproduce this, on either 0.42.0 or latest. I'm happy to troubleshoot further with you if you would like. Here's what I did:

### Install FastAPI for development

See the [FastAPI docs on contributing](https://fastapi.tiangolo.com/contributing/).

```sh
# GitHub CLI: https://cli.github.com/
~/dev
❯ gh repo fork --clone="true" tiangolo/fastapi

~/dev
❯ cd fastapi

~/dev/fastapi master
❯ git checkout 0.42.0
Note: switching to '0.42.0'.

HEAD is now at 65536cb :bookmark: Release version 0.42.0: Answer to the Ultimate Question of Life, the Universe, and Everything

~/dev/fastapi tags/0.42.0
❯ python -m venv env

# May need to add env to .gitignore for 0.42.0
~/dev/fastapi tags/0.42.0
❯ . env/bin/activate

~/dev/fastapi tags/0.42.0
env ❯ python --version
Python 3.7.7

~/dev/fastapi tags/0.42.0
env ❯ pip install flit

~/dev/fastapi tags/0.42.0
env ❯ flit install --deps all --symlink

~/dev/fastapi tags/0.42.0
env ❯ pip show fastapi | grep "Version"
Version: 0.42.0
```

### Set up directory with test file

Create a separate directory and put in the test file from the bug report as _main.py_, adding a FastAPI instance to enable it to run, and adding the example code from the docs for [a singular Body parameter in a separate endpoint](https://fastapi.tiangolo.com/tutorial/body-multiple-params/#singular-values-in-body) as described in "Additional context."

```sh
~/dev
❯ mkdir fastapi-1523; cd fastapi-1523

# VSCode CLI: https://code.visualstudio.com/docs/editor/command-line
~/dev/fastapi-1523
❯ touch main.py; code main.py
```

```py
import base64
from fastapi import APIRouter, Body, FastAPI, File, UploadFile
from pydantic import BaseModel
from starlette.requests import Request

app = FastAPI()
router = APIRouter()


class Item(BaseModel):
    name: str
    description: str = None
    price: float
    tax: float = None


class User(BaseModel):
    username: str
    full_name: str = None


@router.put("/items/{item_id}")
async def update_item(
    item_id: int, item: Item, user: User, importance: int = Body(...)
):
    results = {"item_id": item_id, "item": item, "user": user, "importance": importance}
    return results


@router.post("/uploadfile")
def get(request: Request, file: UploadFile = File(...)):

    filename_parts = file.filename.split(".")
    file = file.file.read()
    if filename_parts[-1] == "xlsx":
        file = base64.b64encode(file)

    return {"file": file}


app.include_router(router)

```

### Run the test file using the FastAPI virtual environment

```sh
~/dev/fastapi-1523
❯ . ~/dev/fastapi/env/bin/activate

~/dev/fastapi-1523
env ❯ uvicorn main:app --reload
```

### Check the OpenAPI schema

http://localhost:8000/docs:

![fastapi-1523-docs](https://user-images.githubusercontent.com/26674818/84577422-e5750e00-ad89-11ea-8663-b293dd70af12.png)

Server output:

```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12340] using statreload
INFO:     Started server process [12342]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:55896 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:55896 - "GET /openapi.json HTTP/1.1" 200 OK
```

OpenAPI JSON:

```sh
# HTTPie: https://httpie.org/
~
❯ http -h :8000/openapi.json
HTTP/1.1 200 OK
content-length: 1173
content-type: application/json
date: Sat, 13 Jun 2020 18:59:32 GMT
server: uvicorn
```

I even tried uploading a sample .xlsx file through the Swagger UI. FastAPI returns a `200` with the encoded file.

**Comment by ihakh** [comment]
read the traceback
there are two line that are not starting with `File "venv`, which are:
```
  File "./components/requests/middleware.py", line 26, in requests_middleware
    response = await call_next(request)
  File "./components/metadata_db/middleware.py", line 18, in session_middleware
    response = await call_next(request)
```
so please check your middleware

**Comment by speizerj** [comment]
thank you @ihakh and @br3ndonland for looking into this. I'll look into our middleware and will close this for now.

**Comment by tiangolo** [comment]
Thanks for the help here everyone! :clap: :bow: 

Thanks for reporting back and closing the issue @speizerj  :+1:

**Comment by ankurRakuten** [comment]
@speizerj can you please update how did you solve this issue ?

**Comment by speizerj** [comment]
@ankurRakuten it was a bug within our custom middleware that was causing the issue, not with fastapi
