### ISSUE TITLE
ImportError: cannot import name 'jinja2Templates' from 'fastapi.templating'

### ISSUE THREAD

**Issue by caroe2014** [tiangolo/fastapi#1530]
### Describe the bug

ImportError: cannot import name 'jinja2Templates' from 'fastapi.templating' (c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\fastapi\templating.py)

Write here a clear and concise description of what the bug is.

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

1. Create a file with:

```Python
from fastapi import FastAPI, Request
from fastapi.templating import jinja2Templates
app = FastAPI()

templates = jinja2Templates(directory="templates")
```
2. create requirements.txt
fastapi
uvicorn
jinja2
yfinance
sqlalchemy

3. run the python program fro the command prompt: uvicorn main:app --reload 
4. it will show the error

### Expected behavior

(env) C:\Users\myusername\Sites\python\fastapi\app>uvicorn main:app --reload
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m13824[0m] using [36m[1mstatreload[0m
[32mINFO[0m:     Started server process [[36m13640[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.

### Screenshots

[33mWARNING[0m:  Detected file change in 'main.py'. Reloading...
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\uvicorn\main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\uvicorn\main.py", line 389, in serve
    config.load()
  File "c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\uvicorn\config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\uvicorn\importer.py", line 23, in import_from_string
    raise exc from None
  File "c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\main.py", line 2, in <module>
    from fastapi.templating import jinja2Templates
ImportError: cannot import name 'jinja2Templates' from 'fastapi.templating' (c:\users\myusername\sites\python\fastapi\app\env\lib\site-packages\fastapi\templating.py)
### Environment

- OS: Windows 10
- Python: 3.8.3
- pip 19.2.3
- FastAPI Version 0.55.1 get it with: pip install fastapi

```bash
python -c "import fastapi; print(fastapi.__version__)"
```

- Python version, get it with:

```bash
python --version
```

**Comment by phy25** [comment]
Have you installed jinja2?

https://fastapi.tiangolo.com/advanced/templates/#install-dependencies
