### ISSUE TITLE
Issue with Extending Openapi `prefix error`

### ISSUE THREAD

**Issue by Daggy1234** [tiangolo/fastapi#1581]
custom_openapi() missing 1 required positional argument: 'openapi_prefix'

This is the error I keep getting

```python
def custom_openapi(openapi_prefix: str):
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = get_openapi(
        title="Dagpi",
        version="1.0",
        description="The Number 1 Image generation api",
        routes=app.routes,
        openapi_prefix=openapi_prefix,
    )
    openapi_schema["info"]["x-logo"] = {
        "url": "https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png"
    }
    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = custom_openapi
```

I am not using a virtualenv

This is on windows 10 on a standard instance run with uvicorn.
Python3.8
![image](https://user-images.githubusercontent.com/60603110/84685140-62a1ae00-af57-11ea-8a72-5b36d7d0cc73.png)
![image](https://user-images.githubusercontent.com/60603110/84685160-6af9e900-af57-11ea-9b66-f1e2ae2981d3.png)

**Comment by Daggy1234** [comment]
```python
←[32mINFO←[0m:     Started server process [←[36m9232←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     127.0.0.1:56469 - "←[1mGET /redoc HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:56469 - "←[1mGET /openapi.json HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 384, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\fastapi\applications.py", line 146, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\users\arnav jindal\appdata\local\programs\python\python38\lib\site-packages\fastapi\applications.py", line 103, in openapi
    return JSONResponse(self.openapi())
TypeError: custom_openapi() missing 1 required positional argument: 'openapi_prefix'
```

**Comment by tiangolo** [comment]
Ah, yeah, the openapi generation function now takes a string parameter in recent versions.

It seems like you upgraded your FastAPI version, probably without running the tests first, check about pinning your FastAPI version here: https://fastapi.tiangolo.com/deployment/#pin-your-fastapi-version

Also check the new docs about extending OpenAPI: https://fastapi.tiangolo.com/advanced/extending-openapi/

**Comment by Daggy1234** [comment]
@tiangolo Thanks for that, but the documentation is not updated and I suggest merging my pull request that changes the docs!
[request](https://github.com/tiangolo/fastapi/pull/1630 )
