### ISSUE TITLE
AttributeError: Can't pickle local object 'FastAPI.setup.<locals>.openapi' logging SocketHandler

### ISSUE THREAD

**Issue by flapili** [tiangolo/fastapi#1586]
### First check

* [*] I added a very descriptive title to this issue.
* [*] I used the GitHub search to find a similar issue and didn't find it.
* [*] I searched the FastAPI documentation, with the integrated search.
* [*] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [*] I already read and followed all the tutorial in the docs and didn't find an answer.
* [*] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [*] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [*] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

Hi, after digging deep in the uvicorn source I have come to the conclusion I can't use log_config kwargs because logging record aren't sent to the master process but handled by the worker itself,
in my case I have 2constraints:

the solutions must be python only / not dependant of the process manager "at the end the system must be independent in terms of logging"
I must setup complexe rotating files and I can't let the workers handle that because each worker will try to rename/delete logs files.

my current solution is send the logs records via TCP but I'm face to an issue:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/handlers.py", line 631, in emit
    s = self.makePickle(record)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 603, in makePickle
    s = pickle.dumps(d, 1)
AttributeError: Can't pickle local object 'FastAPI.setup.<locals>.openapi'
Call stack:
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Message: '192.168.1.52:59572 - "GET / HTTP/1.1" 200'
Arguments: None
```

minimal repro code:
app.py
```py
# coding: utf-8

import logging
import logging.handlers
import queue

from fastapi import FastAPI


root_logger = logging.getLogger()
root_logger.setLevel(logging.DEBUG)


q = queue.Queue()
queue_handler = logging.handlers.QueueHandler(q)

root_logger.addHandler(queue_handler)

socket_handler = logging.handlers.SocketHandler('localhost', logging.handlers.DEFAULT_TCP_LOGGING_PORT)
listener = logging.handlers.QueueListener(q, socket_handler, respect_handler_level=True)
listener.start()


logger = logging.getLogger(__name__)


app = FastAPI()

@app.on_event("shutdown")
def on_shutdown():
    q.join()


logger.info("from app")

@app.get("/")
async def homepage():
    return "Hello world"
```
main.py
```py
# coding: utf-8

if __name__ == "__main__":

    import socketserver
    import pickle
    import struct
    import threading
    import logging
    import logging.handlers

    import uvicorn

    class LogRecordStreamHandler(socketserver.StreamRequestHandler):
        def handle(self):
            while True:
                chunk = self.connection.recv(4)
                if len(chunk) < 4:
                    break

                slen = struct.unpack(">L", chunk)[0]
                chunk = self.connection.recv(slen)
                while len(chunk) < slen:
                    chunk += self.connection.recv(slen - len(chunk))

                obj = pickle.loads(chunk)
                record = logging.makeLogRecord(obj)
                logger = logging.getLogger(record.name)

                if logger.isEnabledFor(record.levelno):
                    logger.handle(record)



    logging.basicConfig(format="%(name)-15s %(levelname)-8s %(message)s", level=logging.DEBUG)

    TCP_server = socketserver.ThreadingTCPServer(
        ("localhost", logging.handlers.DEFAULT_TCP_LOGGING_PORT), LogRecordStreamHandler
    )

    threading.Thread(target=TCP_server.serve_forever).start()


    workers = 2

    logger = logging.getLogger(__name__)

    logger.info("Running %d workers", workers)
    uvicorn.run("app:app", host="0.0.0.0", port=8000, log_config={"version": 1, "disable_existing_loggers": False}, workers=workers)
    TCP_server.shutdown()
```

`venv/bin/python src/main.py`
go to 127.0.0.1:8000

Do you have any idea ?
If some things are not clear or precise enough ask me

### Environment

* OS: linux (debian 10):
* FastAPI: 0.55.1
* Python version: 3.8.1

**Comment by ericlingit** [comment]
I'm dealing with the exact same problem (and have an almost identical setup to yours).

The problem is caused by uvicorn's logger `uvicorn.access` emitting a log record that contains unpicklable objects:

```python
{
    'name': 'uvicorn.access',
    'msg': '192.168.87.193:41938 - "GET /docs HTTP/1.1" 200',
    'args': None,
    'levelname': 'INFO',
    'levelno': 20,
    'pathname': '/home/eric/miniconda3/envs/test/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py',
    'filename': 'httptools_impl.py',
    'module': 'httptools_impl',
    'exc_info': None,
    'exc_text': None,
    'stack_info': None,
    'lineno': 454,
    'funcName': 'send',
    'created': 1608608064.3735769,
    'msecs': 373.5768795013428,
    'relativeCreated': 9702.853918075562,
    'thread': 140182857406272,
    'threadName': 'MainThread',
    'processName': 'MainProcess',
    'process': 28906,
    'status_code': '\x1b[32m200 OK\x1b[0m',
    'scope': {
        'type': 'http',
        'http_version': '1.1',
        'server': ('192.168.90.211', 8000),
        'client': ('192.168.87.193', 41938),
        'scheme': 'http',
        'method': 'GET',
        'root_path': '',
        'path': '/docs',
        'raw_path': b'/docs',
        'query_string': b'',
        'headers': [
            (b'host', b'192.168.90.211:8000'),
            (b'user-agent', b'python-requests/2.24.0'),
            (b'accept-encoding', b'gzip, deflate'),
            (b'accept', b'*/*'),
            (b'connection', b'keep-alive')
        ],
        # These are the trouble makers:
        'fastapi_astack': <contextlib.AsyncExitStack object at 0x7f7eb5d17290>,
        'app': <fastapi.applications.FastAPI object at 0x7f7edbe8c250>,
        'router': <fastapi.routing.APIRouter object at 0x7f7ed8d85b50>,
        'endpoint': <function FastAPI.setup.<locals>.swagger_ui_html at 0x7f7ed8d99200>,
        'path_params': {}
    },
    'method': 'GET',
    'path': '/docs',
    'full_path': '/docs',
    'client_addr': '192.168.87.193:41938',
    'request$line': '\x1b[1mGET /docs HTTP/1.1\x1b[0m',
    'http_version': '1.1',
    'levelprefix': '\x1b[32mINFO\x1b[0m:    '
}
```

My stopgap solution just strips out the troublemaking values.

**Comment by tchaton** [comment]
@tiangolo Same problem with

```
from fastapi import FastAPI
import uvicorn

app = FastAPI()

def test_uvicorn():

    uvicorn.run(app=app, workers=4)
```
