### ISSUE TITLE
Error adding middleware

### ISSUE THREAD

**Issue by dreamfalcon** [tiangolo/fastapi#1646]
Hi,

I'm trying to learn with this example to build a websockets service:
[https://github.com/cthwaite/fastapi-websocket-broadcast](url)

But getting this error:
```
(env) C:\celfinet\websockets\app>uvicorn app:app
Traceback (most recent call last):
  File "C:\Users\daniel.m.silva\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\daniel.m.silva\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\celfinet\websockets\env\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "c:\celfinet\websockets\env\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\celfinet\websockets\env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\celfinet\websockets\env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\celfinet\websockets\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\celfinet\websockets\env\lib\site-packages\uvicorn\main.py", line 331, in main
    run(**kwargs)
  File "c:\celfinet\websockets\env\lib\site-packages\uvicorn\main.py", line 354, in run
    server.run()
  File "c:\celfinet\websockets\env\lib\site-packages\uvicorn\main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\daniel.m.silva\AppData\Local\Programs\Python\Python37\Lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\celfinet\websockets\env\lib\site-packages\uvicorn\main.py", line 389, in serve
    config.load()
  File "c:\celfinet\websockets\env\lib\site-packages\uvicorn\config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\celfinet\websockets\env\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\celfinet\websockets\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\app.py", line 185, in <module>
    app.add_middleware(RoomEventMiddleware)
  File "c:\celfinet\websockets\env\lib\site-packages\starlette\applications.py", line 117, in add_middleware
    self.middleware_stack = self.build_middleware_stack()
  File "c:\celfinet\websockets\env\lib\site-packages\starlette\applications.py", line 81, in build_middleware_stack
    app = cls(app=app, **options)
TypeError: __init__() got an unexpected keyword argument 'app'
```
Not sure if a bug or change in a recent version of FastAPI.

* FastAPI Version 0.58.1:

**Comment by dreamfalcon** [comment]
Fixed:
```
class RoomEventMiddleware:  # pylint: disable=too-few-public-methods
    def __init__(self, app):
        self._app = app
        self._room = Room()

    async def __call__(self, scope: Scope, receive: Receive, send: Send):
        if scope["type"] in ("lifespan", "http", "websocket"):
            scope["room"] = self._room
        await self._app(scope, receive, send)

app.add_middleware(RoomEventMiddleware)
```

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
