### ISSUE TITLE
#Problem.

### ISSUE THREAD

**Issue by codefather-labs** [tiangolo/fastapi#1842]
Stack:
- FastAPI
- Tortoise ORM
- Pydantic model (serialization only)

**Model 1**
```python
class TelegramSubscriber(Subscriber):
    application: fields.ForeignKeyRelation = fields.ForeignKeyField(
        model_name="telegramcms.TelegramApplication",
        related_name='telegram_group_subscriber',
        on_delete=fields.SET_NULL,
        null=True
    )

    class Serializer(BaseModel):
        id: Optional[int]
        data: Optional[dict]
        hashes: Optional[dict]
        application: Optional[dict]

    serializer = Serializer
```
**Model 2**

```python
class TelegramSubscription(Subscription):
    subscribers: fields.ManyToManyRelation = fields.ManyToManyField(
        model_name="telegramcms.TelegramSubscriber",
        default=None,
        related_name='subscription',
        null=True
    )

    class APISerializer(BaseModel):
        id: Optional[int]
        source: Optional[str]
        subscribers: List[TelegramSubscriber.serializer]

    serializer = APISerializer
```

**View**
```python
@self.application.post('/subscriber', response_model=TelegramSubscriber.serializer)
async def create_subscriber(data: TelegramSubscriber.serializer):
                ......
```

Inside of both models i got serializers and vars wich calling them. 

```python
    class Serializer(BaseModel):
        id: Optional[int]
        data: Optional[dict]
        hashes: Optional[dict]
        application: Optional[dict]

    serializer = Serializer

    class APISerializer(BaseModel):
        id: Optional[int]
        source: Optional[str]
        subscribers: List[TelegramSubscriber.serializer]

    serializer = APISerializer
```

if you pay attention to the names of the serializers, you will see that they are named differently. I would like to create a unified view of data serializers, that's why I have a serializer variable pointing to a specific type. so, the problem is that if I try to name both types of serializer the same, I catch the error. Take a trace.

```
telegramcms.services | INFO:     172.25.0.1:53308 - "GET /docs HTTP/1.1" 200 OK
telegramcms.services | INFO:     172.25.0.1:53308 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
telegramcms.services | ERROR:    Exception in ASGI application
telegramcms.services | Traceback (most recent call last):
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
telegramcms.services |     result = await app(self.scope, self.receive, self.send)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
telegramcms.services |     return await self.app(scope, receive, send)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 181, in __call__
telegramcms.services |     await super().__call__(scope, receive, send)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 111, in __call__
telegramcms.services |     await self.middleware_stack(scope, receive, send)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
telegramcms.services |     raise exc from None
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
telegramcms.services |     await self.app(scope, receive, _send)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
telegramcms.services |     raise exc from None
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
telegramcms.services |     await self.app(scope, receive, sender)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 566, in __call__
telegramcms.services |     await route.handle(scope, receive, send)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 227, in handle
telegramcms.services |     await self.app(scope, receive, send)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 41, in app
telegramcms.services |     response = await func(request)
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 130, in openapi
telegramcms.services |     return JSONResponse(self.openapi())
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 105, in openapi
telegramcms.services |     self.openapi_schema = get_openapi(
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/fastapi/openapi/utils.py", line 349, in get_openapi
telegramcms.services |     definitions = get_model_definitions(
telegramcms.services |   File "/usr/local/lib/python3.8/dist-packages/fastapi/utils.py", line 64, in get_model_definitions
telegramcms.services |     model_name = model_name_map[model]
telegramcms.services | KeyError: <class 'services.scheduler.models.TelegramSubscription.APISerializer'>
```
but if I rename APISerializer by unique name then this error goes away.

**Comment by codefather-labs** [comment]
whats going on https://github.com/tiangolo/fastapi/blob/master/fastapi/utils.py in get_model_definitions?

**Comment by Kludex** [comment]
Do you mind providing a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? It makes it easy to help you. :tada:

Also, if you can follow the template, it would be awesome. :sunglasses: 
It contains information that we can use, and the next ones looking for this problem, like FastAPI version.

A secret bonus, not needed, but cool (it's an image):
![image](https://user-images.githubusercontent.com/7353520/89457716-18be9280-d766-11ea-8da4-e877dc2a214f.png)

You'll get this (it's a code):
```python
def fun(param: str):
    return param
```

**Comment by tiangolo** [comment]
Humm, with respect to FastAPI, Pydantic models are not intended to be created as class attributes inside other classes and then being renamed.

FastAPI collects all the models from all the *path operations* to generate all the JSON Schemas for all that and then generate the OpenAPI for the whole API. And it needs the names and locations of those models to know which ones are the same, which ones are already processed, which ones are fields of other models, etc.
