### ISSUE TITLE
Need help Get a error when i uesd websocket by fastapi [ERROR] Exception in ASGI application

### ISSUE THREAD

**Issue by justonlyyo** [tiangolo/fastapi#1888]
my code(part):

ws_server.py

```python
...

@app.websocket("/ws")
async def websocket_view(websocket: WebSocket, at: str, from_id: int = None):
        flag = True
        await manager.connect(websocket=websocket, user_id=1)
        while flag:
            """等待消息并发送"""
            json_data = await websocket.receive_json()
            websocket = manager.active_connections.get(1)
            await manager.send_message(websocket=websocket, message=json_data)`
```

run it

```shell
gunicorn3 ws_server:app -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
```

client's html and javascript:

ws_demo.html

```html
<script>
...


    function send_mes() {
        let data = {
            payload: { "content": "hello"}, 
            mes_type: "message",  
            from_id: from_id, 
            to_id: to_id, 
        };
      // this is stress testing
        let interval = setInterval(()=>{
            client.send(JSON.stringify(data));
            send_count += 1
        }, 1);
        
        setTimeout(()=>{
            clearInterval(interval);
        }, 5000);

    }
</script>
```

Most of the time, everything is all right.but some time ,  it throw a exception:

```shell
[2020-08-13 09:44:43 +0800] [18495] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/walle/.local/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 153, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/home/walle/.local/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/walle/.local/lib/python3.6/site-packages/fastapi/applications.py", line 167, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/home/walle/.local/lib/python3.6/site-packages/fastapi/routing.py", line 242, in app
    await dependant.call(**values)
  File "/home/walle/work/projects/QK5178org/ws_server.py", line 204, in websocket_view
    raise e
  File "/home/walle/work/projects/QK5178org/ws_server.py", line 187, in websocket_view
    json_data = await websocket.receive_json()
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/websockets.py", line 97, in receive_json
    message = await self.receive()
  File "/home/walle/.local/lib/python3.6/site-packages/starlette/websockets.py", line 40, in receive
    message = await self._receive()
  File "/home/walle/.local/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 233, in asgi_receive
    data = await self.recv()
  File "/home/walle/.local/lib/python3.6/site-packages/websockets/protocol.py", line 474, in recv
    "cannot call recv while another coroutine "
RuntimeError: cannot call recv while another coroutine is already waiting for the next message
2020-08-13 09:44:43,575 protocol.py[line:1354] DEBUG server - event = connection_lost(None)
2020-08-13 09:44:43,575 protocol.py[line:1356] DEBUG server - state = CLOSED
2020-08-13 09:44:43,575 protocol.py[line:1365] DEBUG server x code = 1006, reason = [no reason]
2020-08-13 09:44:43,575 protocol.py[line:1261] DEBUG server ! failing CLOSED WebSocket connectio
```

console of browser 

```
Uncaught INVALID_STATE_ERR : Pausing to reconnect websocket
...
Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
```
![image](https://user-images.githubusercontent.com/20040033/90086332-c4f70f00-dd4c-11ea-8451-ffe93a9f0cea.png)

**Comment by LindezaGrey** [comment]
Hi,
does it work when you call gunicorn with just 1 worker? 
`gunicorn3 ws_server:app -w 1 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker`

had a similiar problem with [socketio](https://python-socketio.readthedocs.io/en/latest/server.html#uvicorn-daphne-and-other-asgi-servers)

**Comment by justonlyyo** [comment]
I Tried, same result : some time throw  exception.

**Comment by Dustyposa** [comment]
I think you miss `accept`.
Can you work with this [example](https://fastapi.tiangolo.com/advanced/websockets/) ?

**Comment by SaraUris** [comment]
Can you run it with uvicorn instead of gunicorn3?

**Comment by tiangolo** [comment]
Thanks for the help here everyone! :clap: :bow: 

If the original problem is solved, then you can close this issue :heavy_check_mark:

Otherwise, please provide a simple example that shows the error, that way it will be easier to help you.
