### ISSUE TITLE
Form or File not working with APIRouter

### ISSUE THREAD

**Issue by a-n-s** [tiangolo/fastapi#2081]
File as well as Form input is working in Fastapi object   but not APIRouter object. 
This is not working -- >
```
router = APIRouter()
@router.post("/profile/update-media")
async def update_media(
    file: bytes = File(...)
):
    return True
```

This is working --->
```
router = FastAPI()
@router.post("/profile/update-media")
async def update_media(
    file: bytes = File(...)
):
    return True
```
In APIRouter one I  am getting key error in fastapi utils.
Traceback-
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 388, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\fastapi\applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__    
    raise exc from None
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__    
    await self.app(scope, receive, _send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\middleware\base.py", line 25, in __call__       
    response = await self.dispatch_func(request, self.call_next)
  File ".\app\main.py", line 50, in log_requests
    response = await call_next(request)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\middleware\base.py", line 45, in call_next      
    task.result()
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\fastapi\applications.py", line 128, in openapi
    return JSONResponse(self.openapi())
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\fastapi\applications.py", line 106, in openapi
    self.openapi_schema = get_openapi(
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\fastapi\openapi\utils.py", line 343, in get_openapi
    definitions = get_model_definitions(
  File "c:\users\aditya.shanbhog\appdata\local\programs\python\python38-32\lib\site-packages\fastapi\utils.py", line 28, in get_model_definitions
    model_name = model_name_map[model]
KeyError:
```

**Comment by adityashanbhog** [comment]
Opening open api docs gives the error.

**Comment by ArcLightSlavik** [comment]
APIRouter is most likely not at fault here. This works for me:

```
from fastapi import FastAPI, APIRouter, File, UploadFile


app = FastAPI()

router = APIRouter()


@router.post("/profile/update-media")
async def update_media(file: UploadFile = File(...)):
    return {"filename": file.filename}


app.include_router(router)
```

<img width="691" alt="Screenshot 2020-09-21 at 16 35 19" src="https://user-images.githubusercontent.com/31127044/93773198-7af52900-fc28-11ea-9a2e-5cbf0a68742d.png">


Could you expand on the example you provided?
Are you using Pydantic models?

**Comment by adityashanbhog** [comment]
I am using pydantic models in the project. Using Form also gives the same error.

**Comment by ArcLightSlavik** [comment]
@adityashanbhog
Try this: https://github.com/tiangolo/fastapi/issues/1989

**Comment by adityashanbhog** [comment]
@ArcLightSlavik  Thanks Its working now.
Closing this issue.

**Comment by tiangolo** [comment]
Thanks for the help @ArcLightSlavik! 🚀 

And thanks for coming back to close the issue @a-n-s ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
