### ISSUE TITLE
sending JSON over websocket with external synchronous function

### ISSUE THREAD

**Issue by yovelcohen** [tiangolo/fastapi#2107]
Hi, I'm trying to open a WebSocket which receives a msg, runs some processes based on that message, and returns the response.
```
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        stock = await websocket.receive_text()
        stock = stock.upper()
        data = sentiment_analysis(stock=stock)
        await websocket.send_json(data)
````
the error trace:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 153, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 228, in app
    await dependant.call(**values)
  File "./app.py", line 14, in websocket_endpoint
    stock = await websocket.receive_text()
  File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 85, in receive_text
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 80, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1011

```
the stack trace suggests that the bug is in the line:
 ```        
stock = await websocket.receive_text()
```
but adding sprint statements shows that the sentiment analysis function receives the messages and outputs a return properly, so the send_json is somehow the issue?
the data variable is a dictionary.

**Comment by includeamin** [comment]
[check it out](https://fastapi.tiangolo.com/advanced/websockets/#handling-disconnections-and-multiple-clients)

**Comment by krishnardt** [comment]
you can check this resource...
[https://www.starlette.io/websockets/](url)
fastapi works on top of starlette..

> JSON messages default to being sent over text data frames, from version 0.10.0 onwards. Use websocket.send_json(data, mode="binary") to send JSON over binary data frames.

> if you send and receive any type of data.. you can directly use 
> websocket.send()
> websocket.receive()

I guess this will resolve your problem..

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

If that solves the original problem, then you can close this issue @yovelcohen  ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
