### ISSUE TITLE
all requests return internal server error.

### ISSUE THREAD

**Issue by pcs3rd** [tiangolo/fastapi#2147]
Currently, I am trying to do a simple web hook, this is my code
```
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def root():
    return {"Status": "ok"}
#script control
@app.get("/hooks/control/syncremote")
async def syncremote():
    exec(open("uploadData.py").read())
    return {"Status": "ok"}
@app.get("/hooks/control/reloadSync")
async def reloadSync():
    exec(open("populateSyncList.py").read())
    return {"Status": "ok"}
#other

```

And this is the resulting output.

```
pi@dataprocessing-pi:~/QBSQ-1.0 $ uvicorn swc:app --port 8001 --host 0.0.0.0
INFO: Started server process [14606]
INFO: Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 388, in run_asgi
    asgi = app(self.scope)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
INFO: ('192.168.0.197', 49914) - "GET / HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 388, in run_asgi
    asgi = app(self.scope)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
INFO: ('192.168.0.197', 49915) - "GET /favicon.ico HTTP/1.1" 500
                
```

**Comment by pcs3rd** [comment]
This seems to be a distribution package issue. Raspbian lite.

**Comment by Mause** [comment]
What versions of uvicorn and fastapi are you using?

**Comment by neiljdo** [comment]
@pcs3rd I solved this issue by updating my `uvicorn` version to at least `0.7.0`. From https://github.com/encode/uvicorn/blob/b4c138910bb63475efd028627e10adda722e4937/uvicorn/middleware/message_logger.py#L54, you can see that the `__call__` function is called correctly with the problematic args.
