### ISSUE TITLE
Use of `contextlib.contextmanager` with `Depends`

### ISSUE THREAD

**Issue by eseglem** [tiangolo/fastapi#2212]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Description

Based on [A dependency with yield and try](https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/#a-dependency-with-yield-and-try) I wanted to try and reuse the same code to manage sessions in other parts of my app (tests, management scripts, setup, etc.). So based on my reading of the [Tip](https://github.com/tiangolo/fastapi/blame/master/docs/en/docs/tutorial/dependencies/dependencies-with-yield.md#L214-L226) at the bottom, I tried adding `@contextlib.contextmanager` to the function. Which prevents `Depends(get_db)` from working correctly. 

The Tip says you don't *have* to use the decorators, and that you *shouldn't*. To me, this implies it is possible to use the decorator, but discouraged. Unfortunately, it appears it is not possible. I would guess this functionality is probably working as intended, and the docs can be updated to be more clear. Perhaps just remove reference to `@contextlib.contextmanager`? 

I did dig into the code to see if there was something obvious that I could do to make this work, but I was not able to come up with anything yet. 

### Example

Below is a standalone snippet to show the current functionality. It remains true for async generators as well. 

```Python
from contextlib import contextmanager
from typing import Generator
from fastapi import FastAPI, Depends

class DBSession:
    def query(self, text: str) -> str:
        return text

    def close(self) -> None:
        pass

def get_session_without() -> Generator[DBSession, None, None]:
    session = DBSession()
    try:
        yield session
    finally:
        session.close()

@contextmanager
def get_session_with() -> Generator[DBSession, None, None]:
    session = DBSession()
    try:
        yield session
    finally:
        session.close()

app = FastAPI()

@app.get("/without")
async def route_without_session(
    session: DBSession = Depends(get_session_without),
) -> str:
    return session.query("blah")

@app.get("/with")
async def route_with_session(
    session: DBSession = Depends(get_session_with),
) -> str:
    return session.query("blah")

if __name__ == "__main__":
    from fastapi.testclient import TestClient

    client = TestClient(app)
    print(client.get("/without"))
    print(client.get("/with"))
```

This results in the following:
```
<Response [200]>
Traceback (most recent call last):
  File "mvp.py", line 54, in <module>
    print(client.get("/with"))
...
  File "mvp.py", line 46, in route_with_session
    return session.query("blah")
AttributeError: '_GeneratorContextManager' object has no attribute 'query'
```

### Environment

* OS: Ubuntu-20.04
* FastAPI Version: 0.61.1
* Python version: 3.8.5

### Additional context

The workaround is something like this: 

```python
@contextmanager
def get_session_with() -> Generator[DBSession, None, None]:
    session = DBSession()
    try:
        yield session
    finally:
        session.close()

def get_session_without() -> Generator[DBSession, None, None]:
    with get_session_with() as session:
        yield session
```

Where you `Depends(get_session_without)` on your routes, and `with get_session_with() as session:` anywhere else you want to use it. Which is totally OK. 

### Unrelated to the issue

Happy to dig through issues, and see how I can contribute, but I am curious is it also helpful to hang out on gitter and try to assist people on there? Is that perhaps something to add to the "After submitting this, I commit to one of:" section at the top? I have been doing it anyways, and will keep doing so when I have time either way. Just wondering.

**Comment by jan-golda** [comment]
I would like to dump this one as I think this would be a great improvement to FastAPI.

Let's say I have a simplified service like this:
```python
class FooService:
    def __init__(self):
        self._conn = None

    def __enter__(self):
        self._conn = BarConnection()  # init connection
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self._conn.close()  # close connection

    def do_something():
        self._conn.do_something()  # use connection
```

If support for context managers was added I could simply use it this way:
```python
@app.get("/endpoint")
def endpoint(foo_service: FooService = Depends()):
    foo_service.do_something()
```

But unfortunately, now I have to use a [workaround from documentation](https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/#using-context-managers-in-dependencies-with-yield):
```python
def get_foo_service():
    with FooService() as service:
        yield service

@app.get("/endpoint")
def endpoint(foo_service: FooService = Depends(get_foo_service)):
    foo_service.do_something()
```

I know it's essentially an aesthetic change, but for some people stuff like this matters.

I would be happy to contribute with the needed changes if only I could get some pointers from the maintainers on how they would see this implemented.
