### ISSUE TITLE
How to catch HTTPException with specific code?

### ISSUE THREAD

**Issue by uvicorn** [tiangolo/fastapi#2291]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example
I want to create code 500(internal server error) httpexception handler:
```Python
from fastapi import FastAPI
from fastapi.exceptions import HTTPException
from fastapi.responses import PlainTextResponse


app = FastAPI()


@app.exception_handler(HTTPException(status_code=500))
async def InternalErrorHandler(self, request, exc):
    return PlainTextResponse(str(exc.detail), status_code=exc.status_code)
```
But ```@app.exception_handler``` must get a class, not a class instance.
Traceback:
```
(.venv) /mnt/c/Users/kir/Projects/easystart/backend/app(master ✗) uvicorn app.__main__:appTraceback (most recent call last):
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 339, in main
    run(**kwargs)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 397, in serve
    config.load()
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./app/__main__.py", line 29, in <module>
    async def internalerror(self, request, exc):
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/starlette/applications.py", line 151, in decorator
    self.add_exception_handler(exc_class_or_status_code, func)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/starlette/applications.py", line 125, in add_exception_handler
    self.middleware_stack = self.build_middleware_stack()
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/starlette/applications.py", line 81, in build_middleware_stack
    app = cls(app=app, **options)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 35, in __init__
    self.add_exception_handler(key, value)
  File "/mnt/c/Users/kir/Projects/easystart/backend/app/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 45, in add_exception_handler
    assert issubclass(exc_class_or_status_code, Exception)
TypeError: issubclass() arg 1 must be a class
```

### Environment
* OS: Windows 10(wsl ubuntu)
* FastAPI Version: 0.54.2
* Python version: 3.9

**Comment by Kludex** [comment]
If you want to override the default exception handler for `HTTPException`, [this can be useful](https://fastapi.tiangolo.com/tutorial/handling-errors/#override-the-default-exception-handlers).

The problem on your implementation:
`@app.exception_handler(HTTPException(status_code=500))` -> `@app.exception_handler(HTTPException)`

**Comment by peach-lasagna** [comment]
@Kludex, thx! i found an answer in starlette [sources](https://github.com/encode/starlette/blob/7a783d3b0e381acd81079aa73058fa1394447ce4/starlette/applications.py#L158):
i can use statuscode instead of Exception class!

```python
@app.exception_handler(500)
async def InternalErrorHandler(self, request):
    return PlainTextResponse("nonono")
```

@tiangolo , how about add this to docs?

**Comment by tiangolo** [comment]
Thanks for the help @Kludex ! 🍰 

@uvicorn yep, I would take a PR adding stuff around that to the docs. 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
