### ISSUE TITLE
How to access user credentials send through ajax call with OAuth2PasswordRequestForm

### ISSUE THREAD

**Issue by Ahtii** [tiangolo/fastapi#2294]
Hi,

I am creating a simple login form on the frontend and sending the username and password to my endpoint with ajax call like this:

**Ajax call to endpoint:**
```
$.ajax({
       type: 'POST',
       url: '/api/token',
       contentType: "application/json",
       dataType: "json",
       data: JSON.stringify( {"username": $("#username").val(), "password": $("#password").val()})
});
```
on the backend I want to receive the credentials and generate a token after successfully login the user like this:

**My endpoint**

```
@app.post("/api/token")
async def login(response: Response, credentials: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    user = views.authenticate(db, credentials.username, credentials.password)
    if not user:
        raise HTTPException(status_code=400, detail="Incorrect username or password")
    access_token = views.gen_token(user.username)
    response.set_cookie(key="access_token", value=f"Bearer {access_token}", httponly=True)
    return
```

with the above code I get error:  `422 Unprocessable Entity` so I replaced  `OAuth2PasswordRequestForm` with my custom pydantic model:

**Login validator:**

```
class LoginValidator(BaseModel):
    username: str
    password: str
```

Now it works but then this line: `response.set_cookie(key="access_token", value=f"Bearer {access_token}", httponly=True)` does not set the cookie and hence the user cannot be logged in. 

**Edit:**

Okay I saw this in docs:

> The spec also states that the username and password must be sent as form data (so, no JSON here).

so I modified ajax call to this:

```
$.ajax({
       type: 'POST',
       url: '/api/token',
       data:{"username": $("#username").val(), "password": $("#password").val()}
});
```

Okay now I don't get error by the cookie is still not set.

**Comment by Mause** [comment]
Have you tried returning the response?

**Comment by Ahtii** [comment]
you mean returning the `response` variable after setting the cookie ? yes I get a `keyError: None` also I tried test my endpoint with swagger UI and it works there I can see the cookie being set.

**Comment by Ahtii** [comment]
@Mause I get the following error when returning response:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Call stack:
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/main.py", line 419, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 391, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/responses.py", line 132, in __call__
    await send(
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 453, in send
    self.access_logger.info(
Message: '%s - "%s %s HTTP/%s" %d'
Arguments: ('127.0.0.1:37840', 'POST', '/api/token', '1.1', None)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 391, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/responses.py", line 132, in __call__
    await send(
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/home/ahtisham/ENVS/ENV_COLLAB/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 464, in send
    content = [STATUS_LINE[status_code]]
KeyError: None

```

**Comment by Mause** [comment]
Sounds like you need to set a status code on the response.

But if it's working in the swagger ui there might not be an issue with the API?

**Comment by Ahtii** [comment]
okay I fixed it by setting `response.status_code = 200` what is the difference between the two:

```
async def login(response: Response, ...):
     response.set_cookie(...)
     return response
```

and this

```
async def login(...):
     response = Response()
     response.set_cookie(...)
     return response
```

with the later code It works without setting the `status_code`.

also one thing I noticed In swagger UI I can see the cookie being set in the browser but in my custom view it doesn't show the cookie being set only until I move to some other endpoint.

**Comment by Mause** [comment]
What do you mean by "showing the cookie being set"?

**Comment by tiangolo** [comment]
Thanks for the help @Mause! 🍰 

@Ahtii I imagine you solved your use case, I'm gonna close this issue. If you still have problems please create a new issue following all the template and filling a simple self contained example that reproduces your use case.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
