### ISSUE TITLE
fastapi/applications.py", line 55     **extra: Any

### ISSUE THREAD

**Issue by TobiaszG24** [tiangolo/fastapi#2378]
### app.py in /app
```Python
# external libraries
import uvicorn
from fastapi import FastAPI
from pydantic import BaseSettings

class Config(BaseSettings):
    API_APP_NAME="name"
    APP_VERSION="1"
    EXPOSE_PORT=80
    DEVELOPMENT=True
    WORKERS=1
    TIMEOUT=5


conf = Config()

# main instance of webserver
app = FastAPI(
    title=conf.API_APP_NAME,
    description="Auth users and resources",
    version=conf.APP_VERSION,
)

@app.get("/healthcheck", tags=["app"])
def healthcheck():
    return True

# start config
if __name__=="__main__":
    uvicorn.run(
        "app:app", 
        host='0.0.0.0', 
        port=conf.EXPOSE_PORT, 
        reload= conf.DEVELOPMENT, 
        debug= conf.DEVELOPMENT, 
        workers=conf.WORKERS, 
        timeout_keep_alive=conf.TIMEOUT)
```

### Traceback

```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from fastapi import FastAPI
  File "/usr/local/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 55
    **extra: Any,
                ^
SyntaxError: invalid syntax
```

### Environment

* OS: WSL 2 (Linux)

### Additional context - Docker file

```Docker
########################################################################################
#
# This build stage builds the sources
#
######################################################################################## 

FROM python:3.8 AS builder

# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir /app
WORKDIR /app
# Copy the requirements file in order to install
# Python dependencies
COPY requirements.txt .
# Install Python dependencies
RUN pip install --upgrade pip --upgrade setuptools                            
RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes python3-venv gcc libpython3-dev 
RUN pip install -r requirements.txt  
# We copy the rest of the codebase into the image
COPY . .

########################################################################################
#
# This build stage creates an anonymous user to be used with the distroless build
# as defined below.
#
########################################################################################
FROM python:3.8 AS anon-user
RUN sed -i -r "/^(root|nobody)/!d" /etc/passwd /etc/shadow /etc/group \
    && sed -i -r 's#^(.*):[^:]*$#\1:/sbin/nologin#' /etc/passwd

########################################################################################
#
# This build stage creates a distroless image for production.
#
##############################################################################

FROM gcr.io/distroless/python3
COPY --from=builder /app /app
COPY --from=builder /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
COPY --from=anon-user /etc/passwd /etc/shadow /etc/group /etc/

ENV LC_ALL C.UTF-8

USER nobody
WORKDIR /app
# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app
ENV PYTHONPATH=/usr/local/lib/python3.8/site-packages

CMD ["app.py"]
```

**Comment by Mause** [comment]
Can you try without the PYTHONPATH being set? And give us that error

**Comment by TobiaszG24** [comment]
```Traceback (most recent call last):

File "app.py", line 2, in <module>

import uvicorn

ImportError: No module named 'uvicorn'

**Comment by Mause** [comment]
Are you installing uvicorn?

**Comment by TobiaszG24** [comment]
My requirements.txt file
 ```
fastapi==0.61.1
uvicorn==0.11.3
python-multipart==0.0.5
python-jose==3.2.0
jose==1.0.0
passlib==1.7.4
bcrypt==3.2.0
pydantic[email]==1.7.2
odmantic==0.3.1
bson==0.5.10
pymongo==3.11.0
```

**Comment by Mause** [comment]
Try with 

```docker
CMD ["python3.8", "app.py"]
```

**Comment by TobiaszG24** [comment]
I got this:
`/usr/bin/python3.5: can't open file 'python3.8': [Errno 2] No such file or directory`

**Comment by Mause** [comment]
Where did you copy this Dockerfile from?

**Comment by Mause** [comment]
Where did you copy this Dockerfile from?

**Comment by Mause** [comment]
Gcr distroless does not currently support python 3.8: https://github.com/GoogleContainerTools/distroless/issues/564

**Comment by TobiaszG24** [comment]
thx

**Comment by tiangolo** [comment]
Thanks for the help here @Mause ! :clap: :bow: 

Thanks for reporting back and closing the issue @TobiaszG24  :+1:
