### ISSUE TITLE
How to store a received file from websocket in FastAPI

### ISSUE THREAD

**Issue by Ahtii** [tiangolo/fastapi#2403]
Hi,
I am trying to sending a message with a file through websockets and receiving it on the backend like this:

**Javascript:**        
```
    function sendMessage(uploaded_file) {
        data = {
            "message": "some message",
            "sender": "some sender"
        };        
        websocket.send(JSON.stringify(data));
        websocket.send(uploaded_file);
   }
```
**FastAPI**
```
    while True:
         data = await websocket.receive_json()
         message = data["message"]
         sender = data['sender']
         file = await websocket.receive_bytes()
```
Now I want to read the file and store it somewhere but I am not able to do so.

**Read File**
```
     output_file = open(file, "rb")
     byte = output_file.read(1)
     while byte:
          print(byte)
          byte = output_file.read(1)
```
The above code gives the following error:
```
Traceback (most recent call last):
  File "/my_env/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 154, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/my_env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/my_env/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/my_env/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/my_env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/my_env/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/my_env/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/my_env/lib/python3.8/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/my_env/lib/python3.8/site-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/my_env/lib/python3.8/site-packages/fastapi/routing.py", line 228, in app
    await dependant.call(**values)
  File "./main.py", line 213, in direct_chat
    output_file = open(file, "rb")
ValueError: embedded null byte
```
I am not sure if that is the right way to receive a file through websockets please help.

**Comment by Ahtii** [comment]
@Mause Please help :)

**Comment by Ahtii** [comment]
This seems to fix the problem:

**javascript:**

```
    function sendMessage(uploaded_file) {
        data = {
            "message": "some message",
            "sender": "some sender",
            "filename": file['filename']                  // sended filename
        };        
        websocket.send(JSON.stringify(data));
        websocket.send(uploaded_file);
   }

```
**FastAPI:**

```
       while True:
             data = await websocket.receive_json()
             receiver = data["receiver"]
             filename = data['filename']
             file = await websocket.receive_bytes()

             with open(filename, "wb") as f:
                    f.write(file)
```

**Comment by includeamin** [comment]
please close the issue if your problem solved.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
