### ISSUE TITLE
Error downloading http://127.0.0.1:8000/openapi.json HTTP ERROR 500Something went wrong... on http://127.0.0.1:8000/redoc or /docs

### ISSUE THREAD

**Issue by akshaynarula** [tiangolo/fastapi#2406]
Something went wrong...
Error downloading http://127.0.0.1:8000/openapi.json HTTP ERROR 500
Stack trace
Error: Error downloading http://127.0.0.1:8000/openapi.json 
HTTP ERROR 500
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28049
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:80:36080

Error: HTTP ERROR 500
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28049
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:80:35658

_Originally posted by @akshaynarula in https://github.com/tiangolo/fastapi/issues/2082#issuecomment-733178552_

**Comment by includeamin** [comment]
HI,
we need more information to help you.
- Sample Code
- Python Version
- FastApi Version

**Comment by ycd** [comment]
Can you reproduce how did you get this? I mean WDYM by downloading the `openapi.json`.

**Comment by akshaynarula** [comment]
```python
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/middleware/trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/fastapi/applications.py", line 128, in openapi
    return JSONResponse(self.openapi())
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/fastapi/applications.py", line 106, in openapi
    self.openapi_schema = get_openapi(
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 348, in get_openapi
    result = get_openapi_path(route=route, model_name_map=model_name_map)
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 177, in get_openapi_path
    operation_parameters = get_openapi_operation_parameters(
  File "/home/ubuntu/LambdaProjects/mustard/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 95, in get_openapi_operation_parameters
    "schema": field_schema(
  File "pydantic/schema.py", line 215, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 183, in pydantic.schema.get_field_info_schema
  File "pydantic/schema.py", line 846, in pydantic.schema.encode_default
  File "pydantic/json.py", line 65, in pydantic.json.pydantic_encoder
TypeError: Object of type 'function' is not JSON serializable
```

**Comment by akshaynarula** [comment]
![Screenshot](https://user-images.githubusercontent.com/67769279/100412653-43c54d00-309b-11eb-8a00-534e682d3a26.png)
![Screenshot](https://user-images.githubusercontent.com/67769279/100412657-46c03d80-309b-11eb-98d2-17f2ac67d5ec.png)

**Comment by Mause** [comment]
It looks like you're incorrectly defining your endpoints and including a function where it isn't valid.

Perhaps you could provide some code?

**Comment by akshaynarula** [comment]
I have few **http** endpoints and  **websocket** endpoints, nothing else.

**Comment by akshaynarula** [comment]
> HI,
> we need more information to help you.
> 
> * Sample Code
> * Python Version
> * FastApi Version

Code contains few HTTP and WebSocket endpoints
Python 3.8
fastapi 0.61.1

**Comment by Mause** [comment]
Unless you provide code, we cannot help you.

**Comment by and-se** [comment]
Hello. I have the same problem with error TypeError("Object of type 'function' is not JSON serializable"). Stacktrace is useless.

Example code:
```python3
@app.get('/fail')
def test_request_dependant(rq: Request = Depends()):
    return """This will fail entire app with TypeError("Object of type 'function' is not JSON serializable") and useless stacktrace"""
```

The problem with using Depends() for getting Request object. According to [documentation](https://fastapi.tiangolo.com/advanced/using-request-directly/) we must do:
```python3
@app.get('/fail')
def test_request_dependant(rq: Request):
    return "OK"
```

It helps.
I think you need provide clear error message at least (and write warning in [documentation](https://fastapi.tiangolo.com/advanced/using-request-directly/)). Or best - make Depend() work correctly in this case.

**Comment by and-se** [comment]
There are some workarounds:

```python3
class RequestDependProvider:
    async def __call__(self, request: Request) -> Request:
        return request

provider = RequestDependProvider()

@app.get('/work')
def route(request: Request = Depends(provider)):
    ...
```

```python3

class RequestContainer:
    def __init__(self, request: Request):
        self.rq = request

@app.get('/work')
def route(rq: RequestContainer = Depends()):
    request = rq.rq
```

The advantage is that you can get the request object anywhere, not just in the route function

**Comment by bnmnetp** [comment]
I'm getting the same outcome, but a slightly different error. 

`TypeError: Object of type 'type' is not JSON serializable`

The lines of code causing the problem are:

```python
@router.post("/validate")
async def login(
    data: OAuth2PasswordRequestForm = Depends(),
    response_class=RedirectResponse
    # ):
```

If I eliminate the `response_class` parameter the docs work just fine.

It doesn't seem to impact the workings of the application, but I would like to understand why it causes the crash in this case.  I use the `response_class ` parameter elsewhere and it doesn't cause a problem.

Thanks!

**Comment by deepansh96** [comment]
To debug further, one can actually go into the devtools and find the exact stack trace for the 500 error.

We're using Django so the network devtools shows the log. If you're using some other framework, I'm pretty sure you'll get more information if you devtool the error.

<img width="1676" alt="Screenshot 2022-03-28 at 2 51 01 PM" src="https://user-images.githubusercontent.com/20169829/160367628-d2a95505-1930-40a5-a890-fab089cbd08e.png">

**Comment by tiangolo** [comment]
Thanks for the help here @ycd, @Mause, @includeamin ! 🍰 

I will close this issue @akshaynarula, but if you are still having problems, please create a new issue following the template, adding a self-contained example to reproduce the problem, and fill all the steps.

Everyone else, if you are still having problems, please create a new issue, following the template, adding a code example, etc. Thanks! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
