### ISSUE TITLE
Issue in creating exe using pyinstaller with pydantic import

### ISSUE THREAD

**Issue by shivamspj** [tiangolo/fastapi#2468]
Windows 10 machine
Python 3.8.6
Pydantic 1.7.2
Pyinstaller 4.1

after creating exe, it is throwing error as follows:
```
Traceback (most recent call last):
  File "Worker.py", line 1, in <module>
  File "c:\users\kumar.shivam\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "WorkerManager.py", line 5, in <module>
  File "c:\users\kumar.shivam\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "GeocodingManager.py", line 4, in <module>
  File "c:\users\kumar.shivam\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "FormatData.py", line 5, in <module>
  File "c:\users\kumar.shivam\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "Input_output_objects.py", line 1, in <module>
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
ImportError: cannot import name dataclasses
[25236] Failed to execute script Worker
```

**Comment by Mause** [comment]
Please see https://github.com/pyinstaller/pyinstaller/issues/4346

**Comment by Phil997** [comment]
Hello
I had the same issue with anaconda and virtualenv
The is the installation of pydantic. You have to uninstall pydantic and to reinstall it with 

`pip install pydantic --no-binary pydantic`

after that install it works for anaconda and virtualenv

**Comment by tiangolo** [comment]
Thanks for the help here @Mause and @Phil997! 🍰 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
