### ISSUE TITLE
Exceptions with handlers are replaced in a background task

### ISSUE THREAD

**Issue by snazzyfox** [tiangolo/fastapi#2505]
When a background task raises an exception that has a FastAPI handler, that exception is replaced by FastAPI and the original error cannot be found in the server logs. This makes debugging and investigations incredibly hard as it's impossible to know where the error occurred.

FastAPI should preserve the original exception so that it can be logged and investigated server-side.

### Example

```Python
from fastapi import FastAPI, Request, BackgroundTasks
from fastapi.responses import JSONResponse


class UnicornException(Exception):
    def __init__(self, name: str):
        self.name = name


app = FastAPI()


@app.exception_handler(UnicornException)
async def unicorn_exception_handler(request: Request, exc: UnicornException):
    return JSONResponse(
        status_code=418,
        content={"message": f"Oops! {exc.name} did something. There goes a rainbow..."},
    )


async def process_unicorn(name: str):
    if name == "yolo":
        raise UnicornException(name=name)
    # else do_something(name)

@app.get("/unicorns/{name}")
async def sync_process_unicorn(name: str, background_tasks: BackgroundTasks):
    await process_unicorn(name)
    return name

@app.get("/unicorns_async/{name}")
async def async_process_unicorn(name: str, background_tasks: BackgroundTasks):
    """Accept the unicorn and process it in the background"""
    background_tasks.add_task(process_unicorn, name=name)
    return f"Processing {name} asynchronously."
```

### Description

- `/unicorns/yolo` correctly returns an error response
- `/unicorns_async/yolo` returns the correct response to the client. I expect error logs and traceback of a `UnicornException` on the server. However, that exception is *replaced* with one that FastAPI generates, without context. 

```
INFO:     127.0.0.1:32848 - "GET /unicorns_async/yolo HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/luyao/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/luyao/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/luyao/.local/lib/python3.8/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/home/luyao/.local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/luyao/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/luyao/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/luyao/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 86, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.
```

### Environment

* OS: Linux (Ubuntu 20.10)
* FastAPI Version: 0.62.0
* Python version: occurs on both 3.8.6 and 3.7.9

**Comment by Kludex** [comment]
I don't see the question. :thinking: 

A `BackgroundTask` runs after the successful response is sent. You should not have `HTTPException`s there.

**Comment by snazzyfox** [comment]
> I don't see the question. thinking
> 
> A `BackgroundTask` runs after the successful response is sent. You should not have `HTTPException`s there.

It's not specifically a `HTTPException`, it's a custom exception with registered handler. This allow us to for example do somethings like `raise UnicornExistsError` in the business logic parts of the application, regardless of how API routing works. 

At the same time, I think it also makes sense to handle `UnicornExistsError` in the router, as opposed to write something like this in every single route:
```py
try:
   await do_something(...)
except UnicornExistsError as e:
   raise HTTPException(process_exception(e))
except UnicornMissingError as e:
   raise HTTPException(process_exception(e))
```

I agree that exceptions are not automatically handled in the background task, nor should it. What I'm asking for is that when such an exception occurs, FastAPI should not mask over it completely. I'll update the issue to make it clear.

**Comment by Kludex** [comment]
That's not a FastAPI issue. To be honest, that's how it is _designed_. In case you want more clarification, that's more suitable in `Starlette`. 

The code that makes those decisions is [here](https://github.com/encode/starlette/blob/master/starlette/concurrency.py).

In case you want to understand the reason for `async` bkg tasks: https://stackoverflow.com/questions/60287285/starlette-asyncio-create-task-doesnt-log-error-if-task-object-is-stored-in

For `sync` the reason is even clearer, as it runs in a different thread.

**Comment by snazzyfox** [comment]
Hmm, you're right that it seems to be an issue with Starlette. I'll open an issue there instead.

I don't think this particular issue has to do with forgetting to await the result or threading though. The exception is clearly there - in fact, if I go to [the code quoted in the traceback](https://github.com/encode/starlette/blob/master/starlette/exceptions.py#L86) and insert `print(exc)` before the `raise`, it literally prints out the exact exception that the application has raised. So the original exception is available in the context; it's just being replaced with a less helpful error instead of surfaced through the logs.

**Comment by Kludex** [comment]
You're right. My bad. :sweat: 

But well, still looks a conscious decision:
```python
            if handler is None:
                handler = self._lookup_exception_handler(exc)
``` 

But asking clarifications about it seems a good idea. :+1:

**Comment by johachi** [comment]
@snazzyfox Did you ever open an issue in Starlette? I could not find anything.

Also, thank you for this thread! It did help a lot with my problem.

**Comment by Matthieu-Tinycoaching** [comment]
@snazzyfox @johachi How did you overcome this error? I still couldn't get HTTP errors defined in the background task function.

**Comment by johachi** [comment]
@Matthieu-Tinycoaching 

I needed a message broker (e.g. Rabbit MQ) to send events to other services. I solved this problem by also using the messaging broker to trigger these events async without using BackGroundTasks. However, that will probably be overkill to solve only this problem.

There is also a [good blog post here](https://johachi.hashnode.dev/important-gotchas-with-backgroundtasks-in-fastapi) on how to mitigate this problem (I'm the author) as well as [this library](https://github.com/melvinkcx/fastapi-events) that can also solve this problem for you.
