### ISSUE TITLE
FastAPI - unable to render HTML response

### ISSUE THREAD

**Issue by Barnez299** [tiangolo/fastapi#2525]
```Main.py
from fastapi import FastAPI
from typing import List, Dict

from fastapi import Depends, FastAPI, HTTPException, Request, Response
from fastapi.responses import HTMLResponse
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from fastapi.templating import Jinja2Templates

from . import crud, models, schemas
from .database import SessionLocal, engine

models.Base.metadata.create_all(bind=engine)

templates = Jinja2Templates(directory="templates")

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()



@app.get("/", response_class=HTMLResponse)
def read_notes(request: Request, skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    notes = crud.get_notes(db=db, skip=skip, limit=limit)
    print(notes)
    return templates.TemplateResponse("index.html",{
        "request": request,
        "notes": notes,
    })

if __name__ == '__main__':
    uvicorn.run("main:app", host="127.0.0.1", port=8000)
```

schemas.py
```
class NoteBase(BaseModel):
            title: str
            description: str


class NoteCreate(NoteBase):
    pass

class Note(NoteBase):
    id: int

    class Config:
        orm_mode = True
```

crud.py

```
from sqlalchemy.orm import Session

from . import models, schemas


def get_note(db: Session, note_id: int):
    return db.query(models.Note).filter(models.Note.id == note_id).first()

def delete_note(db: Session, note_id: int):
    db_note = db.query(models.Note).filter(models.Note.id == note_id).first()
    db.delete(db_note)
    db.commit()
    return {}

def get_notes(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.Note).offset(skip).limit(limit).all()


def create_note(db: Session, note: schemas.NoteCreate):
    db_note = models.Note(title=note.title, description=note.description)
    db.add(db_note)
    db.commit()
    db.refresh(db_note)
    return db_note

def update_note(db: Session, note: schemas.Note):
    db_note = db.query(models.Note).filter(models.Note.id == note.id).first()
    db_note.title = note.title
    db_note.description = note.description
    db.commit()
    db.refresh(db_note)
    return db_note
```

models.py
```
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import relationship

from .database import Base

class Note(Base):
    __tablename__ = "notes"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=True, default="new")
    description = Column(String, nullable=True, default="new")
```

database.py
```
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# SQLALCHEMY_DATABASE_URL = "sqlite:///./sql_app.db"
SQLALCHEMY_DATABASE_URL = "postgresql://postgres:password@localhost/notes"

engine = create_engine (SQLALCHEMY_DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()
```

**Comment by Barnez299** [comment]
I want to render the data in the table format on the front-end
below is the HTML format
`<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron">
                <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% for note in notes%}
                        <td>{{notes.id}}</td>
                        <td>{{notes.title}}</td>
                        <td>{{notes.description}}</td>
                        </tr>
                        {% endfor %}
                    <tr>
                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
`

**Comment by Mause** [comment]
Please format your code.

What error are you receiving?

**Comment by Barnez299** [comment]
if I understand things correct this is how the function should look
```
@app.get("/", response_class=HTMLResponse)
def read_notes(request: Request, skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    notes = crud.get_notes(db=db, skip=skip, limit=limit)
    print(notes)
    return templates.TemplateResponse("index.html",{
        "request": request,
        "id": id,
        "title": title,
        "description": description
    })
```
but this gives the following error 
```
INFO:     127.0.0.1:55139 - "GET /?skip=0&limit=100 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/fastapi/routing.py", line 188, in app
    raw_response = await run_endpoint_function(
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/fastapi/routing.py", line 137, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./sql_app/main.py", line 51, in read_notes
    "title": title,
NameError: name 'title' is not defined
```

**Comment by Mause** [comment]
The error is correct, you don't have a `title` variable in that scope?

**Comment by Barnez299** [comment]
Sorry - pleas explain or point out which line of code is incorrect?

**Comment by Mause** [comment]
As the error states, you are referring to a variable called `title` that does not exist? On line 51 of main.py

**Comment by Barnez299** [comment]
Sorry - maybe I am not understanding. When I run this function:
```
@app.get("/notes", response_model=List[schemas.Note])
def read_notes(request: Request, skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    notes = crud.get_notes(db=db, skip=skip, limit=limit)
    print(notes)
    return notes
```
I get the following - objects printed:
```
WARNING:  StatReload detected file change in 'sql_app/main.py'. Reloading...
INFO:     Started server process [23852]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:55976 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:55976 - "GET /openapi.json HTTP/1.1" 200 OK
[<sql_app.models.Note object at 0x111cc22e0>, <sql_app.models.Note object at 0x111cc22b0>, <sql_app.models.Note object at 0x111cf1820>, <sql_app.models.Note object at 0x111cf18b0>]
INFO:     127.0.0.1:55977 - "GET /notes?skip=0&limit=100 HTTP/1.1" 200 OK
```
looking at this end point-- http://127.0.0.1:8000/notes i get the following displayed in index.html. However this is in list format.
```
[   {     "title": "title 3",     "description": "title 3 description",     "id": 3   },   {     "title": "title 1 updated",     "description": "string",     "id": 1   },   {     "title": "Title updated 2",     "description": "description updated2",     "id": 2   },   {     "title": "Note 4",     "description": "Note 4 description",     "id": 4   } ]
```
As such what should the function definition be in order for me to render the output in index.html  - in a table format?

**Comment by Mause** [comment]
You are using the wrong variable name in your template - you're using notes.title instead of note.title

**Comment by Barnez299** [comment]
revisited as per comment
```
{% extends 'layout.html' %} {% include 'header.html' %} {% block title %} Home {% endblock %} {% block body %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Title</th>
                            <th scope="col">Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% for note in notes%}
                                <td>{{note.id}}</td>
                                <td>{{note.title}}</td>
                                <td>{{note.description}}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



{% endblock %}
```
same error
```
INFO:     127.0.0.1:56962 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/fastapi/routing.py", line 188, in app
    raw_response = await run_endpoint_function(
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/fastapi/routing.py", line 137, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/barnaby/.local/share/virtualenvs/fastapi-example-6xjq_vv2/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./sql_app/main.py", line 51, in read_notes
    "title": title,
NameError: name 'title' is not defined
```

**Comment by Mause** [comment]
Yes, you still need to fix your other code!

**Comment by Barnez299** [comment]
You need to be more specific please.

**Comment by ycd** [comment]
In `/sql_app/main.py` you haven't declared a variable called `title`.

**Comment by Barnez299** [comment]
@ycd  where exactly...sorry guys an new at this...the endpoints are working fine using swagger/docs. however I am not able to render it via the ("/'') using render template....

**Comment by Mause** [comment]
On line 51 of main.py

**Comment by ycd** [comment]
You are returning a few variables but, you haven't declared any of them yet. Either use notes and return it (If it still fails please show us the error).

```python
notes = crud.get_notes(db=db, skip=skip, limit=limit)
    print(notes)
    return templates.TemplateResponse("index.html",{
        "request": request,
        "id": id,
        "title": title,
        "description": description
    })
```

I think you need the return `notes.id, notes.title, notes.description` here.

**Comment by Barnez299** [comment]
Hey guys - its working now: Fixed the following code as follows:

```
@app.get("/", response_class=HTMLResponse)
def read_notes(request: Request, skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    notes = crud.get_notes(db=db, skip=skip, limit=limit)
    return templates.TemplateResponse("index.html", {
        "request": request,
        "notes": notes,
    })
```

Also had for loop incorrect in index.html - fixed accordingly
```
{% extends 'layout.html' %} {% include 'header.html' %} {% block title %} Home {% endblock %} {% block body %}

<div class="container">
    <div class="row">
        <div class="col md-12">

            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {%for note in notes%}
                    <tr>
                        <td>{{note.id}}</td>
                        <td>{{note.title}}</td>
                        <td>{{note.description}}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}
```
Everything working well. Thank you for your response and guidance. This issue can be closed.

**Comment by Mause** [comment]
If your issue is solved please close the issue yourself

**Comment by Barnez299** [comment]
Yep solved. Thank you

**Comment by tiangolo** [comment]
Thanks for the help here @Mause and @ycd ! :clap: :bow: 

Thanks for reporting back and closing the issue @Barnez299  :+1:
