### ISSUE TITLE
ModuleNotFoundError: No module named 'app' using uvicorn, fastapi

### ISSUE THREAD

**Issue by darkl1ght** [tiangolo/fastapi#2582]
I am getting ModuleNotFoundError: No module named 'app' error. 

Below (image) is almost everything you need to know about the issue. There have been other similar issues about this, but most of them were related to docker. I am not using docker and don't know much about it. 

This is a common problem I have observed. Any help is appreciated.

![image](https://user-images.githubusercontent.com/19537472/103345380-43afd700-4ab7-11eb-9729-0c8c0b558403.png)

Complete Error
```
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/xxxxx/geoprocessing-api/.venv/lib/python3.6/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/xxxxx/geoprocessing-api/.venv/lib/python3.6/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/xxxxxx/geoprocessing-api/.venv/lib/python3.6/site-packages/uvicorn/server.py", line 55, in serve
    config.load()
  File "/xxxxxxx/geoprocessing-api/.venv/lib/python3.6/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/xxxxx/geoprocessing-api/.venv/lib/python3.6/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/xxxxx/geoprocessing-api/.venv/lib/python3.6/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/xxxxxxxxx/geoprocessing-api/app/server/app.py", line 2, in <module>
    from app.server.routes.config_route import router as ConfigRouter
ModuleNotFoundError: No module named 'app'
```

Please let me know if you need anything else.
Thanks.

**Comment by Mause** [comment]
Try
````python
from .server.routes.config_route import router as ConfigRouter
```
instead

**Comment by darkl1ght** [comment]
Hi @Mause,

If I do that, I get a new error.
![image](https://user-images.githubusercontent.com/19537472/103353928-263b3700-4ad0-11eb-9b0e-e9119857c69b.png)
and if I use
```
 from .routes.config_route import router as ConfigRouter
```
The error for that file gets removed, but I get a new error in another file.
![image](https://user-images.githubusercontent.com/19537472/103354053-8a5dfb00-4ad0-11eb-9713-710b2c62bef3.png)

I cannot keep on changing the import structure everywhere. There has to be some other fix I guess.

Btw, ignore the fact that I am using the same project in Windows as well as Linux, but I am getting similar errors in both.

Thanks

**Comment by Mause** [comment]
Then you have to fix the new error, in a similar way

**Comment by darkl1ght** [comment]
Thanks, @Mause.

I did what you have told me. But I don't know if that is the fix to this issue. In Windows, there is a different modification, while in Linux there are different modifications to be made. I mean is there is folder structure different from what I am following? that can be used, or is documented somewhere(apart from [this)](https://fastapi.tiangolo.com/tutorial/bigger-applications/).

Thanks for the help though.

**Comment by shawnwall** [comment]
Please take a look at some documentation regarding [absolute vs relative imports in python](https://realpython.com/absolute-vs-relative-python-imports/). The imports should work the same between windows or *nix.

**Comment by darkl1ght** [comment]
@shawnwall, @Mause Thanks for the suggestions.

I found the reason for it. My PYTHONPATH environment variable was not set.

To set it, you can run the below command in the base directory of your project:

```bash
$ export PYTHONPATH=$PWD
```

This fixed my issue and I was able to use the imports along with the app.server.x.x.

Thanks for your insights though.

**Comment by scheung38** [comment]
@darkl1ght I tried in base

$ export PYTHONPATH=$PWD

then cd src

(.venv) ➜  src git:(master) ✗ uvicorn main:app --reload


 File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/mincheung/Documents/file_processing_pipeline/src/./main.py", line 2, in <module>
    import pandera as pa
ModuleNotFoundError: No module named 'pandera'

**Comment by oktep** [comment]
I had same error this helped:
https://stackoverflow.com/questions/68505216/modulenotfounderror-no-module-named-app-routes
Run the app from root directory: `uvicorn app.server.app:app -- reload` 
instead of  ...app/server > `uvicorn app:app`

**Comment by iffyaiyan** [comment]
Windows users they can write,

set PYTHONPATH=$PWD

**Comment by KapeParaguay** [comment]
Intenta dandole a guardar archivo antes de ejecutar.
