### ISSUE TITLE
KeyError when generating openapi when using subclasses as field types

### ISSUE THREAD

**Issue by mclate** [tiangolo/fastapi#2724]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

```pythonfrom fastapi import FastAPI

from pydantic import BaseModel

app = FastAPI(title="issue api", version='0.1.0')


class A:
    class Model(BaseModel):
        a: str


class B:
    class Model(BaseModel):
        b: str


class Response(BaseModel):
    a: A.Model
    b: B.Model


@app.get('/', response_model=Response)
def get():
    ...
```

```
INFO:     127.0.0.1:57149 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File ".venv/lib/python3.9/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File ".venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File ".venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File ".venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File ".venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File ".venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File ".venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File ".venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File ".venv/lib/python3.9/site-packages/fastapi/applications.py", line 132, in openapi
    return JSONResponse(self.openapi())
  File ".venv/lib/python3.9/site-packages/fastapi/applications.py", line 110, in openapi
    self.openapi_schema = get_openapi(
  File ".venv/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 343, in get_openapi
    definitions = get_model_definitions(
  File ".venv/lib/python3.9/site-packages/fastapi/utils.py", line 28, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'script.B.Model'>
```

### Description

Looks like when openapi is generated, it doesn't play well with models defined in subclasses within the classes. Code above will work if replaced like this:
```python
class ModelA(BaseModel):
    a: str


class A:
    Model = ModelA


class ModelB(BaseModel):
    b: str


class B:
    Model = ModelB


class Response(BaseModel):
    a: A.Model
    b: B.Model
```

I feel like the issue might be in `schema.py:normalize_name`
    
### Environment

* OS: [e.g. Linux / Windows / macOS]: MacOS 10.15.7
* FastAPI Version [e.g. 0.3.0]:  fastapi==0.61.2
* Python version: Python 3.9.1

**Comment by mclate** [comment]
Notice, that this code also works:
```python

class A:
    class Model(BaseModel):
        a: str


class B:
    class Model(BaseModel):
        b: str


class Response(BaseModel):
    a: A.Model
    # b: B.Model  # Commented, so there is only one field with subclass
    c: int
```

**Comment by tiangolo** [comment]
Humm, I don't think you are supposed to use Pydantic like that, I don't think that's supported.

As it's a non-standard way to declare Pydantic models, it wouldn't be expected or supported by FastAPI, sorry. 😬 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
