### ISSUE TITLE
ImportError: cannot import name Deque

### ISSUE THREAD

**Issue by kkruzich** [tiangolo/fastapi#2732]
### First check

* [ x] I added a very descriptive title to this issue.
* [ x] I used the GitHub search to find a similar issue and didn't find it.
* [ x] I searched the FastAPI documentation, with the integrated search.
* [ x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [ x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [ x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [ x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [ x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [ x] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

Here's a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

```Python
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}
```

### Description

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Optional
>>> from fastapi import FastAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/routing.py", line 18, in <module>
    from fastapi import params
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 4, in init pydantic.dataclasses
    import types
  File "pydantic/error_wrappers.py", line 4, in init pydantic.error_wrappers
  File "pydantic/json.py", line 12, in init pydantic.json
  File "pydantic/types.py", line 28, in init pydantic.types
    yield
  File "pydantic/validators.py", line 9, in init pydantic.validators
ImportError: cannot import name Deque
```

### Environment

* OS: macOS 10.15.3 

To know the FastAPI version use:

```
python3 -c "import fastapi; print(fastapi.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/routing.py", line 18, in <module>
    from fastapi import params
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 4, in init pydantic.dataclasses
    import types
  File "pydantic/error_wrappers.py", line 4, in init pydantic.error_wrappers
  File "pydantic/json.py", line 12, in init pydantic.json
  File "pydantic/types.py", line 28, in init pydantic.types
    yield
  File "pydantic/validators.py", line 9, in init pydantic.validators
ImportError: cannot import name Deque
```

* Python version:

```python3 --version
Python 3.6.0
```

**Comment by ycd** [comment]
Well it is backported twice for 3.5.4 and 3.6.0 (see [issue #29481](https://bugs.python.org/issue29481)). 

So you are probably using older version of 3.6.0. Best thing you can do is installing a newer version of Python.

**Comment by hukkinj1** [comment]
It seems to me like `typing.Deque` was added in Python 3.6.1 (source: https://docs.python.org/3/library/typing.html#typing.Deque).

So FastAPI and Pydantic both seem to require Python >=3.6.1

**Comment by tiangolo** [comment]
Thanks for the report @kkruzich! :nerd_face: 

Thanks for the investigation @ycd! :detective: 

And thanks @hukkin for the PR updating the metadata! :man_scientist: 

---

Yep, you should probably update the Python version to 3.6.1 at least. Have in mind that 3.6 reaches the end of life in December, by then you should hopefully have upgraded to at least Python 3.7.
