### ISSUE TITLE
Error "AdminShutdown": get db session in background celery task

### ISSUE THREAD

**Issue by elsimqoz** [tiangolo/fastapi#2745]
Small api service with background task which use db session:
`main.py`
```Python
import celery
from fastapi import FastAPI
from sqlalchemy import Column, Integer, create_engine
from sqlalchemy.ext.declarative import as_declarative
from sqlalchemy.orm import sessionmaker

### model

@as_declarative()
class Model:
    pass

class Entity(Model):
    __tablename__ = 'entity'

    id = Column(Integer, primary_key=True, index=True)

### connection

main_engine = create_engine('postgresql://postgres:@127.0.0.1:5432/test', pool_pre_ping=True)
MainSession = sessionmaker(autocommit=False, autoflush=False, bind=main_engine)

def get_main_db():
    db = MainSession()
    try:
        yield db
    finally:
        db.close()

### celery

celery_ = celery.Celery('tasks', broker='redis://127.0.0.1:6379/1')
celery_.conf.update(task_always_eager=True)

@celery_.task
def background_task():
    session = next(get_main_db())
    session.add(obj := Entity())
    session.commit()
    print(obj.id)

### app

app = FastAPI()

@app.get('/')
def read_root():
    result = {'Hello': 'World'}
    background_task.delay()
    return result
```

There is a simple test:
`test.py`
```Python

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy_utils import create_database, database_exists, drop_database

from main import app, Model


@pytest.fixture(scope='session')
def web_client():
    return TestClient(app=app)


@pytest.fixture(scope='session')
def main_db_uri():
    return 'postgresql://postgres:@127.0.0.1:5432/test'


@pytest.fixture(scope='session')
def main_engine(main_db_uri):
    return create_engine(main_db_uri, client_encoding='utf8', connect_args={'client_encoding': 'utf8'})


@pytest.fixture(scope='session', autouse=True)
def database(main_engine, main_db_uri):
    if database_exists(main_db_uri):
        drop_database(main_db_uri)

    create_database(main_db_uri)
    Model.metadata.create_all(bind=main_engine)

    yield

    drop_database(main_db_uri)


def test_get(web_client):
    assert web_client.get('/').status_code == 200
```

Run pytest:
```
Test session starts (platform: linux, Python 3.8.5, pytest 6.2.2, pytest-sugar 0.9.4)
rootdir: /home/test/test_2, configfile: pyproject.toml, testpaths: tests
plugins: sugar-0.9.4
collecting ... 1

 tests/test_.py ✓                                                                     100% ██████████

Results (0.54s):
       1 passed
Exception during reset or similar
Traceback (most recent call last):
  File "/home/test/test_2/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/test/test_2/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/test/test_2/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```
So, the test is has passed successful, but there is the psycopg2 error.
Is the way for get db session wrong?  What is the reason that server closed the connection unexpectedly?
```
Python 3.8.5
celery==5.0.5
fastapi==0.63.0
psycopg2-binary==2.8.6
pydantic==1.7.3
pytest==6.2.2
redis==3.5.3
requests==2.25.1
SQLAlchemy==1.3.23
SQLAlchemy-Utils==0.36.8
starlette==0.13.6
uvicorn==0.13.3
uvloop==0.14.0
```

**Comment by tuukkamustonen** [comment]
You're mixing quite a few things here (Postgres, Redis, SQLAlchemy, Celery). Can you negate away unnecessary bits and pieces from it, ie. try without Redis/Celery, even without SQLAlchemy?

The error you're seeing would indeed indicate that the server side closed the connection, not your application.

I would say your test works, because the endpoint returns before the background task completes. And when the background task completes (or fails), the error is thrown, maybe because DB connection is no longer available in the context.

**Comment by tiangolo** [comment]
Thanks for the help here @tuukkamustonen ! 👏  🙇 

It seems your error is on Celery, right @elsimqoz? In that case that wouldn't really be FastAPI.

Also, you should probably put the Celery worker stuff in a different file and run that independently of your FastAPI app.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
