### ISSUE TITLE
Websockets and SQLAlchemy events

### ISSUE THREAD

**Issue by adriangabura** [tiangolo/fastapi#2764]
### First check

* [*] I added a very descriptive title to this issue.
* [*] I used the GitHub search to find a similar issue and didn't find it.
* [*] I searched the FastAPI documentation, with the integrated search.
* [*] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [*] I already read and followed all the tutorial in the docs and didn't find an answer.
* [*] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [*] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [*] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

I can't find a way to integrate SQLAlchemy Events into FastAPI Websockets. The issue is I can't trigger a websocket.send_text() from the SQLAlchemy event handler because this is an asynchronous function. I can't await it in:

`from sqlalchemy import event
from fastapi import APIRouter

router = APIRouter(tags=["clients"])

@router.websocket("/ws/clients")
async def websocket_endpoint(websocket: WebSocket, db: Session = Depends(get_db)):
     async def query_and_send():
         initial_query = read.all_clients(db)
         await websocket.send_text(jsonify_query(pydantic_models.Client, initial_query))

    loop = asyncio.get_event_loop()

    @event.listens_for
     def my_event(*args, **kwargs):

         #can't do that!
         await websocket.send_text("ok")

         #tried that too 
         loop.create_task(query_and_send())
` 

I tried to do a asyncio.get_event_loop() and then do loop.create_task(myfunction()) with a separate handler async function for sending but I get errors:

`Traceback (most recent call last):
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/run/media/alpha1138/IDE/projects/cms/app/routers/clients.py", line 55, in create_client
    return create.client(db=db, client_model=client_model)
  File "/run/media/alpha1138/IDE/projects/cms/app/crud/create.py", line 56, in client
    db.commit()
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib64/python3.9/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/run/media/alpha1138/IDE/projects/cms/app/routers/clients.py", line 85, in update_listener
    loop.create_task(query_and_send())
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 748, in call_soon
    self._check_thread()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 785, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/run/media/alpha1138/IDE/projects/cms/app/routers/clients.py", line 55, in create_client
    return create.client(db=db, client_model=client_model)
  File "/run/media/alpha1138/IDE/projects/cms/app/crud/create.py", line 56, in client
    db.commit()
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib64/python3.9/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/run/media/alpha1138/IDE/projects/cms/app/routers/clients.py", line 85, in update_listener
    loop.create_task(query_and_send())
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
task: <Task pending name='Task-13' coro=<websocket_endpoint.<locals>.query_and_send() running at /run/media/alpha1138/IDE/projects/cms/app/routers/clients.py:93> created at /usr/lib64/python3.9/asyncio/base_events.py:433>
/home/alpha1138/.local/share/virtualenvs/cms-5rfnMskL/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py:403: RuntimeWarning: coroutine 'websocket_endpoint.<locals>.query_and_send' was never awaited
  self.transport.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
`

I need to be able to send back to the client updated database query results whenever the is a database update. And I can't seem to able to do that.

I was able to create a script that does a while True loop that checks a value set when the @event.listens_for function changes and when it does it triggers the query_and_send() function. That does work. But when I close the server, it never shuts down because the background task never shuts, and it gets stuck.

**Comment by ycd** [comment]
Can you please create a minimal reproducible example?

**Comment by stevenj** [comment]
@adriangabura What you are experiencing is the chasm between async and sync, but its worse than what you are considering with websockets. Unless you have everything running in the same process, your websocket may be being handled by a different process to the sync event you are processing.  What i did is this.
Created a UDP Socket listening on a known port.  I then post to my database that this particular process/ip is managing this websocket.  When i want to send the websocket a message from anywhere else, i just send a UDP datagram to that ip and it gets picked up by an async task which is running in the same process as the websocket.  Because they are both async and guaranteed to be in the same process, the UDP handler can then send the message out the websocket.  Its a simple form of IPC.  It scales and it eliminates all problems with crossing the async/sync divide or finding where a particular websocket is being managed.  I do a similar thing when i process Websocket requests.  Because my websockets stay open for days at a time and are connected to thousands of devices.  I do not want a persistent DB connection to each websocket.  And OpenAPI doesn't handle AsynchAPI documentation anyway.  So what i do in that case, is every websocket request gets internally converted into a rest request which i then call internally using a unix socket (because they are faster than ip sockets).  That means that all the websocket messaging is being processed exactly the same as the rest api.  The websocket handler is just forwarding the request on internally and returning the response it gets over the websocket.

**Comment by tiangolo** [comment]
Thanks for the help here @ycd and @stevenj ! 👏  🙇 

If you are still having issues @adriangabura, please create a minimal, self-contained example to reproduce the problem/use case.

I suspect for your use case the best might be to have an intermediate Redis that takes the thing form the SQLAlchemy event, and then the WebSocket handling code would be listening to that Redis waiting for that info to send it back. This would also help you avoid depending on having a single process to handle everything and would allow you to more easily scale horizontally.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
