### ISSUE TITLE
TypeError: Object of type '_GenericAlias' is not JSON serializable

### ISSUE THREAD

**Issue by alexferrari88** [tiangolo/fastapi#2785]
Here's a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

```Python
from fastapi import FastAPI
from typing import List
from pydantic import BaseModel
import uvicorn

app = FastAPI()

class Item(BaseModel):
    name: str
    logo: str
    description: str

@app.get('/')
def index():
    return {"message": "OK"}

@app.get('/test')
def testing(q: str, response_model=List[Item]):
    return [{'name': 'name', 'logo': 'logo.png', 'description': 'desc'}]
```

### Description

* Open the browser and call the docs `127.0.0.1/docs`.
* Receives the error `Internal Server Error /openapi.json`.
* In the terminal I get `TypeError: Object of type '_GenericAlias' is not JSON serializable` (full log below).

### Environment

* OS: Windows 10:
* FastAPI Version [e.g. 0.3.0]: 0.63.0
* Python version: 3.9.1

### Additional context

```bash
Traceback (most recent call last):
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\fastapi\applications.py", line 152, in openapi
    return JSONResponse(self.openapi())
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\fastapi\applications.py", line 130, in openapi
    self.openapi_schema = get_openapi(
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\fastapi\openapi\utils.py", line 359, in get_openapi
    result = get_openapi_path(route=route, model_name_map=model_name_map)
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\fastapi\openapi\utils.py", line 185, in get_openapi_path
    operation_parameters = get_openapi_operation_parameters(
  File "c:\users\nl112afe\onedrive\python\rtldr\env\lib\site-packages\fastapi\openapi\utils.py", line 98, in get_openapi_operation_parameters
    "schema": field_schema(
  File "pydantic\schema.py", line 215, in pydantic.schema.field_schema
  File "pydantic\schema.py", line 183, in pydantic.schema.get_field_info_schema
  File "pydantic\schema.py", line 848, in pydantic.schema.encode_default
  File "pydantic\json.py", line 65, in pydantic.json.pydantic_encoder
TypeError: Object of type '_GenericAlias' is not JSON serializable
```

**Comment by alexferrari88** [comment]
Even though there are two (closed) bugs with this error, the context looks different. Please let me know if I should remove this one and post my issue in those bugs.

**Comment by alexferrari88** [comment]
found the error.
the response_model parameter should be here `@app.get('/test', response_model=List[Item])` instead of putting it in the function definition!
