### ISSUE TITLE
  Exception in ASGI application

### ISSUE THREAD

**Issue by Adesoji1** [tiangolo/fastapi#2856]
Traceback (most recent call last):
  File "c:\users\sortol\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\sortol\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\sortol\anaconda3\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\users\sortol\anaconda3\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\users\sortol\anaconda3\lib\site-packages\fastapi\routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "c:\users\sortol\anaconda3\lib\site-packages\fastapi\routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File ".\main.py", line 21, in predict_image
    predictions = predict(flower_img)
  File ".\helpers.py", line 42, in predict
    response = requests.post(URL, data=data, headers=headers)
  File "c:\users\sortol\anaconda3\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\users\sortol\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\sortol\anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\sortol\anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\sortol\anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/flower-classification:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024818853520>: Failed to establish a new connection: [WinError 10061] No connection 
could be made because the target machine actively refused it'))

**Comment by ycd** [comment]
Can you follow the issue template?

**Comment by aalifadv** [comment]
Hi @Adesoji1  

I second the folks that you really should use the issue template so we can help you better.

please notice that your exception is caused by this line:

`response = requests.post(URL, data=data, headers=headers)`

The error message that is interesting is this:

> No connection could be made because the target machine actively refused it
which suggests that whatever URL you are trying to request in that line of code is refusing the connection. 

and that gets me to wonder, why do you think this is a FastAPI issue? :broken_heart:

**Comment by Adesoji1** [comment]
ok,it's not a FASTAPI issue

**Comment by tiangolo** [comment]
Thanks for the help here @ycd  and @aalifadv ! 👏  🙇 

Thanks for reporting back and closing the issue @Adesoji1  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
