### ISSUE TITLE
Exception in ASGI application: Starlette background job error?

### ISSUE THREAD

**Issue by vss96** [tiangolo/fastapi#2912]
### Example

Here's a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

```Python
from fastapi import APIRouter, BackgroundTasks
router = APIRouter()

def start_frame_ingestion(videoUrl: str):
# Downloads a video and calls an API by passing individual frames of the video

@router.post("/video/ingest", tags=['media-ingestion-adapter'], response_model=str)
async def ingest_video(videoUrl: str, backgroundTasks: BackgroundTasks) -> str:
    """
    @param videoUrl: One of many url types. Http for sure. S3 if configured.
    @param backgroundTasks: This param is created by fastapi to handle background tasks
    @return: OK
    """
    backgroundTasks.add_task(start_frame_ingestion, videoUrl)
    return "OK"
```

### Description

* I call the API and the background job starts to split the downloaded video into frames and starts calling another API.
* After a while, the server crashes with "Exception in ASGI application"
* Traceback : 
``` 2021-03-08 08:51:28,427 loglevel=ERROR  logger=uvicorn.error run_asgi() L388  Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 142, in __call__
    await self.background()
  File "/usr/local/lib/python3.8/site-packages/starlette/background.py", line 35, in __call__
    await task()
  File "/usr/local/lib/python3.8/site-packages/starlette/background.py", line 20, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/app/core/routes/media_ingestion_adapter.py", line 53, in start_frame_ingestion
    frames.Frames(capture, fileName, mediaId).splitVideo(config, numberOfFrames)
  File "/app/app/core/services/frames.py", line 35, in splitVideo
    darwinIngestion.ingest(frame, token)
  File "/app/app/core/services/darwin_ingestion.py", line 62, in ingest
    self.media_storage_service.save_video_frame(self.mediaId, self.frameNo, content)
  File "/app/app/core/clients/media_storage_service_client.py", line 36, in save_video_frame
    raise Exception(response.text)
Exception: Internal Server Error
```

### Environment

* OS: [e.g. Linux / Windows / macOS]: Linux Ubuntu
* FastAPI Version [e.g. 0.3.0]: 0.62.0
* Python version: 3.8.2

### Additional context

I'm using the docker image suggested for prod, my dockerfile looks something like this: 
``` FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

COPY ./app /app/app

COPY ./requirements.txt /app

WORKDIR /app

RUN pip install -r requirements.txt
RUN apt-get update
RUN apt-get install -y libgl1-mesa-dev

EXPOSE 80
```

**Comment by Mause** [comment]
Looks like there's an error occurring when you try to store the video? It doesn't look related to FastAPI

**Comment by tiangolo** [comment]
Thanks for the help here @Mause ! 👏  🙇 

Thanks for coming back and closing the issue @vss96  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
