### ISSUE TITLE
AuthenticationMiddleware must be installed to access request.user

### ISSUE THREAD

**Issue by guillain** [tiangolo/fastapi#3043]
Hello,

I try to setup a middleware to record all request parameters to a json doc.
I've success to do all things instead to get the **request.user.username** information coming from the Request because it requires to install **AuthenticationMiddleware**.

Please can you support me to setup that properly?

**Code**
```
@app.middleware("http")
async def http_tracking(request: Request, call_next):
    response = await call_next(request)
    trace = {
        "request": {
            "type": request['type'],
            "asgi": request['asgi'],
            "server": request['server'],
            "client": request['client'],
            "scheme": request['scheme'],
            "method": request['method'],
            "path": request['path'],
            "path_params": request['path_params'] if 'path_params' in request else {},
            "user": request.user.username
        },
        "response": {
            "headers": dict(response.headers)
        }
    }
    # Trace record fct

    return response
```

**Error log**
```
2021-04-05 00:21:07 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\fastapi\applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "D:/documents/GitLab/bo-art-of-bonsai/blocker/app/main.py", line 57, in http_tracking
    print(request.user.username)
  File "D:\documents\GitLab\bo-art-of-bonsai\venv\lib\site-packages\starlette\requests.py", line 148, in user
    ), "AuthenticationMiddleware must be installed to access request.user"
AssertionError: AuthenticationMiddleware must be installed to access request.user
```

Thanks in advance, take care! and have a great day :D

**Comment by Kludex** [comment]
Look like it wants this: https://www.starlette.io/authentication/ ?

**Comment by iashraful** [comment]
In my case, I was using JWT Bearer authentication. So, I also couldn't call `request.user` where necessary. I did apply the Authentication middleware. Hope this will help.

### Writing your own authentication backend
> This class is written based on my application structure and needs. You may need this to fit for your application
```python
# Authentication Backend Class
class BearerTokenAuthBackend(AuthenticationBackend):
    """
    This is a custom auth backend class that will allow you to authenticate your request and return auth and user as
    a tuple
    """
    async def authenticate(self, request):
        # This function is inherited from the base class and called by some other class
        if "Authorization" not in request.headers:
            return

        auth = request.headers["Authorization"]
        try:
            scheme, token = auth.split()
            if scheme.lower() != 'bearer':
                return
            decoded = jwt.decode(
                token,
                settings.JWT_SECRET,
                algorithms=[settings.JWT_ALGORITHM],
                options={"verify_aud": False},
            )
        except (ValueError, UnicodeDecodeError, JWTError) as exc:
            raise AuthenticationError('Invalid JWT Token.')

        username: str = decoded.get("sub")
        token_data = TokenData(username=username)
        # This is little hack rather making a generator function for get_db
        db = LocalSession()
        user = User.objects(db).filter(User.id == token_data.username).first()
        # We must close the connection
        db.close()
        if user is None:
            raise AuthenticationError('Invalid JWT Token.')
        return auth, user

```

### Add the middleware on the main file (In my case it's `main.py`)
```python

@app.on_event('startup')
async def startup():
    app.add_middleware(AuthenticationMiddleware, backend=BearerTokenAuthBackend())

```

**Comment by mlbase** [comment]
@iashraful Hi I also apply starlette authentication middleware and it works properly. Anyway how did you get authorization header in swagger-ui?, Using `Oauth2PasswordBearer` parameter with starlette `AuthenticationMiddleware` decodes jwt twice. Do you know about any good methods?

**Comment by iashraful** [comment]
Sorry didn't try it. I'll let you know if I get time for a try :)

**Comment by mlbase** [comment]
@iashraful Sorry I misunderstand about `Oauth2PasswordBearer` . I debugged repeatedly with `Oauth2PasswordBearer`, it seems like only inspect about its authorization header type is `bearer`.
