### ISSUE TITLE
Using custom Middleware with WebSocket

### ISSUE THREAD

**Issue by shaihulud** [tiangolo/fastapi#3054]
Hello,
I'm using [this example](https://fastapi.tiangolo.com/advanced/websockets/) from the docs, open 2 tabs in my browser and everything work just fine - I can send and recieve text in each tab.

### Example
Than I add a simple middleware:

```Python
class TestMiddleware:

    def __init__(self, app) -> None:
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] not in ("http", "websocket"):
            await self.app(scope, receive, send)
            return

        self.send = send
        self.receive = receive
        await self.app(scope, self.proxy_receive, self.proxy_send)

    async def proxy_receive(self):
        message = await self.receive()
        return message

    async def proxy_send(self, message):
        await self.send(message)


app.add_middleware(TestMiddleware)
```

just before ```@app.get("/")```
And now if I will open 2 tabs in my browser the 2d will work fine, but if I'll try to send smth in the 1st tab, I'll get

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 162, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "./main.py", line 53, in __call__
    await self.app(scope, self.proxy_receive, self.proxy_send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/fastapi/routing.py", line 247, in app
    await dependant.call(**values)
  File "./main.py", line 77, in websocket_endpoint
    data = await websocket.receive_text()
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/websockets.py", line 84, in receive_text
    message = await self.receive()
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/starlette/websockets.py", line 40, in receive
    message = await self._receive()
  File "./main.py", line 56, in proxy_receive
    message = await self.receive()
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 249, in asgi_receive
    data = await self.recv()
  File "/Users/u18802056/proj/fastapi-test/venv/lib/python3.8/site-packages/websockets/protocol.py", line 473, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message
```

### Environment

* OS: macOS
* fastapi==0.63.0
* pydantic==1.8.1
* starlette==0.13.6
* uvicorn==0.13.4
* websockets==8.1
* Python 3.8.2

**Comment by cheesycod** [comment]
I would like this too
