### ISSUE TITLE
ImportError: cannot import name 'get_query_token' from 'app.dependencies'

### ISSUE THREAD

**Issue by ghost** [tiangolo/fastapi#3074]
Hello fastapi community,
I am new to fastapi and following the tutorial --> `https://fastapi.tiangolo.com/tutorial/bigger-applications/`
I was able to come so far without having any errors :))

However,
I have came across an interesting case where I was not able to explain myself so 
I wanted to share and maybe can get an answer that makes sense to me :)

### dependencies.py
```Python
from fastapi import Header, HTTPException

async def get_token_header(x_token: str = Header(...)):
    if x_token != "fake-super-secret-token":
        raise HTTPException(status_code=400, detail="X-Token header invalide!!")

async def get_query_token(token: str):
    if token != "jessica":
        raise HTTPException(status_code=400, detail="No jessica token provider!!")
```

### main.py
As described in fastapi documantation I import `get_token_header` and `get_query_token`
```Python
from fastapi import Depends, FastAPI
from .internal import admin
from .routers import items, users
from .dependencies import get_query_token, get_token_header

app1 = FastAPI(dependencies=[Depends(get_query_token)])

app1.include_router(users.router)
app1.include_router(items.router)
app1.include_router(
    admin.router,
    prefix="/admin",
    tags=["admin"],
    dependencies=[Depends(get_token_header)],
    responses={418: {"description": "I'm a teapot"}},
)

@app1.get("/")
async def root():
    return {"message": "Hello Bigger Applications!"}

```

### Description
* Rest of the files are exactly the same as in the documentation described at 
`https://fastapi.tiangolo.com/tutorial/bigger-applications/`

* Running application as 
```bash
uvicorn app.main:app1 --reload
```
* I get the following `ImportError`
```bash
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [73991] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tuncovacik/.local/share/virtualenvs/prj_bigapp-yhA7Uojr/lib/python3.9/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/Users/tuncovacik/.local/share/virtualenvs/prj_bigapp-yhA7Uojr/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/tuncovacik/.local/share/virtualenvs/prj_bigapp-yhA7Uojr/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/Users/tuncovacik/.local/share/virtualenvs/prj_bigapp-yhA7Uojr/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/tuncovacik/.local/share/virtualenvs/prj_bigapp-yhA7Uojr/lib/python3.9/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/Users/tuncovacik/.local/share/virtualenvs/prj_bigapp-yhA7Uojr/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./app/main.py", line 4, in <module>
    from .dependencies import get_query_token, get_token_header
ImportError: cannot import name 'get_query_token' from 'app.dependencies' (./app/dependencies.py)
```

* Now at this point I was confused because `ImportError` implicitly mentions functions'  **_correct path_**
* My solution was to re-name the functions as follow: `getquerytoken` and `gettokenheader`
* After doing so my application run as expected. I was able to access **_docs_** and **_redoc_** interfaces

* Is there a naming convention or something that I am missing? 
* I am also confused because at **`https://fastapi.tiangolo.com/tutorial/bigger-applications/`** 
Functions names is still have underscore in their names. Is it supposed to run in this way as well?

### Environment

* OS: `macOS `
* FastAPI Version : `0.63.0`
* Python version: `3.9`

### Additional context
Note: I am sorry If it sounds kind a dumb or not related to fastapi.

**Comment by sarzz2** [comment]
I believe get_query_token is an internal module in fastapi  and that's why it might be conflicting.

**Comment by panicattacks** [comment]
I have re-created my environment from scratch and It worked as It was in the docs.

**Comment by tiangolo** [comment]
Thanks for the help here @sarzz2 ! 👏  🙇 

Thanks Mr. ghost for reporting back and closing the issue (before deleting your GitHub account 😅 ) 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
