### ISSUE TITLE
Show the Pydantic response structure in the doc page with Swagger

### ISSUE THREAD

**Issue by nrshapiro** [tiangolo/fastapi#319]
**Description**

FastAPI doc does not show structure of response (I'm using Pydantic). 

I am working on porting an API to FastAPI.  I have FastAPI and pydantic working nicely on my system.  I import my pydantic models in a file called models.py, if that makes a difference, they're not directly in main.  I like this organization.  Much of the work for the endpoints themselves are done in a library file I call opasAPISupportLib.py which needs those too.  In the main file, I don't need to do a lot for an endpoint, here's one:

I have finshed three endpoints and they don't show the response structure in the doc page with either the Swagger based doc or ReDoc.
```
 @app.get("/v1/Authors/Index/{authorNamePartial}/")
 def getAuthorsIndex(authorNamePartial: str, request: Request, limit: int = 15, offset: int = 0):
    """
    ## /v1/Authors/Index/{authorNamePartial}/
    ## Function
    Return a list (index) of authors.  The list shows the author IDs, which are a normalized form of an authors name.
    ## Return Type
    authorindex
    ## Status
    This endpoint is working.
    ## Sample Call
       http://localhost:8000/v1/Authors/Index/Tuck/

    """
    retVal = opasAPISupportLib.authorsGetAuthorInfo(authorNamePartial, limit=limit, offset=offset)

    # fill in additional return structure status info
    client_host = request.client.host
    retVal.authorIndex.responseInfo.request = request.url._url

    return retVal
```

Here's the relevant models for this endpoint from models.py:
```
class ResponseInfo(BaseModel):
    count: int = 0
    limit: int = None
    offset: int = None
    fullCount: int = None
    fullCountComplete: bool = None
    listLabel: str = None
    listType: ListTypeEnum = None
    scopeQuery: str = None
    request: str = None
    timeStamp: str = None

class AuthorIndexStruct(BaseModel):
    responseInfo: ResponseInfo(listType="authorindex") 
    responseSet: List[AuthorIndexItem] = []

class AuthorIndex(BaseModel):
    authorIndex: AuthorIndexStruct
```
I expected to see a sample json structure in the Responses 200 area.  Nowhere in the doc as generated in either docs generator does it show the json return structure for API users.  I would have expected to see something like this;
```
responses 
200
        {
            "authorindex": {
              "responseInfo": {
                "count": int,
                "fullCount": int,
                "fullCountComplete": bool,
                "listLabel": "string",
                "listType": "string",
                "scopeQuery": "string",
                "request": "string",
                "timeStamp": "string"
              },
              "responseSet": [
                {
                  "authorID": "string",
                  "publicationsURL": "string"
                }
              ]
            }
         }
    
```

**Additional context**
I've seen online examples which also have blank areas for responses, for code 200.  Shouldn't it show the response model somewhere?

**Comment by stefanondisponibile** [comment]
You have to declare it in the decorator:

```
@app.get("/v1/Authors/Index/{authorNamePartial}/", response_model=ResponseInfo)
def getAuthorsIndex():
    ...    
```

**Comment by nrshapiro** [comment]
Thanks...I missed that!  And that "sort of" works.  But that's not really the response_model.  The real response model is:
```
@app.get("/v1/Authors/Index/{authorNamePartial}/", response_model=models.AuthorIndex)
```
But specifying that gives:
```
Failed to load API definition.
Errors
Hide
 
Fetch errorInternal Server Error /openapi.json
```
The decorator you specified works, but it's not the whole response, ResponseInfo is a substructure (see the model in my post).  The hierarchy is:

AuthorIndex => AuthorIndexStruct => {ResponseInfo, List[AuthorIndexItem] = []}

and ResponseInfo is just the information header, and the real data is in List[AuthorIndexItem]

An example return json response is this:
```
{
	"authorIndex": {
		"responseInfo": {
			"count": 7,
			"limit": 15,
			"offset": 0,
			"fullCount": 72,
			"fullCountComplete": false,
			"listLabel": null,
			"listType": "authorindex",
			"scopeQuery": null,
			"request": "http://127.0.0.1:8000/v1/Authors/Index/Tuck/",
			"timeStamp": "2019-06-17T19:06:17Z"
		},
		"responseSet": [
			{
				"authorID": "Tuckett, David",
				"publicationsURL": "",
				"publicationsCount": 60
			},
			{
				"authorID": "Tucker, Sara S.",
				"publicationsURL": "",
				"publicationsCount": 7
			},
			{
				"authorID": "Tucker, Landrum",
				"publicationsURL": "",
				"publicationsCount": 1
			},
			{
				"authorID": "Tucker, Nicholas",
				"publicationsURL": "",
				"publicationsCount": 1
			},
			{
				"authorID": "Tucker, Robert C.",
				"publicationsURL": "",
				"publicationsCount": 1
			},
			{
				"authorID": "Tucker, Susan",
				"publicationsURL": "",
				"publicationsCount": 1
			},
			{
				"authorID": "Tucker, William M.",
				"publicationsURL": "",
				"publicationsCount": 1
			}
		]
	}
```
(I haven't suppled the publications URL field mapping yet)

So it looks like a bug or design issue?  It doesn't seem to support nested json structures?

Or am I missing something else?

**Comment by dmontagu** [comment]
@nrshapiro There should be no problems with nested json structures, and I don't see anything obvious about your use case that should be preventing you from getting this to work. Since you are getting an internal server error, it's probably not just a straightforward validation issue.

Could you set `debug=True` when you create the app
```python
app = FastAPI(debug=True)  # you might have more arguments
```
(this should make it easier to get the traceback), and then share the error traceback you are getting when you set `response_model=models.AuthorIndex` and try to access the docs?

**Comment by nrshapiro** [comment]
I started uvicorn with --debug too.  Here's the log:
```
2019-06-17 17:46:55,384 None - ASGI [1] Started
2019-06-17 17:46:55,384 None - ASGI [1] Sent {'type': 'lifespan.startup'}
2019-06-17 17:46:55,385 None - ASGI [1] Received {'type': 'lifespan.startup.complete'}
2019-06-17 17:47:02,118 ('127.0.0.1', 7621) - Connected
2019-06-17 17:47:02,119 ('127.0.0.1', 7621) - ASGI [2] Started
2019-06-17 17:47:02,119 ('127.0.0.1', 7621) - ASGI [2] Received {'type': 'http.response.start', 'status': 200, 'headers': '<...>'}
2019-06-17 17:47:02,119 ('127.0.0.1', 7621) - "GET /docs HTTP/1.1" 200
2019-06-17 17:47:02,119 ('127.0.0.1', 7621) - ASGI [2] Received {'type': 'http.response.body', 'body': '<873 bytes>'}
2019-06-17 17:47:02,119 ('127.0.0.1', 7621) - ASGI [2] Completed
2019-06-17 17:47:02,465 ('127.0.0.1', 7621) - ASGI [3] Started
2019-06-17 17:47:02,468 ('127.0.0.1', 7621) - ASGI [3] Received {'type': 'http.response.start', 'status': 500, 'headers': '<...>'}
2019-06-17 17:47:02,468 ('127.0.0.1', 7621) - "GET /openapi.json HTTP/1.1" 500
2019-06-17 17:47:02,469 ('127.0.0.1', 7621) - ASGI [3] Received {'type': 'http.response.body', 'body': '<3585 bytes>'}
2019-06-17 17:47:02,469 ('127.0.0.1', 7621) - ASGI [3] Raised exception
2019-06-17 17:47:02,469 Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\uvicorn\middleware\message_logger.py", line 58, in __call__
    raise exc from None
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\uvicorn\middleware\message_logger.py", line 54, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\uvicorn\middleware\debug.py", line 81, in __call__
    raise exc from None
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\uvicorn\middleware\debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\middleware\errors.py", line 122, in __call__
    raise exc from None
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\middleware\errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\exceptions.py", line 73, in __call__
    raise exc from None
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\starlette\routing.py", line 40, in app
    response = await func(request)
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\fastapi\applications.py", line 84, in openapi
    return JSONResponse(self.openapi())
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\fastapi\applications.py", line 76, in openapi
    openapi_prefix=self.openapi_prefix,
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\fastapi\openapi\utils.py", line 244, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\fastapi\utils.py", line 42, in get_model_definitions
    model, model_name_map=model_name_map, ref_prefix=REF_PREFIX
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 511, in model_process_schema
    model, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 537, in model_type_schema
    f, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 274, in field_schema
    ref_prefix=ref_prefix,
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 486, in field_type_schema
    ref_prefix=ref_prefix,
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 713, in field_singleton_schema
    field_type, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 511, in model_process_schema
    model, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 537, in model_type_schema
    f, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 274, in field_schema
    ref_prefix=ref_prefix,
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 486, in field_type_schema
    ref_prefix=ref_prefix,
  File "c:\users\nrsha\appdata\local\programs\python\python37\lib\site-packages\pydantic\schema.py", line 687, in field_singleton_schema
    if issubclass(field.type_, Enum):
TypeError: issubclass() arg 1 must be a class
2019-06-17 17:47:02,471 ('127.0.0.1', 7621) - Disconnected
2019-06-17 17:47:26,171 Started server process [72856]
```

**Comment by dmontagu** [comment]
@nrshapiro I think I found your problem. Here's your code:
```python
class AuthorIndexStruct(BaseModel):
    responseInfo: ResponseInfo(listType="authorindex") 
    responseSet: List[AuthorIndexItem] = []
```
The annotation on `responseInfo` seems wrong; I think it should be
```python
class AuthorIndexStruct(BaseModel):
    responseInfo: ResponseInfo = ResponseInfo(listType="authorindex") 
    responseSet: List[AuthorIndexItem] = []
```
or similar. In particular, what comes after the colon should be a type, not an instance.

I'm not sure I understand your goals here, but it seems like this might not be accomplishing what you intend -- you'd probably want to set the `listType` somewhere else when instantiating what is going to go into the `responseInfo`. (I don't think there is a way to modify the default arguments within an annotation, if that's your goal.)

If I'm understanding correctly, I'd probably just go with `responseInfo: ResponseInfo` as the annotation here.

**Comment by nrshapiro** [comment]
***Nailed it!***  Thank you!  I'm so glad it was just my error, because now it works properly!

Sorry to take your time, but I've only been working with FastAPI and Pydantic for a few days!

Again, very much appreciated.

**Comment by tiangolo** [comment]
Thanks for your help @stefanondisponibile and @dmontagu ! :rocket: :cake: 

And thanks @nrshapiro for reporting back and closing the issue :tada:
