### ISSUE TITLE
InternalError: Packet sequence number wrong

### ISSUE THREAD

**Issue by houmie** [tiangolo/fastapi#3193]
Hello,

I came across an issue on production that I can't replicate in the local environment.
The same code path often works, but sometimes throws this error. I don't understand, why this is happening.

I believe there is an issue with multi-thread nature of fastapi and internal usage of ```pymysql``` by ```databases```.
I'm pretty sure ```pymysql``` is single threaded.

But ```databases``` was supposed to support asyncio, correct? What am I doing wrong, please?

*crud_server.py*
```
db = databases.Database(settings.SQLALCHEMY_DATABASE_URI)

async def get_servers(is_maintenance: bool) -> List[Server]:
    query = ServerTable.select().where(ServerTable.c.is_maintenance == is_maintenance)
    if not db.is_connected:
        await db.connect()
    return await db.fetch_all(query)
```

*ServerTable.py*
```
metadata = MetaData(schema=settings.DBNAME_MAIN)

ServerTable = sqlalchemy.Table(
    "server",
    metadata,
    Column("id", String(15), primary_key=True),
    Column("name", String(100), nullable=False),
    Column("country", String(100), nullable=False),
    Column("group_master", String(15), nullable=True),
    Column("group_slave", String(15), nullable=True, index=True),
    Column("ip", String(length=45), nullable=False),
    Column("max_connections", Integer(), nullable=False),
    Column(
        "is_maintenance",
        Boolean(),
        nullable=False,
        server_default=text("0"),
        default=text("0"),
        index=True,
    ),
    Column("dow_maintenance", String(3), nullable=True),
    Column("hour_maintenance", Integer(), nullable=True),
    Column("minutes_maintenance", Integer(), nullable=True),
    Column("datetime_maintenance", TIMESTAMP(), nullable=True),
)
```

*Error:*
```
  File "/home/admin/tg/app/routers/server_status.py", line 25, in server_status
    servers = await crud_server.get_servers(is_maintenance=False)
  File "/home/admin/tg/app/database/crud_server.py", line 15, in get_servers
    return await db.fetch_all(query)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/databases/core.py", line 140, in fetch_all
    return await connection.fetch_all(query, values)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/databases/core.py", line 239, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/databases/backends/mysql.py", line 108, in fetch_all
    await cursor.execute(query, args)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 574, in _read_packet
    raise InternalError(
pymysql.err.InternalError: Packet sequence number wrong - got 0 expected 1
```

I would really appreciate a hint, what I'm doing wrong. 
Thank you so much

**Comment by frankie567** [comment]
Not sure it'll solve your particular issue but, usually, `database.connect` and `database.disconnect` are placed in event handlers:

```py
@app.on_event("startup")
async def startup():
    await database.connect()


@app.on_event("shutdown")
async def shutdown():
    await database.disconnect()
```

**Comment by houmie** [comment]
Thanks for your reply.

Yes, I already have that:
```
@app.on_event("startup")
async def startup():
    print("Starting up")
    if not db.is_connected:
        await db.connect()
    await google_token_verifier.on_startup()

@app.on_event("shutdown")
async def shutdown():
    print("Shutting down")
    await db.disconnect()
    await google_token_verifier.on_cleanup()
```

I had to insert the conditional everywhere for sake of unit tests. But do you think this could be the reason?

**Comment by frankie567** [comment]
I'm absolutely not sure, no. But *I feel* that it may cause some weirdness in some cases. 

If the only motivation is to make unit tests work, my advice would be to revisit this and make in sort to connect the database inside the unit tests:
* If you use the FastAPI test client, it'll run the event handlers so you shouldn't have to worry about it.
* If you have implemented an async test client (with HTTPX for example), you can use [asgi-lifespan](https://github.com/florimondmanca/asgi-lifespan) to ensure the event handlers are called. I use this pattern frequently: https://github.com/frankie567/fastapi-users/blob/89cff15c6b0de5432a0b268a53d1273ccd69d266/tests/conftest.py#L347-L351
* If you unit-test your `get_servers` function independently of a FastAPI app, it should be quite straightforward to connect the database inside the unit tests logic. For example, with pytest and pytest-asyncio, you can have a module-scoped fixture:

```py
@pytest.fixture(autouse=True, scope="module")
async def initialize_database():
    await db.connect()

    yield  # The unit-tests of the module are run after this

    # Cleanup/teardown logic
    await db.disconnect()
```

As a side-note, `encode/databases` don't use `pymysql` but [`aiomysql`](https://github.com/aio-libs/aiomysql); which is a "fork" of `pymysql` for asyncio. Some people  in issues are saying it's not maintained anymore 🤷‍♂️

**Comment by houmie** [comment]
Hi Frankie,

Thank you for providing these options.  Yes, I'm using HTTPX as async test client. I just implemented asgi-lifespan and removed all the offending ```database.connect``` elsewhere in code.  All unit tests are now passing. I have deployed the latest on production. Let's cross the fingers and observe this for a few more days.

Interesting about ```encode/databases```.  I checked and I saw I had ```PyMySQL[rsa]==0.9.3``` in my requirements.txt.
1) So I uninstalled it.  
2) I removed it from requirements.txt
3) Then ```pip install -U -r requirements.txt```

When I do ```pip freeze``` I see it's back again. 
```
PyMySQL==0.9.3
```

I think ```databases``` is using this as a dependency, no?

```
fastapi
gunicorn
uvicorn
email-validator
Jinja2
pytz
SQLAlchemy
mysqlclient
alembic
passlib
redis
retry
argon2_cffi
zxcvbn
python-crontab
structlog
python-dotenv
databases[mysql]
itsdangerous
aiosmtplib
tenacity
starlette-wtf
uvloop
httpx
httptools
pycryptodome
Aiogoogle
aiohttp_google_auth_backend
```

**Comment by houmie** [comment]
Hi Frankie,

I no longer see the issue reoccurring. Thanks for your help. I will close the issue and reopen again if it happens again.

In a nutshell two things may have helped.
1) Update of requirements.txt brought in latest FastAPI and SqlAlchemy 1.4, which may have fixed the issue.
2) As you said the conditional check of database connection is creating side effects.

Last but not least the code is much cleaner by using `asgi-lifespan`. :-)

**Comment by houmie** [comment]
@frankie567 

The problem is back again. It was ok only for four days.

```
[2021-05-16 06:06:00 +0000] [799] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette_wtf/csrf.py", line 140, in dispatch
    return await call_next(request)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/admin/tegant/app/main.py", line 98, in check_version
    versions = await db.fetch_all(query)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/databases/core.py", line 140, in fetch_all
    return await connection.fetch_all(query, values)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/databases/core.py", line 239, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/databases/backends/mysql.py", line 108, in fetch_all
    await cursor.execute(query, args)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/home/admin/.pyenv/versions/3.9.4/envs/venv/lib/python3.9/site-packages/aiomysql/connection.py", line 574, in _read_packet
    raise InternalError(
pymysql.err.InternalError: Packet sequence number wrong - got 0 expected 1
```

And after the first exception every subsequent call to the DB fails with the same error.
Maybe writing to database in async manner is not yet stable enough. Maybe I should have kept it sync.

Any advice for me what to do next, please? Thanks

**Comment by houmie** [comment]
I also share my config below in case I have setup ASGI / Gunicorn wrongly, which may have led to these instabilities.

```/etc/app-my/config.py```

```
bind = "127.0.0.1:8000"
backlog = 2048
workers = 13
worker_class = "uvicorn.workers.UvicornWorker"
worker_connections = 1000
timeout = 30
keepalive = 2
spew = False
daemon = False
pidfile = None
umask = 0
user = None
group = None
tmp_upload_dir = None
errorlog = "/var/log/app-my/error.log"
loglevel = "info"
accesslog = "/var/log/app-my/access.log"
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
proc_name = None


def post_fork(server, worker):
    server.log.info("Worker spawned (pid: %s)", worker.pid)


def pre_fork(server, worker):
    pass


def pre_exec(server):
    server.log.info("Forked child, re-executing.")


def when_ready(server):
    server.log.info("Server is ready. Spawning workers")


def worker_int(worker):
    worker.log.info("worker received INT or QUIT signal")

    import threading
    import sys
    import traceback

    id2name = {th.ident: th.name for th in threading.enumerate()}
    code = []
    for threadId, stack in sys._current_frames().items():
        code.append("\n# Thread: %s(%d)" % (id2name.get(threadId, ""), threadId))
        for filename, lineno, name, line in traceback.extract_stack(stack):
            code.append('File: "%s", line %d, in %s' % (filename, lineno, name))
            if line:
                code.append("  %s" % (line.strip()))
    worker.log.debug("\n".join(code))


def worker_abort(worker):
    worker.log.info("worker received SIGABRT signal")
```

```/etc/systemd/system/app-my.service```

[Unit]
Description=Gunicorn instance to serve MY
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/home/admin/my/app
Environment="PATH=/home/admin/.pyenv/versions/venv/bin"
ExecStart=/home/admin/.pyenv/versions/venv/bin/gunicorn -c /etc/app-my/config.py main:app
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by houmie** [comment]
Ahh I see. Thank you for heads-up. This is bad news indeed.

I suppose switching to the latest SQLAlchemy 14, which supports asynchio won't help either, because the underlying driver to MySQL database is buggy, correct?

Switching to Postgres is possible if there is no other way, but it's a huge undertaking.  Thanks for the tip, at least there is something we could do.

**Comment by houmie** [comment]
@frankie567 Thank you. Do you also use ```PGBouncer``` for Postgres? Do you recommend it or do you think it won't be necessary for FastAPI?

**Comment by frankie567** [comment]
I don't know PGBouncer, sorry 🤷‍♂️ My advice would be to start simple with a standard installation, see how it goes, before considering something more complex.

**Comment by houmie** [comment]
Hello @frankie567 
Sorry to bother you with this. Switching from MySQL to Postgres is a bit challenging.

Do you know how to resolve this? https://stackoverflow.com/questions/67693489/sqlalchemy-cant-find-schema-after-switching-from-mysql-to-postgresql

I'm using databases[postgresql] for async and psycopg2 for alembic etc.  Why is SqlAlchemy Core acting up like this? Since you know Postgres so well, maybe you can nudge me into the right direction. Thank you

**Comment by iskandertaneev** [comment]
Hi @houmie! Have you had any luck fixing this issue?

**Comment by houmie** [comment]
Hi @iskandertaneev 
Yes, but you won't like the solution. As mentioned above aiomysql has fallen behind and is barely maintained anymore.  The Python community doesn't like MySQL as much as they do Postgres.

I had to bite into the bullet and switch over entirely to Postgres.  Also don't use `Databases`, I don't recommend it.  
It's better to use the internal asyncpg that is well maintained. 

Overall I love Fast-API in async with Postgres. And have been live for six months on production without those issues I had with MySQL. I hope this helps.

**Comment by iskandertaneev** [comment]
Thank you for your reply @houmie! You were right, I don't like this 😁  But I'm glad to hear that you have managed to overcome this issue. Unfortunately for me, I don't think it would be possible to switch to postgres. 

Hey @tiangolo, mb there's a way to address this?

**Comment by terrysclaw** [comment]
Hi @iskandertaneev 
Have you had any luck fixing this issue?

**Comment by iskandertaneev** [comment]
Hi @terrysclaw! I deployed my service with postgres. It seems to work ok.

**Comment by terrysclaw** [comment]
Hi @houmie @iskandertaneev,

I tried to add pool_pre_ping, pool_recycle parameters into the create_async_engine method. It seem work for me. I hope this helps.

engine = create_async_engine(
    settings.DB_URL,
    echo=False,
    pool_pre_ping=True,
    pool_recycle=3600
)
