### ISSUE TITLE
Using '__root__' in BaseModel in `response_model` does not work with pydantic>1.8.0

### ISSUE THREAD

**Issue by StefanBRas** [tiangolo/fastapi#3218]
### First check

* [X] I added a very descriptive title to this issue.
* [X] I used the GitHub search to find a similar issue and didn't find it.
* [X] I searched the FastAPI documentation, with the integrated search.
* [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [X] I already read and followed all the tutorial in the docs and didn't find an answer.
* [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [X] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

Here's a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

```Python
from pydantic import BaseModel
from typing import Mapping
from fastapi import FastAPI
from starlette.testclient import TestClient

app = FastAPI()

class RootTest(BaseModel):
    __root__: Mapping[str, str]

@app.get("/", response_model=RootTest)
def root():
    return RootTest(__root__={"a": "b"})

client = TestClient(app)
assert client.get(f'/').json() == {"a": "b"}
```

Running this with Pydantic > 1.8.0 gives

<details>
<summary>Error output</summary>
<p>

```bash
Traceback (most recent call last):
  File "../fastapirootOld/github.py", line 16, in <module>
    client.get(f'/simple')
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/testclient.py", line 431, in request
    json=json,
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/testclient.py", line 243, in send
    raise exc from None
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/testclient.py", line 240, in send
    loop.run_until_complete(self.app(scope, receive, send))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/fastapi/routing.py", line 217, in app
    is_coroutine=is_coroutine,
  File "/home/sras/dev/fastapiroot/venv/lib/python3.7/site-packages/fastapi/routing.py", line 126, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for RootTest
response -> __root__ -> __root__
  str type expected (type=type_error.str)
```

</p>
</details>

Running it with Pydantic 1.7.4 gives no errors.

### Description

This used to work but apparently breaks for newer pydantic versions. I'm not sure if it's a Pydantic or FastApi problem as it seems to come from a difference with how `ModelField.validate` works. Running the following:
```python
from pydantic import BaseModel
from typing import Dict
from fastapi.utils import create_response_field

class RootTest(BaseModel):
    __root__: Dict[str, str]

model_field = create_response_field('root_test', type_=RootTest)

test_objects = [RootTest(__root__={"a": "b"}), {"a": "b"}, {"__root__":{"a": "b"}}]

for obj in test_objects:
    print(f"Obj: {obj} - Result: {model_field.validate(obj, {}, loc=('reponse',))}")
```

yields these different results:

<details>
<summary>Pydantic 1.8.2 </summary>
<p>

```bash
Obj: __root__={'a': 'b'} - Result: (RootTestSimple(__root__={'a': 'b'}), None)
Obj: {'a': 'b'} - Result: (RootTestSimple(__root__={'a': 'b'}), None)
Obj: {'__root__': {'a': 'b'}} - Result: ({'__root__': {'a': 'b'}}, ErrorWrapper(exc=ValidationError(model='RootTestSimple', errors=[{'loc': ('__root__', '__root__'), 'msg': 'str type expected', 'type': 'type_error.str'}]), loc=('reponse',)))
```

</p>
</details>

<details>
<summary>Pydantic 1.7.4 </summary>
<p>

```bash
Obj: __root__={'a': 'b'} - Result: (RootTestSimple(__root__={'a': 'b'}), None)
Obj: {'a': 'b'} - Result: ({'a': 'b'}, ErrorWrapper(exc=ValidationError(model='RootTestSimple', errors=[{'loc': ('__root__',), 'msg': 'field required', 'type': 'value_error.missing'}]), loc=('reponse',)))
Obj: {'__root__': {'a': 'b'}} - Result: (RootTestSimple(__root__={'a': 'b'}), None)
```

</p>
</details>

Since `_prepare_response_content` parses using `obj.dict(...)`, `BaseModel` objects that use `__root__` will be converted to a dict with the single key `__root__`. This case however fails to validate in Pydantic 1.8.2 (and 1.8.1 and 1.8.0).

I don't know enough about `ModelField` to say if this is a Pydantic issue or an issue with how FastApi uses it.

### Environment

* OS: Ubuntu 18.04 (in WSL2)
* FastAPI Version: 0.65.1
* Python version: 3.7.5

**Comment by wdroz** [comment]
Work with pydantic 1.8.2 and fastapi 0.66.0 if you modify as
```python
from pydantic import BaseModel
from typing import Mapping
from fastapi import FastAPI
from starlette.testclient import TestClient

app = FastAPI()

class RootTest(BaseModel):
    __root__: Mapping[str, str]

@app.get("/", response_model=RootTest)
def root():
    return {"a": "b"}

client = TestClient(app)
assert client.get(f'/').json() == {"a": "b"}
```

**Comment by StefanBRas** [comment]
@wdroz Nice, that works great. It's still problematic for me however since I in many cases receive the data as the actual Pydantic model from elsewhere. I could solve it by returning `RootTest(...).__root__` instead, but that's not very pretty and not very DRY. Also optimally it only takes `__root__` if the pydantic version is >= 1.8 which would make it even uglier.
