### ISSUE TITLE
typing.Type field breaks Swagger

### ISSUE THREAD

**Issue by roveo** [tiangolo/fastapi#3275]
### Example

```Python
from typing import Type

import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel

class Container(BaseModel):
    T: Type

app = FastAPI()

@app.get("/", response_model=Container)
def index(container: Container):
    return container

if __name__ == "__main__":
    uvicorn.run("app:app")
```

### Description

* Run the above with python
* go to http://localhost:8000/docs
* should open Swagger docs
* there's an error instead

![image](https://user-images.githubusercontent.com/5427958/119194963-87b66f00-ba8c-11eb-812b-1d02cb3613f7.png)

### Environment

* OS: macOS
* FastAPI Version 0.65.1
* Python version: 3.9.4

### Additional context

Stack trace from the server:

```
❯ python app.py
INFO:     Started server process [97855]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:56421 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:56421 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/fastapi/applications.py", line 152, in openapi
    return JSONResponse(self.openapi())
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/fastapi/applications.py", line 130, in openapi
    self.openapi_schema = get_openapi(
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 363, in get_openapi
    definitions = get_model_definitions(
  File "/Users/roveo/.pyenv/versions/baguette/lib/python3.9/site-packages/fastapi/utils.py", line 24, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 839, in pydantic.schema.field_singleton_schema
  File "/Users/roveo/.pyenv/versions/3.9.4/lib/python3.9/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

The functionality that I want in my use case works correctly: I tested the API and custom (de)serialization logic is OK, I get what I want from it, but both `/docs` and `/redoc` return this error (because `openapi.json` fails to generate, I reckon).

**Comment by ycd** [comment]
What about using `typing.Any`?

**Comment by roveo** [comment]
`typing.Any` would work I believe, but the field is not `Any`, it's a `Type` value.
