### ISSUE TITLE
Failed to load API definition. Fetch error Internal Server Error /openapi.json - don't know where to start

### ISSUE THREAD

**Issue by agropper** [tiangolo/fastapi#3328]
I'm new to FastAPI and was making spectacular progress integrating Stripe, CouchDB, and even SendGrid. Then, out of the blue, **"Failed to load API definition. Fetch error Internal Server Error /openapi.json"** comes up on /docs Even rolling back to previous versions doesn't change things. 

FastAPI is running but the /docs is dead and I don't know where to go next. Google searches give confusing advice for this novice.

The code is here: https://github.com/agropper/T2FastAPI 

The Terminal output is:

(venv) MacBookPro:T2FastAPI adrian$ python main.py
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
INFO:     Started reloader process [1363] using statreload
INFO:     Started server process [1365]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:49873 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:49873 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:49876 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:49876 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/fastapi/applications.py", line 152, in openapi
    return JSONResponse(self.openapi())
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/fastapi/applications.py", line 130, in openapi
    self.openapi_schema = get_openapi(
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 368, in get_openapi
    result = get_openapi_path(route=route, model_name_map=model_name_map)
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 194, in get_openapi_path
    operation_parameters = get_openapi_operation_parameters(
  File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 98, in get_openapi_operation_parameters
    "schema": field_schema(
  File "pydantic/schema.py", line 234, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 202, in pydantic.schema.get_field_info_schema
  File "pydantic/schema.py", line 899, in pydantic.schema.encode_default
  File "pydantic/json.py", line 95, in pydantic.json.pydantic_encoder
TypeError: Object of type 'type' is not JSON serializable

**Comment by frankie567** [comment]
The error comes from [this line](https://github.com/agropper/T2FastAPI/blob/main/app/api.py#L119):

```py
async def webhook_received(request: Request, stripe_signature: str = Header(str)):
```

You put `str` as default argument for `Header` (I guess it's not intentional). Thus, when OpenAPI tries to generate the schema and discover the default values, it tries to serialize `str`, which obviously isn't a valid value in this context.

**Comment by agropper** [comment]
Thank you @frankie567! Cutting the /webhook route brought back the /docs.

The code comes from @ianrufus very helpful FastAPI tutorials https://github.com/ianrufus/youtube/blob/main/fastapi-stripe-webhook/app.py#L68 and I will let him know. 

Before closing this issue, given my novice status, I wonder how I was supposed to figure this out.

**Comment by Cajuteq** [comment]
Hi, on how you could have figured out, the logs are actually pretty explicit although not that simple to read for beginners.

first it shows : INFO: 127.0.0.1:49876 - "GET /docs HTTP/1.1" 200 OK
so we know that /docs exists and is exposed, 

then : INFO: 127.0.0.1:49876 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
shows that, as documentation generation relies on openapi, the error comes from openapi generation;

then, following the call stack, 
File "/Users/adrian/Documents/GitHub/T2FastAPI/venv/lib/python3.9/site-packages/fastapi/applications.py", line 152, in openapi
return JSONResponse(self.openapi())
confirm that openapi fails while trying to create a JSON out of your code,

TypeError: Object of type 'type' is not JSON serializable
ultimately confirm it is a JSON serialization problem.

Then, knowing the problem comes from openapi json generation, one has to read all the endpoints definition read by openapi (that is all which don't have include_in_schema=False in the decorator) 
As you don't have much endpoints and as most of them are simple and straightforward, you end up finding the type error in the /webhook definition header

I hope this helps you see how to read and follow a stack trace and ultimately find bugs.

Also note that it is way easier to find if you already know that fastAPI docs are generated using openapi and that openapi creates a standardized JSON out of your endpoints definitions !

**Comment by agropper** [comment]
Thanks @Cajuteq! That's exactly what I was hoping for. 

I have been going through the superb tutorial and slowly getting the lay of the land.

Closing.

**Comment by KelbyFaessler** [comment]
wow I was using some of the code from @ianrufus and the webook route broke my docs and eventually I figured out the Header(str) vs Header(None) thing, but I wish I had found this first. He should really merge a fix for that
