### ISSUE TITLE
Is the document old or bugs?

### ISSUE THREAD

**Issue by gotounix** [tiangolo/fastapi#337]
I read the document and run the code in the documents.
But I have some problems that the result is not equal the document's result.
Such as:

1.Create an Enum class

```
from enum import Enum

from fastapi import FastAPI


class ModelName(Enum):
    alexnet = "alexnet"
    resnet = "resnet"
    lenet = "lenet"


app = FastAPI()


@app.get("/model/{model_name}")
async def get_model(model_name: ModelName):
    if model_name == ModelName.alexnet:
        return {"model_name": model_name, "message": "Deep Learning FTW!"}
    if model_name.value == "lenet":
        return {"model_name": model_name, "message": "LeCNN all the images"}
    return {"model_name": model_name, "message": "Have some residuals"}
```

I have errors while run it:

```
(env) λ uvicorn main:app --reload
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: Started reloader process [17700]
email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "f:\test\fastapi\env\lib\site-packages\uvicorn\main.py", line 305, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "f:\test\fastapi\env\lib\site-packages\uvicorn\main.py", line 312, in serve
    config.load()
  File "f:\test\fastapi\env\lib\site-packages\uvicorn\config.py", line 182, in load
    self.loaded_app = import_from_string(self.app)
  File "f:\test\fastapi\env\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\main.py", line 16, in <module>
    async def get_model(model_name: ModelName):
  File "f:\test\fastapi\env\lib\site-packages\fastapi\routing.py", line 278, in decorator
    name=name,
  File "f:\test\fastapi\env\lib\site-packages\fastapi\routing.py", line 238, in add_api_route
    name=name,
  File "f:\test\fastapi\env\lib\site-packages\fastapi\routing.py", line 184, in __init__
    self.dependant = get_dependant(path=path, call=self.endpoint)
  File "f:\test\fastapi\env\lib\site-packages\fastapi\dependencies\utils.py", line 150, in get_dependant
    ), f"Path params must be of one of the supported types"
AssertionError: Path params must be of one of the supported types
INFO: Stopping reloader process [17700]
```

2.Query parameter list / multiple values with defaults

```
from typing import List

from fastapi import FastAPI, Query

app = FastAPI()


@app.get("/items/")
async def read_items(q: List[str] = Query(["foo", "bar"])):
    query_items = {"q": q}
    return query_items
```

The result should be:

```
{
  "q": [
    "foo",
    "bar"
  ]
}
```

But I got:

```
{
  "q": []
}
```

I use Windows 10, and the env is:
```
(env) λ python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

F:\Test\fastapi
(env) λ pip freeze
Click==7.0
fastapi==0.23.0
h11==0.8.1
pydantic==0.25
starlette==0.12.0
uvicorn==0.7.1
websockets==7.0
```

**Comment by dmontagu** [comment]
@gotounix Those are old versions of both pydantic and fastapi -- try upgrading and see if the issue still exists.

I can't test it now, but if you still run into the issue after upgrading, you may need to also inherit from `str`:
```python
class ModelName(str, Enum):
    alexnet = "alexnet"
    resnet = "resnet"
    lenet = "lenet"
```

**Comment by tiangolo** [comment]
Thanks for your help @dmontagu ! :cake: 

Thanks @gotounix for closing the issue.

**Comment by classywhetten** [comment]
I believe I'm encountering a similar issue (the error is nearly identical). I've tried using both:

`files: list = Query(None)`

and

`files: List[str] = Query(None)`

in both scenarios I'm encountering this error:
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: Started reloader process [32223]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/uvicorn/supervisors/statreload.py", line 29, in handle_fds
    target(**kwargs)
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/uvicorn/main.py", line 307, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/uvicorn/main.py", line 314, in serve
    config.load()
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/uvicorn/config.py", line 186, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app/main.py", line 149, in <module>
    files: list = Query(None)
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/fastapi/routing.py", line 474, in decorator
    callbacks=callbacks,
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/fastapi/routing.py", line 418, in add_api_route
    callbacks=callbacks,
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/fastapi/routing.py", line 315, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/home/brian/rieslingendpoint/venv/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 287, in get_dependant
    ), f"Path params must be of one of the supported types"
AssertionError: Path params must be of one of the supported types
INFO: Stopping reloader process [32223]

my environment:
$python3 --version
Python 3.7.6

$pip freeze
aiofiles==0.4.0
async-exit-stack==1.0.1
async-generator==1.10
bcrypt==3.1.7
cffi==1.13.1
Click==7.0
dataclasses==0.6
fastapi==0.52.0
h11==0.8.1
h2==3.1.1
hpack==3.0.0
httptools==0.0.13
hyperframe==5.2.0
passlib==1.7.1
pkg-resources==0.0.0
pycparser==2.19
pydantic==1.4
PyJWT==1.7.1
python-multipart==0.0.5
pytoml==0.1.21
six==1.12.0
SQLAlchemy==1.3.10
starlette==0.13.2
typing-extensions==3.7.4
uvicorn==0.9.0
uvloop==0.13.0
websockets==8.0.2
Werkzeug==0.16.0
wsproto==0.15.0

I've tried upgrading fastapi and pydantic, and I'm still continuing to run into the same issue.
