### ISSUE TITLE
APIRouter and static files (starlette.routing.NoMatchFound)

### ISSUE THREAD

**Issue by facundopadilla** [tiangolo/fastapi#3389]
### First check

* [X] I added a very descriptive title to this issue.
* [X] I used the GitHub search to find a similar issue and didn't find it.
* [X] I searched the FastAPI documentation, with the integrated search.
* [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [X] I already read and followed all the tutorial in the docs and didn't find an answer.
* [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [X] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

-----------
### Technical details:
```
aiofiles==0.7.0
asgiref==3.3.4
click==8.0.1
fastapi==0.65.2
h11==0.12.0
Jinja2==3.0.1
MarkupSafe==2.0.1
pydantic==1.8.2
starlette==0.14.2
typing-extensions==3.10.0.0
uvicorn==0.14.0
```
### Project structure

```
.
├── core
│   ├── apps
│   │   ├── admin
│   │   └── login
│   │       └── views.py
│   ├── extension
│   ├── models
│   ├── settings.py
├── static
│   │   └── all css files/folders
├── templates
│   │   └── login.html
│   │   └── base.html
└── tests
└── server.py
```

## The problem

Hello everyone, there is something that I am not quite understanding and it is when working with static files.

I am working with an APIRouter, the idea is to modularize, to have everything separated.

When I do the mount of the static files, it does not generate any error, but when I use Jinja2 to render a template that has a static file, it generates an error. 

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/routing.py", line 390, in handle
    await self.app(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "./core/apps/login/views.py", line 27, in get
    return render.TemplateResponse("login.html", context={"request": request})
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/templating.py", line 81, in TemplateResponse
    return _TemplateResponse(
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/templating.py", line 27, in __init__
    content = template.render(context)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "templates/base.html", line 14, in top-level template code
    {% block css %} {% endblock %}
  File "templates/login.html", line 6, in block 'css'
    <link href="{{ url_for('login:static', filename='/vendor/fontawesome-free/css/all.css') }}" rel="stylesheet" type="text/css">
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/templating.py", line 59, in url_for
    return request.url_for(name, **path_params)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/requests.py", line 163, in url_for
    url_path = router.url_path_for(name, **path_params)
  File "/home/facundo/jobcamp/v1/env_jobcamp/lib/python3.8/site-packages/starlette/routing.py", line 508, in url_path_for
    raise NoMatchFound()
starlette.routing.NoMatchFound
```
--------
#### core/apps/login.py
```python
from fastapi import APIRouter, Request
from fastapi.templating import Jinja2Templates
from starlette.responses import HTMLResponse

def get_router():
    return router 

router = APIRouter()
render = Jinja2Templates("templates")

@router.get("/login", response_class=HTMLResponse)
async def get(request: Request):
    return render.TemplateResponse("login.html", context={"request": request})

```
#### /server.py
```python
from core.settings import start_application

app = start_application()
```

#### core/settings.py
```python
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

def configure_static(app: FastAPI):
    app.mount("/static", StaticFiles(directory="static"), name="static")

def start_application():
    app = FastAPI(title="Project name")
    configure_static(app)
    return app
```
#### templates/login.html
```html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block css %}
    <link href="{{ url_for('static', filename='/vendor/fontawesome-free/css/all.css') }}" rel="stylesheet" type="text/css">
{% endblock %}
```
-----
## I have tried several things and was unsuccessful

I found a thread where a person basically had the same problem but was able to solve it, I tried to do it as similar as possible to what this person did and I was unsuccessful: https://github.com/tiangolo/fastapi/issues/1111

From what I understood, I need to "mount" a new Starlette "app", which I did, but I didn't succeed, I keep getting the same error.

#### core/apps/login/views.py
```python
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import HTMLResponse, PlainTextResponse
from starlette.routing import Route
from fastapi import APIRouter
from fastapi.templating import Jinja2Templates

def _get_mount():
    mount = Starlette(
        routes=[
            Route(
                "/login", function_get, methods=["GET"], name="get"
            )
        ]
    )
    return mount

router = APIRouter()
render = Jinja2Templates("templates")

@router.get("/login", response_class=HTMLResponse)
async def function_get(request: Request):
    return render.TemplateResponse("login.html", context={"request": request})
```

#### /core/settings.py
```python
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from core.apps.login import views

def configure_static(app: FastAPI):
    app.mount("/login", views._get_mount(), name="login")
    app.mount("/static", StaticFiles(directory="static"), name="static")
```

#### When I enter the endpoint, the following appears in the terminal
```python
INFO:     Started server process [32539]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:33512 - "GET /login HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:33512 - "GET /login/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:33512 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```
--------

On the other hand, I also understand that I am "mixing" FastAPI classes with Starlette, which in theory, is not wrong, but I feel that it is wrong haha.

Any ideas? I tried many things that I already forgot what they were but I could not succeed, or maybe I am failing in something and I have no idea.

**Comment by tusharvickey1999** [comment]
@facundopadilla try using `path` instead of `filename` in `url_for()` inside `login.html`

**Comment by tom0010** [comment]
Had the same issue when migrating from Flask to FastAPI. Thanks @tusharvickey1999!
