### ISSUE TITLE
nan is not supported when i declare a request body class with an object having default value as nan 

### ISSUE THREAD

**Issue by skrakesh5** [tiangolo/fastapi#3417]
I was using fastAPI through swagger UI, In one instance i had defined request body as class with one of the class object of the request body having default value as numpy.nan.

Example code :
```
import numpy
class Model(pydantic.BaseModel):
    value: float = numpy.nan

app.get('/this')
def get_this(request_body: Model):
    return request_body.value
```

this is the error i got on the swagger UI when i tried testing the API on swagger UI.
![image](https://user-images.githubusercontent.com/29368761/123578302-20aa7980-d7f3-11eb-9179-17db75be575e.png)

This is the logs:
```
←[32mINFO←[0m:     127.0.0.1:58758 - "←[1mGET /openapi.json HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 388, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fastapi\applications.py", line 181, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fastapi\applications.py", line 130, in openapi
    return JSONResponse(self.openapi())
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\responses.py", line 162, in render
    separators=(",", ":"),
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant 
```

**Comment by Mause** [comment]
The error is correct, `numpy.nan` is not valid json - try `float('nan')` instead

**Comment by Mause** [comment]
Looks like it's not allowed in the default json response model: https://github.com/encode/starlette/blob/master/starlette/responses.py#L160

**Comment by vincentsarago** [comment]
@skrakesh5 you can use simplejson to `ignore_nan` (which will be translated to `null`)

see: https://github.com/developmentseed/titiler/blob/customJSONResponseForNaN/src/titiler/core/titiler/core/resources/responses.py#L16-L31

This was the easiest way I found, if anyone has a better solution I'm all 👂

**Comment by MicaelJarniac** [comment]
The links on both replies seem to be broken.

**Comment by vincentsarago** [comment]
@MicaelJarniac https://github.com/developmentseed/titiler/blob/1f2d5eb0853b5d35d81464910ee0274598d3d1b3/src/titiler/core/titiler/core/resources/responses.py#L16-L31
