### ISSUE TITLE
KeyError when using the Pydantic model dynamically created by created_model in two Generic Model as response model

### ISSUE THREAD

**Issue by hail-pas** [tiangolo/fastapi#3464]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to one of:
  * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
  * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
  * Implement a Pull Request for a confirmed bug.

### Environment

* OS: macOS  10.15.7
* FastAPI:  0.65.2
* Pydantic:  1.8.2
* SQLAlchemy:  1.4.18 

### My Purpose

To differentiate single data response and page data response

#### 1. Database Model

```python
import abc
import sqlalchemy
from sqlalchemy.orm import ColumnProperty, DeclarativeMeta, declared_attr, declarative_base
from typing import List, Type, Union, TypeVar, Optional

class BaseModelMeta(DeclarativeMeta, abc.ABCMeta):
    PyModel = TypeVar('PyModel', bound='BaseModel')

    # Pydantic
    @property
    def response_model(cls) -> Type['PyModel']:
        """
        Non-relationship field to pydantic model
        """

        def generate_response_model(model):
            class Config(BaseConfig):
                orm_mode = True

            kwargs = {
                "id": ModelField(name="id", type_=int, default=..., required=True,
                                 field_info=FieldInfo(default=..., title="ID", description="Primary Key"),
                                 model_config=Config, class_validators=None)
            }
            config = getattr(model, "Config")
            mapper = inspect(model)
            for attr in mapper.attrs:
                if isinstance(attr, ColumnProperty):
                    if attr.columns:
                        column_name = attr.key
                        if (column_name in model.common_column) or (column_name.endswith("_id")) or (
                                config and column_name in getattr(config, "exclude", [])):
                            continue
                        column = attr.columns[0]
                        python_type: Optional[type] = None
                        if hasattr(column.type, "impl"):
                            if hasattr(column.type.impl, "python_type"):
                                python_type = column.type.impl.python_type
                        elif hasattr(column.type, "python_type"):
                            python_type = column.type.python_type
                        assert python_type, f"Could not infer python_type for {column}"
                        default = None
                        if column.default is None and not column.nullable:
                            default = ...
                        kwargs[column_name] = ModelField(name=column_name, type_=python_type, default=None,
                                                         required=bool(default),
                                                         field_info=FieldInfo(default=None,
                                                                              title=attr.columns[0].comment,
                                                                              description=attr.columns[0].comment),
                                                         model_config=Config, class_validators=None)
            kwargs["updated_at"] = ModelField(name="updated_at", type_=datetime, default=None, required=True,
                                              field_info=FieldInfo(default=None, title="Updated at Datetime",
                                                                   description="Updated at Datetime"),
                                              model_config=Config, class_validators=None)
            kwargs["created_at"] = ModelField(name="created_at", type_=datetime, default=None, required=True,
                                              field_info=FieldInfo(default=None, title="Created at Datetime",
                                                                   description="Created at Datetime"),
                                              model_config=Config, class_validators=None)
            temp = create_model(f"{model.__name__}RespModel",
                                __config__=Config)
            temp.__fields__ = kwargs
            return temp
        return generate_response_model(cls)


class BaseModel(db.Model, metaclass=BaseModelMeta):
    id = sqlalchemy.Column(comment="ID", type_=sqlalchemy.Integer, primary_key=True, index=True)
    created_at = sqlalchemy.Column(comment="Created at Datetime", type_=sqlalchemy.DateTime,
                                   server_default=func.now(), )
    updated_at = sqlalchemy.Column(comment="Updated at Datetime", type_=sqlalchemy.DateTime, server_default=func.now(),
                                   onupdate=func.now())

    # Generate table name automatically
    @declared_attr
    def __tablename__(cls) -> str:
        return "_".join([i.lower() for i in re.findall('[A-Z][^A-Z]*', cls.__name__)])

    __abstract__ = True

    @classmethod
    async def get(cls, pk):
        """
        Get Model Instance with PK
        """

    @classmethod
    async def page_data(cls, pager: Pager, *join_loads, **kwargs):
        """
        Return PageInfo data and instance paginated data list
        """


class User(BaseModel):
    __table_args__ = {"comment": "users"}
    username = Column(comment="name of user", type_=String(150), default="")
    phone = Column(comment="phone number", type_=String(11), unique=True, nullable=False)
    password = Column(comment="password hash", type_=String(100), nullable=False)
    last_login_at = Column(comment="last login at datetime", type_=DateTime)
    remark = Column(comment="remarks", type_=String(200), default="")

```

#### 2. Generic Response Model

```python
from typing import List, Generic, TypeVar, Optional
from datetime import datetime
from pydantic import BaseModel, typing, validator
from pydantic.generics import GenericModel

DataT = TypeVar("DataT")


class Resp(GenericModel, Generic[DataT]):
    """
    General Single Response
    """

    code: int = 100200
    responseTime: datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    message: Optional[str] = None
    data: Optional[DataT] = None

    @validator("data", always=True)
    def check_consistency(cls, v, values):
        if values.get("message") is None and values.get("code") != 100200:
            raise ValueError(f"Must provide a message when code is not 100200!")
        if values.get("message") and v:
            raise ValueError("Response can't provide both message and data!")
        return v


class PageInfo(BaseModel):
    """
    Page Info
    """

    total_page: int
    total_count: int
    size: int
    page: int


class PageResp(Resp, Generic[DataT]):
    """
    General Page Response
    """
    page_info: PageInfo
    data: Optional[List[DataT]] = None


class Pager(BaseModel):
    limit: PositiveInt = 10
    offset: conint(ge=0) = 0
```

#### 3. API Route

```python
@router.get(
    path="/get/user", response_model=PageResp[models.User.response_model], description="Get User Info List",
    summary="User Info"
)
async def get_models_func(pager: Pager = Depends(get_pager)):
    page_info, data = await models.User.page_data(pager=pager)
    return PageResp[models.User.response_model](page_info=page_info, data=data)


@router.get(
    path="/get/user/{pk}", response_model=Resp[models.User.response_model], description="Get Single User Info",
    summary="User Info"
)
async def get_models_func(pk: int):
    user = await models.User.get(pk=pk)
    return Resp[models.User.response_model](data=user)
```

### Exception Traceback

```shell
Traceback (most recent call last):
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/fastpost/middlewares.py", line 9, in add_process_time_header
    response = await call_next(request)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/fastpost/globals.py", line 91, in __call__
    await self.app(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/fastapi/applications.py", line 152, in openapi
    return JSONResponse(self.openapi())
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/fastapi/applications.py", line 137, in openapi
    servers=self.servers,
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 364, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "/Users/phoenix/GitRepo/Phoenix/fastpost/venv/lib/python3.7/site-packages/fastapi/utils.py", line 28, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.UserRespModel'>
```

### Additional

I have found it will work fine if I create dynamic response mode with different class name in generate_response_model func. eg

```python
# use uuid to identify
create_model(f"{model.__name__}RespModel{str(uuid.uuid1())[:8]}", __config__=Config)
"""
There will generate two pydantic model with the same structure, these two is itendical for me, I just need one
	- UserRespModel11f93940
	- UserRespModel11fb87d6
And the Generic Model separately use them
        - PageResp[UserRespModel11f93940]
        - Resp[UserRespModel11fb87d6]
"""
```

I have searched for this couple of days but with nothing, and I just embrace into FastAPI recently, so I'm not sure if it is a bug or not. So I open a question to ask help. Thanks for anyone's opinions and views.

**Comment by uriyyo** [comment]
Hi @hail-pas,

That because you don't save result of `response_model` call and it always generates new class.

It can be fixed by adding `lru_cache` decorator:
```python
from functools import lru_cache

class BaseModelMeta(DeclarativeMeta, abc.ABCMeta):
     ...

    @property
    @lru_cache(None)
    def response_model(cls) -> Type['PyModel']:
        pass
```

**Comment by hail-pas** [comment]
> Hi @hail-pas,
> 
> That because you don't save result of `response_model` call and it always generates new class.
> 
> It can be fixed by adding `lru_cache` decorator:
> 
> ```python
> from functools import lru_cache
> 
> class BaseModelMeta(DeclarativeMeta, abc.ABCMeta):
>      ...
> 
>     @property
>     @lru_cache(None)
>     def response_model(cls) -> Type['PyModel']:
>         pass
> ```
> 
> Or you can use `cached_property` (for versions bellow python `3.8` you can use [this backport](https://pypi.org/project/backports.cached-property/)):
> 
> ```python
> from functools import cached_property
> 
> class BaseModelMeta(DeclarativeMeta, abc.ABCMeta):
>      ...
> 
>     @cached_property
>     def response_model(cls) -> Type['PyModel']:
>         pass
> ```

@uriyyo Thank you so much, that works.
