### ISSUE TITLE
fastapi 从0.65.3 升级到 0.66.0 引发KeyError: None

### ISSUE THREAD

**Issue by xujiang1** [tiangolo/fastapi#3502]
环境说明： windows 10 使用 uvicorn部署fastapi 

当我将fastapi从0.65.3 升级到 0.66.0 会引发错误：
```
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await response(scope, receive, send)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\responses.py", line 224, in __call__
    await run_until_first_complete(
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\responses.py", line 209, in stream_response
    await send(
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\starlette\middleware\errors.py", line 156, in _send
    await send(message)
  File "C:\Users\xuzhu\.virtualenvs\re_fastapi\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 471, in send
    reason = STATUS_PHRASES[status_code]
KeyError: None
```

**Comment by TnTomato** [comment]
What is the version of your Python and Uvicorn?

**Comment by Ro0tk1t** [comment]
status code should between 100 ~ 600

**Comment by panla** [comment]
在某一个返回响应的地方

return JSONResponse(content=content, status_code=status_code)

status_code 超出了要求

**Comment by xujiang1** [comment]
> 你的 Python 和 Uvicorn 是什么版本？

Python 3.8.2
 uvicorn              0.13.4

**Comment by xujiang1** [comment]
> status code should between 100 ~ 600

but neow status code is None

**Comment by xujiang1** [comment]
我查询了这个错误,来自 re_fastapi\Lib\site-packages\uvicorn\protocols\http\h11_impl.py 的436行 async def send(self, message):的函数，该函数传入message参数 ， status_code = message["status"] status_code 由message 得到，
我打印了message 得到：{'type': 'http.response.start', 'status': None, 'headers': [(b'content-length', b'13'), (b'content-type', b'application/json'), (b'x-process-ti
me', b'0.001983165740966797')]}

**Comment by xujiang1** [comment]
发现问题 自己代码的问题
