### ISSUE TITLE
Can't pass an empty list of `multipart/form-data` fields if typing is `list[bytes]` and `content-type: multipart/form-data` when sending request

### ISSUE THREAD

**Issue by deknowny** [tiangolo/fastapi#3506]
I have a logic for creating comments (reviews) for some entity. The comment has text, rating, user authorized ID and a list of photos. I want to allow pass my photos as list of `multipart/form-data` values. I make a router that gets `list[bytes]` like this:

```python
…
@router.post("/", status_code=fastapi.status.HTTP_201_CREATED)
async def create_review(
    place_id: int = fastapi.Path(..., description="Место, которому нужно оставить комментарий"),
    user_id: int = fastapi.Depends(user_auth),
    photos: list[bytes] = fastapi.File(..., description="Фотографии к комментарию"),
    text: str = fastapi.Query(..., description="Текст комментария"),
    rating: int = fastapi.Query(..., ge=1, le=5, description="Рейтинг оценки места (1-5)"),
    place_review_crud: PlaceReviewCRUD = fastapi.Depends()
):
```
***
I _expect_ it should work like a list of query parameters. It works correctly when I pass some photos, but when I pass no photos I get this in terminal (send request in swagger)
```
Did not find CR at end of boundary (40)
```
And response code 400 with this response
```json
{
  "detail": "There was an error parsing the body"
}
```
***
I use postman and try sending the same request (with no photos) with `application/json` content type and I get
```json
{
    "detail": [
        {
            "loc": [
                "body",
                "photos"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
```
***
I change the argument signature to this:
```python
photos: list[bytes] = fastapi.File(None)
```
And it works with content type `application/json` and doesn't work with `multipart/form-data`. I also try it with `typing.Optional[list[bytes]]` and have same result

## Expected behavior
I want to pass `default_factory=list` in `fastapi.File` instead of `None` or something like this and expect that swagger will work with no files passed correctly.  I guess `multipart/form-data` assumes required content so I don't know my own best solution for this case

***

### Environment

* OS: macOS
* FastAPI Version: `0.65.2`:
* Python version: `3.9.2`

**Comment by deknowny** [comment]
Oh sorry if I reload the page I see `Send empty value` checkbox. That solves the issue

**Comment by deknowny** [comment]
But if I use this checkbox I get

```
Traceback (most recent call last):
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 390, in handle
    await self.app(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 206, in app
    solved_result = await solve_dependencies(
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 576, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 698, in request_body_to_args
    awaitables = [sub_value.read() for sub_value in value]
  File "/Users/an/Desktop/frisson-backend/.venv/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 698, in <listcomp>
    awaitables = [sub_value.read() for sub_value in value]
AttributeError: 'str' object has no attribute 'read'
```
