### ISSUE TITLE
fast-api can't load variable from main

### ISSUE THREAD

**Issue by heeda-namu** [tiangolo/fastapi#3553]
This is working global variable in Head.
but not working that in main

Why can't I call the main variable(global variable)?

```Python

#test2,py

import uvicorn
app = FastAPI()

global header_var
header_var="Head"

@app.get("/")
def read_root():
    return {"Code level 0 : "f'{header_var}' }

@app.get("/main")
def read_root():
    return {"Code level 0 : "f'{header_var}' , "main src: "f'{main_var}' }



if __name__=="__main__":

    global main_var
    main_var ="main"
    #server run
    app_str='test2:app'
    uvicorn.run(app_str, host='0.0.0.0', port=5000, reload=True, workers=5)
```

status code
"head"
INFO:     127.0.0.1:59650 - "GET /head HTTP/1.1" 200 OK

status code
"main"
INFO:     127.0.0.1:59686 - "GET /main HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/fastapi/routing.py", line 151, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/home/heeda/anaconda3/envs/namu_pt_py38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/heeda/workproject/namu/D-detect-engine/test2.py", line 14, in read_root
    return {"Code level 0 : "f'{header_var}' , "main src: "f'{main_var}' }
NameError: name 'main_var' is not defined

**Comment by uricholiveira** [comment]
I believe it's because of the order of precedence. You need to define global variables before functions. 

Since "app.get" is a function that has not been declared in "main", it is necessary to declare the variables first.

**Comment by codemation** [comment]
To add to @uricholiveira's point, you can understand what variables are "global" at any point in time by using the globals() built_in.

```
@app.get("/main")
def read_root():
    print(globals())
    return {"Code level 0 : "f'{header_var}' , "main src: "f'{main_var}' }
```
