### ISSUE TITLE
First time FastAPI with 500 Internal Server Error

### ISSUE THREAD

**Issue by dzungld** [tiangolo/fastapi#3640]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from sqlalchemy import Column, Integer, MetaData, String, Table, Text, text
from app.db.base_class import Base
from sqlalchemy.dialects.postgresql import UUID

metadata = Base.metadata


class User(Base):
    __tablename__ = "users"
    id = Column("id", UUID, primary_key=True, server_default=text("gen_random_uuid()"))
    user_name = Column("user_name", String, unique=True, index=True, nullable=False)
    full_name = Column("full_name", String)
    password = Column("password", String, nullable=False)
```

### Description

I just start to learn FastAPI and follow the code from: Full stack [Fastapi Postgresql](https://github.com/tiangolo/full-stack-fastapi-postgresql) to build my own backend api services. In my DB, I have only one table that created by:
`CREATE TABLE public.users ( id text COLLATE pg_catalog."default" NOT NULL, user_name character varying(100) COLLATE pg_catalog."default" NOT NULL, full_name character varying(100) COLLATE pg_catalog."default", password text COLLATE pg_catalog."default", CONSTRAINT users_pkey PRIMARY KEY (id) )`

Everything looks fine, I could start the service by when I access /api/v1/user, I get the 500 error. Could anyone help me to show where could I change to make this code run (My code is here: [https://github.com/dzungld/fastpro](https://github.com/dzungld/fastpro))

### Operating System

Windows

### Operating System Details

Windows 10

### FastAPI Version

0.67.0

### Python Version

3.9.6

### Additional Context

One more thing: Could anyone show me how to debug in Python (FastAPI) with VSCode. I just start learning Python some days.

**Comment by Dustyposa** [comment]
Can you past the error msg?

**Comment by Acerinth** [comment]
After a quick look, I cannot see anywhere that you defined a "/user" route (e.g. in your router in `users.py`), you just have a "/api/v1" prefix. Secondly, how exactly do you run the app? Can you post the exact error message you're getting?

**Comment by dzungld** [comment]
> After a quick look, I cannot see anywhere that you defined a "/user" route (e.g. in your router in `users.py`), you just have a "/api/v1" prefix. Secondly, how exactly do you run the app? Can you post the exact error message you're getting?

I defined "/user" in "app/api/v1/__init__.py":

`from fastapi import APIRouter
from app.api.v1 import movies, users

api_router = APIRouter()
api_router.include_router(movies.router, prefix="/movies", tags=["movies"])
api_router.include_router(users.router, prefix="/users", tags=["users"])`

and from main.py I included the router by:

`from app.api.v1 import api_router

app = FastAPI(title="FastPro - Project Management System")

app.include_router(api_router, prefix="/api/v1")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
`
I run the app with the command:

`uvicorn app.main:app --reload`

But when I access the api: http://127.0.0.1:8000/api/v1/users, I get the error in the browser: Internal Server Error

From the terminal, I got:

`INFO:     127.0.0.1:59517 - "GET /api/v1/users/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "f:\prj\fastpro\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "f:\prj\fastpro\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "f:\prj\fastpro\env\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "f:\prj\fastpro\env\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "f:\prj\fastpro\env\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "f:\prj\fastpro\env\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "f:\prj\fastpro\env\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "f:\prj\fastpro\env\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "f:\prj\fastpro\env\lib\site-packages\fastapi\routing.py", line 227, in app
    response_data = await serialize_response(
  File "f:\prj\fastpro\env\lib\site-packages\fastapi\routing.py", line 130, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for User
response -> 0
  value is not a valid dict (type=type_error.dict)`

**Comment by dzungld** [comment]
> After a quick look, I cannot see anywhere that you defined a "/user" route (e.g. in your router in `users.py`), you just have a "/api/v1" prefix. Secondly, how exactly do you run the app? Can you post the exact error message you're getting?

When I access the api: http://127.0.0.1:8000/api/v1/users, I get the error in the browser: Internal Server Error

From the terminal, I got:

INFO: 127.0.0.1:59517 - "GET /api/v1/users/ HTTP/1.1" 500 Internal Server Error ERROR: Exception in ASGI application Traceback (most recent call last): File "f:\prj\fastpro\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi result = await app(self.scope, self.receive, self.send) File "f:\prj\fastpro\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__ return await self.app(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\fastapi\applications.py", line 199, in __call__ await super().__call__(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\applications.py", line 112, in __call__ await self.middleware_stack(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__ raise exc from None File "f:\prj\fastpro\env\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__ await self.app(scope, receive, _send) File "f:\prj\fastpro\env\lib\site-packages\starlette\exceptions.py", line 82, in __call__ raise exc from None File "f:\prj\fastpro\env\lib\site-packages\starlette\exceptions.py", line 71, in __call__ await self.app(scope, receive, sender) File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 580, in __call__ await route.handle(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 241, in handle await self.app(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 52, in app response = await func(request) File "f:\prj\fastpro\env\lib\site-packages\fastapi\routing.py", line 227, in app response_data = await serialize_response( File "f:\prj\fastpro\env\lib\site-packages\fastapi\routing.py", line 130, in serialize_response raise ValidationError(errors, field.type_) pydantic.error_wrappers.ValidationError: 1 validation error for User response -> 0 value is not a valid dict (type=type_error.dict)

**Comment by dzungld** [comment]
> Can you past the error msg?

When I access the api: http://127.0.0.1:8000/api/v1/users, I get the error in the browser: Internal Server Error

From the terminal, I got:

INFO: 127.0.0.1:59517 - "GET /api/v1/users/ HTTP/1.1" 500 Internal Server Error ERROR: Exception in ASGI application Traceback (most recent call last): File "f:\prj\fastpro\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi result = await app(self.scope, self.receive, self.send) File "f:\prj\fastpro\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__ return await self.app(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\fastapi\applications.py", line 199, in __call__ await super().__call__(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\applications.py", line 112, in __call__ await self.middleware_stack(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__ raise exc from None File "f:\prj\fastpro\env\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__ await self.app(scope, receive, _send) File "f:\prj\fastpro\env\lib\site-packages\starlette\exceptions.py", line 82, in __call__ raise exc from None File "f:\prj\fastpro\env\lib\site-packages\starlette\exceptions.py", line 71, in __call__ await self.app(scope, receive, sender) File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 580, in __call__ await route.handle(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 241, in handle await self.app(scope, receive, send) File "f:\prj\fastpro\env\lib\site-packages\starlette\routing.py", line 52, in app response = await func(request) File "f:\prj\fastpro\env\lib\site-packages\fastapi\routing.py", line 227, in app response_data = await serialize_response( File "f:\prj\fastpro\env\lib\site-packages\fastapi\routing.py", line 130, in serialize_response raise ValidationError(errors, field.type_) pydantic.error_wrappers.ValidationError: 1 validation error for User response -> 0 value is not a valid dict (type=type_error.dict)

**Comment by Acerinth** [comment]
Okay. So, the main thing to notice here is that you have Pydantic validation error: `pydantic.error_wrappers.ValidationError: 1 validation error for User esponse -> 0 value is not a valid dict`. This means, that whatever your endpoint is returning is not in a valid format defined by Pydantic, in this case a dictionary. If you are using Pydantic to directly convert from ORM objects into a validated JSON object (dictionary), make sure to add the ORM mode to your User schema, like described here: https://pydantic-docs.helpmanual.io/usage/models/#orm-mode-aka-arbitrary-class-instances

In your case, I guess it would be something like:
```python
class UserIn(BaseModel):
    user_name: str
    full_name: str
    password: str
    
    class Config:
        orm_mode = True
```
