### ISSUE TITLE
typing.Optional[typing.Union[Typing.List[int], int]] fails for get query

### ISSUE THREAD

**Issue by fenchu** [tiangolo/fastapi#3661]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
#!/usr/bin/env/python3
from typing import Optional,List,Union
from fastapi import FastAPI, Query
app = FastAPI()
@app.get("/get")
async def myget(p:Optional[Union[List[int], int]]=Query(None)):
    print(f"pids:{p}")
    return p
```
```


### Description


gives when starting:
```
WARNING:  StatReload detected file change in 'bug.py'. Reloading...
Process SpawnProcess-19:
Traceback (most recent call last):
  File "C:\dist\python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\dist\python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\dist\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\server.py", line 57, in serve
    config.load()
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\config.py", line 318, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\importer.py", line 22, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\dist\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 851, in exec_module
  File "<frozen importlib._bootstrap_external>", line 988, in get_code
  File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\temp\.\bug.py", line 8
    async def myget(p:Optional[Union[List[int], int]=Query(None)):
                                                    ^
SyntaxError: invalid syntax
WARNING:  StatReload detected file change in 'bug.py'. Reloading...
WARNING:  StatReload detected file change in 'bug.py'. Reloading...
Process SpawnProcess-21:
Traceback (most recent call last):
  File "C:\dist\python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\dist\python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\dist\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\server.py", line 57, in serve
    config.load()
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\config.py", line 318, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\uvicorn\importer.py", line 22, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\dist\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\temp\.\bug.py", line 8, in <module>
    async def myget(p:Optional[Union[List[int], int]]=Query(None)):
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\fastapi\routing.py", line 575, in decorator
    self.add_api_route(
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\fastapi\routing.py", line 518, in add_api_route
    route = route_class(
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\fastapi\routing.py", line 400, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "c:\dist\venvs\gitlab-mobj-board\lib\site-packages\fastapi\dependencies\utils.py", line 331, in get_dependant
    assert isinstance(
AssertionError: Param: p can only be a request body, using Body(...)
```

if I change it to:
```
@app.get("/get")
async def myget(p:Optional[List[int]]=Query(None)):
    print(f"pids:{p}")
    return p
```
it works as intended:
```
curl.exe "http://127.0.0.1:8000/get?p=1351&p=1474&p=1485&p=1490&p=1494&p=1518"
[1351,1474,1485,1490,1494,1518]
```

### Operating System

Windows

### Operating System Details

_No response_

### FastAPI Version

0.68.0

### Python Version

3.9.5

### Additional Context

_No response_

**Comment by fenchu** [comment]
@SamuelHeath thanks for the feedback, I think mixing str and list of str may confuse openapi, so just using list of str is fine. and the first input is ['myinput'] is all fine.

**Comment by dmitrybabanovforreal** [comment]
I have the same issue.
GET endpoint with incoming parameter `data: Union[str, List[str]]` results in the following error if I pass a string to `data`:

```
422
Unprocessable Entity
{'detail': [{'loc': ['body', 'data'],
             'msg': 'field required',
             'type': 'value_error.missing'}]}
```

At the same time if I change the endpoint to POST and pass a string there it results in the following error:
```
422
Unprocessable Entity
{'detail': [{'loc': ['body', 'data'],
             'msg': 'str type expected',
             'type': 'type_error.str'},
            {'loc': ['body', 'data'],
             'msg': 'value is not a valid list',
             'type': 'type_error.list'}]}
```

I guess the only workaround for not is to accept only `List[str]`
