### ISSUE TITLE
FastAPI unable to return custom __root__ pydantic object - validation error

### ISSUE THREAD

**Issue by couling** [tiangolo/fastapi#3685]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Datamodel

class Inode(BaseModel):
    modified_time: datetime
    type: FileType
    mode: int
    size: int
    uid: int
    gid: int
    hash: Optional[str] = None


class Directory(BaseModel):
    __root__: Dict[str, Inode]

    @property
    def children(self):
        return self.__root__

    @children.setter
    def children(self, value: Dict[str, Inode]):
        self.__root__ = value


API
```python
@app.get(path="/get_dir/{ref}" response_model=spec.result_type)
async def get_directory(ref: str, session: ServerSession = Depends(cache.user_session)) -> http_protocol.GetDirectoryResponse:
    # This looks up ref and loads it from disk via pydantic's Directory.parse_file()
    result =  await session.get_directory(ref)
    # Breakpoint reaches here, so pydantic parsing the file is not the problem!
    return result
```

Error
```
Traceback (most recent call last):
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    response_data = await serialize_response(
  File "/Users/philip/Documents/Development/BackupServer/venv/lib/python3.8/site-packages/fastapi/routing.py", line 130, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 6 validation errors for Directory
response -> __root__ -> __root__ -> modified_time
  field required (type=value_error.missing)
response -> __root__ -> __root__ -> type
  field required (type=value_error.missing)
response -> __root__ -> __root__ -> mode
  field required (type=value_error.missing)
response -> __root__ -> __root__ -> size
  field required (type=value_error.missing)
response -> __root__ -> __root__ -> uid
  field required (type=value_error.missing)
response -> __root__ -> __root__ -> gid
  field required (type=value_error.missing)
```
```


### Description

I'm trying to return a pydantic object.  The objects are stored on disk as files containing json and are parsed into python objects using pydantic.  In theory the server could just return the file content and the http client wouldn't know the difference.  However in context the server needs to understand the content it's returning for other reasons.

When the code returns an object with a custom `__root__`, as shown above, FastAPI will choke on a validation error.  This is very odd because this object has already been exported to a file with `.json()` and parsed back with `parse_raw()` just fine.  I've checked in the debugger that’s  the pydantic object's own `.json()` method will still succeed (it does).

But after my code has returned the object FastAPI falls over...

If I change the datamodel so that `Directory` has `children: Dict[str, Inode]` instead of `__root__: Dict[str, Inode]` then the code will work.  But obviously that trips up the HTTP clients which were not expecting the wrapping dictionary.

### Operating System

macOS

### Operating System Details

_No response_

### FastAPI Version

0.68.0

### Python Version

3.8.5

### Additional Context

_No response_

**Comment by STeveShary** [comment]
@couling The simplest answer is to remove the reference to the `Directory` object and refer to it as a `Dict[str, Inode]`.  

If you modify your code to match below, this will return a 200, and will still define the schema: 
```
@app.get(path="/get_dir/{ref}" response_model=Dict[str, Inode])
async def get_directory(ref: str, session: ServerSession = Depends(cache.user_session)) -> Dict[str, Inode]:
    # This looks up ref and loads it from disk via pydantic's Directory.parse_file()
    result =  await session.get_directory(ref)
    # Breakpoint reaches here, so pydantic parsing the file is not the problem!
    return result.children
```

**Comment by couling** [comment]
@STeveShary I probably should have been clearer that this is reporting a bug.  

Your solution does work in context of the trivial example above, thanks. It's effectively abandoning Pydantic which I'm a little uncomfortable about.  It certainly won't fit with some of the other boiler plate code I've been using.
