### ISSUE TITLE
Static files broken

### ISSUE THREAD

**Issue by MLman99** [tiangolo/fastapi#376]
**Describe the bug**
I want to expose api endpoint from which I can download `static` directory. I get 2 unexpected behaviors:
1. When I want to reach my endpoint `0.0.0.0/static` I see ` No operations defined in spec! `
2. From tutorials(mentioned below) I understood it takes file from my app directory? Unless I copy it to root of my OS I get error `raise RuntimeError(f"Directory '{directory}' does not exist")`.

This is really important for my home project to make sense so any input is really appreciated because I'm stuck on this.

**To Reproduce**
Code:
```
from starlette.staticfiles import StaticFiles
from fastapi import FastAPI

app = FastAPI(title="static_api")
app.mount("/static", StaticFiles(directory="static"))
```

Dockerfile:
```
FROM python:3.7
RUN pip install aiofiles fastapi uvicorn python-multipart 
EXPOSE 80
COPY ./app /app
COPY ./static /static

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
```
I use `docker build -t myimage .` and `docker run -p 80:80 myimage`.

**Expected behavior**
Download static directory(or at least any file from this dir) from `0.0.0.0/static`

**Environment:**
Docker above.

**Already viewed and tried issues/tutorials**
https://fastapi.tiangolo.com/tutorial/static-files/
https://www.starlette.io/staticfiles/
https://github.com/tiangolo/fastapi/issues/130

**Comment by mschorcht** [comment]
Even if this answer comes a little late, maybe it helps others, because I got into the same problem in the beginning.

I am not sure if this is a bug either?
Because it's called static file and not static directory.

So you won't be able to request a folder, only a file, which has to be explicit.

`0.0.0.0/static/exisiting_file`

if you want to get files as folder you could zip your files to one file

0.0.0.0/static/exisiting_files.zip

If the error result is that the folder was not found, then a wrong specification must have happened. The following should run, if you want static inside you app-folder:

```
from starlette.staticfiles import StaticFiles
from fastapi import FastAPI

app = FastAPI(title="static_api")
app.mount("/static", StaticFiles(directory="app/static"))
```
So you don't need to copy the static folder in dockerfile additionaly.

**Comment by yaronv** [comment]
this works find on docker but when you try to run the main.py it says the folder does not exist

**Comment by dmontagu** [comment]
Can you share the full stack trace? In particular, is the error coming from `StaticFiles` or somewhere downstream?

If you are just getting `raise RuntimeError(f"Directory '{directory}' does not exist")` then this should be easy enough to solve by just getting the directory right. You might need to use an absolute path somewhere that you are currently using a relative path, or vice versa.

I would recommend trying to run in a debugger and investigating if you can figure out where it is looking / why it can't find the directory at the point where the error is occurring. If you ultimately find an inconsistency between the runtime behavior and the FastAPI and/or starlette docs, please let us know.

**Comment by yaronv** [comment]
Ok, Thanks, I understand the solution above.
It's just that It's annoying to use absolute path because the path is different between the local machine and the docker environment.
Never mind, I will use some configs for that.
Thanks!

**Comment by dmontagu** [comment]
@yaronv you can pass absolute paths without needing to actually hard code an absolute path by doing something like:
```python
from pathlib import Path

current_file = Path(__file__)
current_file_dir = current_file.parent
project_root = current_file_dir.parent
project_root_absolute = project_root.resolve()
static_root_absolute = project_root_absolute / "static"  # or wherever the static folder actually is
```
Obviously you can reduce the number of lines involved, I just made it more verbose to make it clear what was going on.

**Comment by tiangolo** [comment]
Thanks @dmontagu for the help here!

I think that should answer the question, right @MLman99 ?

**Comment by Zaffer** [comment]
I have the same issue. I am running this fullstack template (https://github.com/Zaffer/fastapi-fullstack) then trying to implement Jinja2 templating as per this page (https://fastapi.tiangolo.com/advanced/templates/). Code looks like this:

```
from typing import Any, List

from fastapi import APIRouter, Depends, HTTPException, FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from sqlalchemy.orm import Session

from app import crud, models, schemas
from app.api import deps

router = APIRouter()

router.mount("/static", StaticFiles(directory="static"), name="static")
```

The logs return the following:

```
backend_1       | Traceback (most recent call last):
backend_1       |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
backend_1       |     self.run()
backend_1       |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
backend_1       |     self._target(*self._args, **self._kwargs)
backend_1       |   File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
backend_1       |     target(sockets=sockets)
backend_1       |   File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 390, in run
backend_1       |     loop.run_until_complete(self.serve(sockets=sockets))
backend_1       |   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
backend_1       |   File "/usr/local/lib/python3.7/site-packages/uvicorn/main.py", line 397, in serve
backend_1       |     config.load()
backend_1       |   File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 278, in load
backend_1       |     self.loaded_app = import_from_string(self.app)
backend_1       |   File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
backend_1       |     module = importlib.import_module(module_str)
backend_1       |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
backend_1       |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1       |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
backend_1       |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
backend_1       |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
backend_1       |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
backend_1       |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
backend_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1       |   File "./app/main.py", line 4, in <module>
backend_1       |     from app.api.api_v1.api import api_router
backend_1       |   File "./app/api/api_v1/api.py", line 3, in <module>
backend_1       |     from app.api.api_v1.endpoints import items, login, users, utils, tests
backend_1       |   File "./app/api/api_v1/endpoints/tests.py", line 14, in <module>
backend_1       |     router.mount("/static", StaticFiles(directory="static"), name="static")
backend_1       |   File "/usr/local/lib/python3.7/site-packages/starlette/staticfiles.py", line 55, in __init__
backend_1       |     raise RuntimeError(f"Directory '{directory}' does not exist")
backend_1       | RuntimeError: Directory 'static' does not exist
```

the static folder is in the same directory as this python file.

Please help.

**Comment by Zaffer** [comment]
I figured it out by getting the correct path with:

```
from os import path

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

router = APIRouter()

path_str = path.dirname(path.realpath(__file__))
logger.info("relative path of static folder: %s", path_str)

router.mount("/static", StaticFiles(directory="/app/app/api/api_v1/endpoints/static"), name="static")

```

**Comment by Derhks** [comment]
I just had the same problem when I was doing unit testing and solved it as follows:

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

app.mount("/static", StaticFiles(directory=Path(BASE_DIR, 'static')), name="static")

**Comment by artemonsh** [comment]
The following line should work too 
`app.mount("/static", StaticFiles(directory="../static"), name="static")`

**Comment by Fayzan-Bhatti** [comment]
I have the same problem.

**Solution**
Replace your code: app.mount('/static', StaticFiles(directory='static'), name='static')
with blew code 

import os
app.mount('/static', StaticFiles(directory=os.path.join(current_dir, 'static')), name='static')
