### ISSUE TITLE
Pydantic - ValueError Raises Internal Server Error 

### ISSUE THREAD

**Issue by rajathn8** [tiangolo/fastapi#3761]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class GetInput(BaseModel):

    rank: Optional[int] = None
    interval: Optional[int] = None

    @validator("*")
    def check_range(cls, v):
        if v:
            if not 0 < v < 1000001:
                raise ValueError("Value Must be within range (0,1000000)")
            return v
```

### Description

-  This Throws an Internal Server Error when Input is out of Range for a ```GET Request``` 

- Can we customize the Model to Raise a ValueError with a Custom Status Code 
Example - ```raise ValueError(status_code=400, detail="Value Must be within range (0,1000000)")```

-  I know we can do this by raising an HTTPException like
```raise HTTPException(status_code=400, detail="Value Must be within range (0,1000000)")```

Log
```
INFO:     127.0.0.1:59427 - "GET /info/?rank=-1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/routing.py", line 195, in app
    dependency_overrides_provider=dependency_overrides_provider,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GetInput
rank
  ValueError() takes no keyword arguments (type=type_error)
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/routing.py", line 195, in app
    dependency_overrides_provider=dependency_overrides_provider,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GetInput
rank
  ValueError() takes no keyword arguments (type=type_error)
```

### Operating System

macOS

### Operating System Details

macOS 11.4

### FastAPI Version

0.68.1

### Python Version

Python 3.7.7

### Additional Context

I posted the question on StackOverflow - https://stackoverflow.com/questions/68914523/pydantic-value-error-raises-internal-server-error

I did find a few questions on GitHub for the same but No clear answer was available.

Thank you for taking a look in advance.

**Comment by Acerinth** [comment]
Hey there,

To me, this looks more like you have a bug in your code somewhere --> explained here: https://fastapi.tiangolo.com/tutorial/handling-errors/?h=validation#requestvalidationerror-vs-validationerror

> FastAPI uses it so that, if you use a Pydantic model in response_model, and your data has an error, you will see the error in your log.
But the client/user will not see it. Instead, the client will receive an "Internal Server Error" with a HTTP status code 500.
It should be this way because if you have a Pydantic ValidationError in your response or anywhere in your code (not in the client's request), it's actually a bug in your code.

Maybe you could start with changing your validator name. Instead of 
```
@validator("*")
```

try with

```
@validator("my_validator")
```

More on validators you can read on Pydantic docs: https://pydantic-docs.helpmanual.io/usage/validators/

Hope this helps.

**Comment by rajathn8** [comment]
So what I tried to do is remove the Interval attribute from the Code.

```
class RankInput(BaseModel):
    """
    Get Rank Input class
    """

    rank: int

    @validator('rank')
    def check_if_value_in_range(cls, v):
        """
        check if input rank is within range
        """
        if not 0 < v < 1000001:

            raise ValueError("Rank Value Must be within range (0,1000000)")
        return v

```

the Code still ran into ```internal server error``` when a negative input was passed.

**Comment by rajathn8** [comment]
Also this is the Controller Calling the Model

```
@router.get('/rank/{rank}',status_code=200)
def get_info_by_rank(value: RankInput = Depends()):

    result = get_by_rank(value.rank)

    return result
```

**Comment by rajathn8** [comment]
> Hey there,
> 
> To me, this looks more like you have a bug in your code somewhere --> explained here: https://fastapi.tiangolo.com/tutorial/handling-errors/?h=validation#requestvalidationerror-vs-validationerror
> 
> > FastAPI uses it so that, if you use a Pydantic model in response_model, and your data has an error, you will see the error in your log.
> > But the client/user will not see it. Instead, the client will receive an "Internal Server Error" with a HTTP status code 500.
> > It should be this way because if you have a Pydantic ValidationError in your response or anywhere in your code (not in the client's request), it's actually a bug in your code.
> 
> Edit: This is because Pydantic validates your data both coming "in" and "out" of your application. So if data coming from your app doesn't validate through Pydantic, you will get `500 Internal Server Error`.
> 
> I can see you're trying to validate everything at once. Maybe you could try firstly validating only one attribute.
> 
> ```
> @validator("rank")
> ```
> 
> or
> 
> ```
> @validator("interval")
> ```
> 
> More on validators you can read on Pydantic docs: https://pydantic-docs.helpmanual.io/usage/validators/
> 
> Hope this helps.

I removed the interval attribute. Check Above. Still Face the same Issue when a negative value is sent

**Comment by johnraz** [comment]
I can confirm that I'm facing the exact same issue and that https://github.com/tiangolo/fastapi/issues/1474#issuecomment-803021344 fixes it but is definitely not nice.

**Comment by MarkusSintonen** [comment]
> I can confirm that I'm facing the exact same issue and that https://github.com/tiangolo/fastapi/issues/1474#issuecomment-803021344 fixes it but is definitely not nice.

Gave another suggestion there https://github.com/tiangolo/fastapi/issues/1474#issuecomment-1049987786 which seems to also work.
