### ISSUE TITLE
Can't pass Cyrillic custom header in starlette response through uvicorn

### ISSUE THREAD

**Issue by soldakos** [tiangolo/fastapi#3763]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import Response
@app.get('/customCyrillicHeader')
def test(resp: Response):
    resp.headers['X-API-Code'] = "Это киррилица, бро"
    return 'ok'
```

### Description

- ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\fastapi\routing.py", line 220, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\fastapi\routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Projects\RecalcAPIfast\app\main.py", line 18, in test
    resp.headers['X-API-Code'] = "Это киррилица, бро"
  File "D:\Projects\RecalcAPIfast\venv\lib\site-packages\starlette\datastructures.py", line 585, in __setitem__
    set_value = value.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

### Operating System

Linux, Windows

### FastAPI Version

0.68.0

### Python Version

3.7.4

**Comment by soldakos** [comment]
I know that is HTTP rules (historically headers in  ISO-8859-1), but why not in base64 by default like in django rest framework: Response(data=data, status=status, headers={'X-API-Code': any string})?

**Comment by soldakos** [comment]
Got it! encode to utf-8, then to base64 and decode from base64 
ru.stackoverflow.com/a/1321108/458186
