### ISSUE TITLE
Pydantic ValidationError: 1 validation error for Departmen Create

### ISSUE THREAD

**Issue by arkryonia** [tiangolo/fastapi#3858]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# Model

from sqlalchemy import Column, Integer, String

from utils.database import Base


class Department(Base):
    __tablename__="departments"

    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True, index=True)

# Schema
from pydantic import BaseModel

class DepartmentBase(BaseModel):
    name: str

class DepartmentCreate(DepartmentBase):
    pass

class Department(DepartmentBase):
    id: int

    class Config:
        orm_mode: True

# Locale Main
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from api.departments import models, schemas
from utils.database import engine, get_db

models.Base.metadata.create_all(bind=engine)

department_route = APIRouter()

@department_route.get('/', response_model=List[schemas.Department])
def get_all_departments(db: Session = Depends(get_db)):
    return db.query(models.Department).all()

@department_route.post('/', response_model=schemas.DepartmentCreate)
def create(payload: schemas.DepartmentCreate, db: Session = Depends(get_db)):
    new_dep = models.Department(name = payload.name)
    db.add(new_dep)
    db.commit()
    db.refresh(new_dep)
    db.close()
    return new_dep

# Global Main
import uvicorn
from fastapi import FastAPI

from api.departments.main import department_route

app = FastAPI()

app.include_router(department_route, prefix='/v1/departments', tags=['Departments'])

@app.get('/')
def index():
    return {"Message": "Welcome to xenic API"}

if __name__ == '__main__':
    uvicorn.run('main:app', reload=True)
```

### Description

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/fastapi/routing.py", line 234, in app
    response_data = await serialize_response(
  File "/home/nujenlodo/Documents/Forge/Sandbox/xenic/venv/lib/python3.9/site-packages/fastapi/routing.py", line 137, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for DepartmentCreate
response
  value is not a valid dict (type=type_error.dict)

### Operating System

Linux

### FastAPI Version

0.68.1

### Python Version

3.9.2

### Additional Context
When I remove response_model from the operations every goes well. 

The error is belonged to Pydantic. I followed the tutorial and still having error.

_No response_

**Comment by arkryonia** [comment]
It is ok for me.

I set as orm_mode: True instead as orm_mode =True
