### ISSUE TITLE
Fastapi with wss and https, setup successful but cannot communicate

### ISSUE THREAD

**Issue by javismiles** [tiangolo/fastapi#4152]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Frontend:
  const serverIP = "x.x.x.x";
  const apiPort = "8000";
  const serverURL = `wss://${serverIP}:${apiPort}/wss`;
  etc

Backend:
@app.websocket("/wss")
async def websocket_endpoint(websocket: WebSocket, ):
etc..
```

### Description

Good day,

a) we have setup our react and fast api project in a server running nginx.
b) And we setup a Letsencrypt certificate successfully as well.
c) We can run the frontend with https successfully.
d) And we can execute the uvicorn-fastapi server app with https as well successfully using:
gunicorn --certfile=/etc/letsencrypt/archive/ourdomain.co/fullchain1.pem --keyfile=/etc/letsencrypt/archive/ourdomain.co/privkey1.pem server_deploy:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

e) the frontend is making calls to:
  const serverIP = "server ip";
  const apiPort = "8000";
  const serverURL = `wss://${serverIP}:${apiPort}/wss`;

f) and unfortunately the server is accepting the call, and is showing these errors:

[2021-11-05 21:41:10 +0000] [2404] [WARNING] Invalid HTTP request received.
Traceback (most recent call last):
etc, etc
  File "/home/ubuntu/anaconda3/envs/mvp/lib/python3.7/site-packages/h11/_util.py", line 76, in 
etc, etc
  File "/home/ubuntu/anaconda3/envs/mvp/lib/python3.7/site-packages/h11/_util.py", line 88, in validate
    raise LocalProtocolError(msg)
h11._util.RemoteProtocolError: illegal request line: bytearray(b'OPTIONS sip:nm SIP/2.0')

any tips?
the frontend is calling with wss, and from a https:// secure react frontend

thank you :)

### Operating System

Linux

### FastAPI Version

0.70.0

### Python Version

3.7.9

**Comment by javismiles** [comment]
update, changing the  WSS Call , from using the IP address, to using the domain name, seems to fix it
