### ISSUE TITLE
Unexpected ValidationError with accessing /openapi.json when some model uses typing.Tuple

### ISSUE THREAD

**Issue by frodo821** [tiangolo/fastapi#4168]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from pydantic import BaseModel
from fastapi import FastAPI

from typing import Tuple

class FooModel(BaseModel):
  prop: Tuple[int, str]


app = FastAPI()

@app.get('/', response_model=FooModel)
def get_foo():
 return {"prop": (0, 'ok')}

print(app.openapi())
```

## Summary
The above code must be failed with a ValidationError like this:
```
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    a()
  File "<pyshell#1>", line 17, in a
    print(app.openapi())
  File "/usr/local/lib/python39/lib/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "/usr/local/lib/python39/lib/site-packages/fastapi/openapi/utils.py", line 410, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for OpenAPI
components -> schemas -> FooModel -> properties -> prop -> items
  value is not a valid dict (type=type_error.dict)
components -> schemas -> FooModel -> $ref
  field required (type=value_error.missing)
```

in fastapi.openapi.models in line 103~142

```python
class Schema(BaseModel):
    ref: Optional[str] = Field(None, alias="$ref")
    title: Optional[str] = None
    multipleOf: Optional[float] = None
    maximum: Optional[float] = None
    exclusiveMaximum: Optional[float] = None
    minimum: Optional[float] = None
    exclusiveMinimum: Optional[float] = None
    maxLength: Optional[int] = Field(None, gte=0)
    minLength: Optional[int] = Field(None, gte=0)
    pattern: Optional[str] = None
    maxItems: Optional[int] = Field(None, gte=0)
    minItems: Optional[int] = Field(None, gte=0)
    uniqueItems: Optional[bool] = None
    maxProperties: Optional[int] = Field(None, gte=0)
    minProperties: Optional[int] = Field(None, gte=0)
    required: Optional[List[str]] = None
    enum: Optional[List[Any]] = None
    type: Optional[str] = None
    allOf: Optional[List["Schema"]] = None
    oneOf: Optional[List["Schema"]] = None
    anyOf: Optional[List["Schema"]] = None
    not_: Optional["Schema"] = Field(None, alias="not")
    items: Optional["Schema"] = None
    properties: Optional[Dict[str, "Schema"]] = None
    additionalProperties: Optional[Union["Schema", Reference, bool]] = None
    description: Optional[str] = None
    format: Optional[str] = None
    default: Optional[Any] = None
    nullable: Optional[bool] = None
    discriminator: Optional[Discriminator] = None
    readOnly: Optional[bool] = None
    writeOnly: Optional[bool] = None
    xml: Optional[XML] = None
    externalDocs: Optional[ExternalDocumentation] = None
    example: Optional[Any] = None
    deprecated: Optional[bool] = None

    class Config:
        extra: str = "allow"
```

It seems `Schema.items` should accept an array of schemas according to the JSON schema spec, but only the type `Schema` is allowed in the current code.

### Operating System

Linux, Windows

### FastAPI Version

0.70.0

### Python Version

Python 3.9.5

**Comment by oligond** [comment]
nitp - Your sample code has a small issue that might confuse people, so you probably want to fix that for posteriority:

The return value of your sample route is an array, but, according to the model declaration, it's supposed to be a dict containing a `prop` key which has a tuple of (int, str) as value:

 ```python
@app.get('/', response_model=FooModel)
def get_foo():
  return {"prop": (0, 'ok')}
```

**Comment by frodo821** [comment]
@oligond 
It's not essential because `openapi()` succeeds and returns the OpenAPI scheme even though the handler always returns None or other invalid values.
But sorry for my mistake. I'd fixed it, and thank you for advising me! 😄

**Comment by HansBrende** [comment]
+1! Also, duplicate of #3665, #3686, #3782, and #3898 (the list is growing!)

**Comment by tiangolo** [comment]
It seems this is a duplicate of https://github.com/tiangolo/fastapi/issues/3665

In short, it should be fixed by FastAPI `0.73.0`, released in the next hours. :tada: 

For more info, read the last comment in that issue: https://github.com/tiangolo/fastapi/issues/3665#issuecomment-1019579214

And the comment in the PR: https://github.com/tiangolo/fastapi/pull/3874#issuecomment-1019578028
