### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by iglimanaj** [tiangolo/fastapi#4210]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
RuntimeError: dictionary changed size during iteration    
for key, value in obj.items():
  File "/usr/local/lib/python3.7/site-packages/fastapi/encoders.py", line 70, in jsonable_encoder
    sqlalchemy_safe=sqlalchemy_safe,
  File "/usr/local/lib/python3.7/site-packages/fastapi/encoders.py", line 94, in jsonable_encoder
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 124, in serialize_response
    is_coroutine=is_coroutine,
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 205, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 190, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
Traceback (most recent call last):
ERROR:    Exception in ASGI application
```
```


### Description

The error is occurring rarely and I couldn't identify any patterns. When I resent the same request, after a few seconds to the server the error didn't appear.

### Operating System

Linux

### Operating System Details

_No response_

### FastAPI Version

0.62.0

### Python Version

Python 3.7.6

### Additional Context

_No response_

**Comment by ondrejkajinek** [comment]
This is not related to fastapi but to python itself. You iterate over dict and change it in the loop. Something like 

```
xx = {"a": 10, "b": 20}
for key in xx.keys():  # you iterate over the dict
  if key == "a":
    xx.pop(key)  # now you change the dict, possibly breaking the keys iterator
```

If you need to modify the dict (add or delete any key), you have to iterate over copy of the iterated container / dict, as follows:

```
for key in list(xx.keys()):  # this takes copy of keys so it won't change during iteration
  if key == "a":
    xx.pop(key)
```

**Comment by iglimanaj** [comment]
@ondrejkajinek It's not my code causing the error. The problem lies more low level in fastapi `File "/usr/local/lib/python3.7/site-packages/fastapi/encoders.py", line 70, in jsonable_encoder`

**Comment by ondrejkajinek** [comment]
Yes, line 70 is the loop where you iterate over the dict, but inside the loop there is no dict modification, only key and value encoding and those encoded values are pushed to resulting dict.

I'm suspecting your code to contain some custom json serializer that modify the value. Can you check if this is not the case?

But those are just guesses.

**Comment by iglimanaj** [comment]
Nope, I don't have any custom json serializer in my code.

**Comment by ondrejkajinek** [comment]
Could you please provide MWE that causes the error?

**Comment by iglimanaj** [comment]
@ondrejkajinek I don't have enough context, cause the error traceback doesn't point to any part of my code. :sweat_smile:
