### ISSUE TITLE
RuntimeError: Response content shorter than Content-Length

### ISSUE THREAD

**Issue by solyarisoftware** [tiangolo/fastapi#4214]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# https://fastapi.tiangolo.com/advanced/custom-response/

from fastapi import FastAPI
from fastapi.responses import FileResponse
from tts import text_to_speech

app = FastAPI()

# server.py
@app.get('/tts/')
def download_tts_file(id: str, lang: str, text: str):

    # debug
    print('id: ', id)
    print('lang: ', lang)
    print('text: ', text)

    # create the speech file
    file = f'{id}.mp3'
    text_to_speech(text, lang, file)

    return FileResponse(file)

---

# tts.py
# pip install gTTS
# https://gtts.readthedocs.io/en/latest/module.html
import time
from gtts import gTTS

def text_to_speech(text, lang, file):

    tts = gTTS(text, lang=lang)
    tts.save(file)

---

#!/usr/bin/bash
# client.sh
language_code="it"
text="Ciao! Mi chiamo Giorgio Robino."

# https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command
url_encoded_text=$(python3 -c "import urllib.parse; print (urllib.parse.quote('''$text'''))")

id="0123456789"
file="$id.mp3"

url="127.0.0.1"
port=8000
query_string="id=$id&lang=$language_code&text=$url_encoded_text"

curl \
  --silent \
  -H "Accept: audio/mp3" \
  -X GET \
  http://$url:$port/tts/?$query_string \
  --output $file

---

#!/usr/bin/bash
# server
uvicorn server:app --reload &
```

### Description

When I run the client, the server crashes.
I guess the issue is related to the `FileResponse(file)` and it happens when I send a file generated by function `text_to_speech(text, lang, file)`

```
$ client.sh
id:  0123456789
lang:  it
text:  Ciao! Mi chiamo Giorgio Robino, sono italiano e vivo a Genova.
INFO:     127.0.0.1:58756 - "GET /tts/?id=0123456789&lang=it&text=Ciao%21%20Mi%20chiamo%20Giorgio%20Robino%2C%20sono%20italiano%20e%20vivo%20a%20Genova. HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/giorgio/.local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/responses.py", line 305, in __call__
    await send(
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/home/giorgio/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/home/giorgio/.local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 512, in send
    raise RuntimeError("Response content shorter than Content-Length")
RuntimeError: Response content shorter than Content-Length
```

### Operating System

Linux

### FastAPI Version

0.70.0

### Python Version

3.8.10

**Comment by solyarisoftware** [comment]
I'm guilty.

the issue happened because the client write the same file the server serving... :(

solution: 

In server I changed the line:

file = f'{id}.mp3'

with the line

file = f'{id}S.mp3'
