### ISSUE TITLE
An error about annotations in __future__ annotations

### ISSUE THREAD

**Issue by luolingchun** [tiangolo/fastapi#4262]
### First Check

- [x] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# test_fastapi.py
from __future__ import annotations

from typing import Optional

import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel

from jwt_tools import login_required

app = FastAPI()


class Item(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    tax: Optional[float] = None


@app.post("/items/", summary='asdfsa')
@login_required
def create_item(item: Item):
    return item


if __name__ == '__main__':
    uvicorn.run(app="test_fastapi:app", host="0.0.0.0", port=8000, debug=True, reload=True)
```

### Description

i'm using `__future__ annotations` and i got an error about annotations.

```python
# jwt_tools.py
from functools import wraps


def login_required(func):

    @wraps(func)
    def wrapper(*args, **kwargs):
        print('login')
        return func(*args, **kwargs)

    return wrapper
```

error ouput:
```python
"C:\Program Files\Python38\python.exe" D:/workspace/test/test_fastapi.py
Traceback (most recent call last):
  File "D:/workspace/test/test_fastapi.py", line 26, in <module>
    def create_item(item: Item):
  File "C:\Program Files\Python38\lib\site-packages\fastapi\routing.py", line 582, in decorator
    self.add_api_route(
  File "C:\Program Files\Python38\lib\site-packages\fastapi\routing.py", line 525, in add_api_route
    route = route_class(
  File "C:\Program Files\Python38\lib\site-packages\fastapi\routing.py", line 407, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "C:\Program Files\Python38\lib\site-packages\fastapi\dependencies\utils.py", line 278, in get_dependant
    endpoint_signature = get_typed_signature(call)
  File "C:\Program Files\Python38\lib\site-packages\fastapi\dependencies\utils.py", line 248, in get_typed_signature
    typed_params = [
  File "C:\Program Files\Python38\lib\site-packages\fastapi\dependencies\utils.py", line 253, in <listcomp>
    annotation=get_typed_annotation(param, globalns),
  File "C:\Program Files\Python38\lib\site-packages\fastapi\dependencies\utils.py", line 265, in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
  File "C:\Users\llc\AppData\Roaming\Python\Python38\site-packages\pydantic\typing.py", line 54, in evaluate_forwardref
    return type_._evaluate(globalns, localns)
  File "C:\Program Files\Python38\lib\typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Item' is not defined
```

and i read the souce code https://github.com/tiangolo/fastapi/blob/0.70.0/fastapi/dependencies/utils.py#L247 :
```python
...
def get_typed_signature(call: Callable[..., Any]) -> inspect.Signature:
    signature = inspect.signature(call)
    globalns = getattr(call, "__globals__", {})
    typed_params = [
        inspect.Parameter(
            name=param.name,
            kind=param.kind,
            default=param.default,
            annotation=get_typed_annotation(param, globalns),
        )
        for param in signature.parameters.values()
    ]
    typed_signature = inspect.Signature(typed_params)
    return typed_signature
...

def get_typed_annotation(param: inspect.Parameter, globalns: Dict[str, Any]) -> Any:
    annotation = param.annotation
    if isinstance(annotation, str):
        annotation = ForwardRef(annotation)
        annotation = evaluate_forwardref(annotation, globalns, globalns)
    return annotation

...


```
`@login_required` is decorated by `@app`, as a result `globalns = getattr(call, "__globals__", {})` not included `Item` and `annotation` is `str` in `__future__ annotations` environment.

So what should I do？

### Operating System

Windows

### Operating System Details

windows 10

### FastAPI Version

0.70.0

### Python Version

3.8.5

**Comment by waweber** [comment]
This doesn't directly solve your problem, but instead of using a decorator, you could add a dependency to check the logged in user:

```
def get_logged_in_user(req: Request) -> User:
    """Get the logged in user info, otherwise raise 401 unauthorized"""
    # get session from cookie, or Bearer Token
    # maybe even the built-in http auth basic stuff, https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/
    user: Optional[User] = get_user(req)
    if not user:
        raise HTTPException(401)
    return user

@app.post("...")  # could also put Depends in dependencies=[] here if you don't need the user object
def create_item(item: Item, user: User = Depends(get_logged_in_user)):
    ...
```

I think this probably the preferred way to do it, even

**Comment by luolingchun** [comment]
Thanks. I added to my project `__extra_globals__` attribute. It's not a good idea, but it works.

```python
...

func_globals = getattr(call, "__globals__", {})
func_globals.update(**getattr(func, '__extra_globals__', {}))

...
```

```python
# jwt_tools.py
from functools import wraps


def login_required(func):

    @wraps(func)
    def wrapper(*args, **kwargs):
        print('login')
        return func(*args, **kwargs)
    
    # copy __globals__
    wrapper.__extra_globals__ = getattr(func, '__globals__', {})
    wrapper.__extra_globals__.update(**getattr(func, "__extra_globals__", {}))

    return wrapper
```
