### ISSUE TITLE
Error when I try to use /redoc or /docs

### ISSUE THREAD

**Issue by Pedro12007** [tiangolo/fastapi#4273]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
INFO:     127.0.0.1:56616 - "GET /redoc HTTP/1.1" 200 OK
INFO:     127.0.0.1:56616 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 387, in get_openapi
    definitions = get_model_definitions(
  File "/home/pedro/Documentos/fastapi/venv/lib/python3.8/site-packages/fastapi/utils.py", line 24, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 234, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 202, in pydantic.schema.get_field_info_schema
  File "pydantic/schema.py", line 893, in genexpr
  File "pydantic/schema.py", line 893, in genexpr
  File "pydantic/schema.py", line 899, in pydantic.schema.encode_default
  File "pydantic/json.py", line 95, in pydantic.json.pydantic_encoder
TypeError: Object of type 'FieldInfo' is not JSON serializable
```

### Operating System

Linux

### Operating System Details

Kubuntu 20.04.3 LTS

### FastAPI Version

0.70.0

### Python Version

Python 3.8.10

### Additional Context

![image](https://user-images.githubusercontent.com/71617826/145700118-bce3d066-7191-48ef-8565-b1e3ecbccd43.png)

**Comment by insomnes** [comment]
```
TypeError: Object of type 'FieldInfo' is not JSON serializable
```
Do you have this type in any of your models? 
Without reproducable app code it's hard to say what is wrong.

**Comment by Pedro12007** [comment]
Thank you, I find the error in 1 model.

**Comment by insomnes** [comment]
@Pedro12007 cool! If problem is solved, can you please close the issue?

**Comment by Pedro12007** [comment]
Ok!!
