### ISSUE TITLE
how to automactically restart `uvicorn main:app --reload` after `Stopping reloader process `, `SyntaxError: invalid syntax`

### ISSUE THREAD

**Issue by boojongmin** [tiangolo/fastapi#4348]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/boojongmin/study/src/./main.py", line 129
    async def update_item(    item_id: int, item: Item, user: User, importance: int = Body(...):
                                                                                               ^
SyntaxError: invalid syntax


---------------------------------------------------------------------------


Process SpawnProcess-11:
Traceback (most recent call last):
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/config.py", line 456, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/boojongmin/study/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/boojongmin/.pyenv/versions/3.10.1/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/boojongmin/study/src/./main.py", line 70, in <module>
    class Item(BaseModel):
  File "/home/boojongmin/study/src/./main.py", line 76, in Item
    image: Optional[Image] = NOne
NameError: name 'NOne' is not defined
INFO:     Stopping reloader process [8115]
```

### Description

I want to restart `uvicorn main:app` when process stoped after syntax error without manually run command.
How I do that?
thatnk you :) 

### Operating System

Windows

### Operating System Details

wsl2 Ubuntu 20.04.3 LTS in windows 10

### FastAPI Version

0.70.1

### Python Version

Python 3.10.1

**Comment by harunyasar** [comment]
I believe this is not an issue directly relevant to FastAPI. It is something that needs to be provided by `uvicorn`. There is an opened issue [here](https://github.com/encode/uvicorn/issues/1295) .
