### ISSUE TITLE
Union of multiple response classes don't allow for openapi.json creation

### ISSUE THREAD

**Issue by jeliashi** [tiangolo/fastapi#4382]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Union

from fastapi import Depends, FastAPI, Query
from fastapi.responses import Response
from pydantic.dataclasses import dataclass

@dataclass
class Request:
    format: str = Query("json", regex="(^json$|^custom$)")

class JsonResponseModel(Response):
    media_type = "application/json"
    def render(self, content)-> bytes:
        return "{\"data\": \"I am json\"}".encode("utf-8")

class CustomResponseModel(Response):
    media_type = "application/octet-stream"
    def render(self, contet) -> bytes:
        return b"I am custom"

app = FastAPI()

@app.get("/", response_class=Union[JsonResponseModel, CustomResponseModel])
def base(params: Request = Depends()):
    if params.format == 'json':
        return JsonResponseModel()
    return CustomResponseModel()
```

### Description

I'm trying to generate the openapi documentation for an app that can have multiple response models for 200 codes.
The endpoints are working as expected: ```
$ curl http://localhost:8000/
{"data": "I am json"}%
$ curl http://localhost:8000/\?format\=json
{"data": "I am json"}%
$ curl http://localhost:8000/\?format\=other
{"detail":[{"loc":["query","format"],"msg":"string does not match regex \"(^json$|^custom$)\"","type":"value_error.str.regex","ctx":{"pattern":"(^json$|^custom$)"}}]}%
$ curl http://localhost:8000/\?format\=custom
I am custom%```

BUT! When I try to generate the openapi documentation for this (using `curl http://localhost:8000/openapi.json`) I get the following:
```
INFO:     127.0.0.1:51703 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/path/to/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/path/to/venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/path/to/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/path/to/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/path/to/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/path/to/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/path/to/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/path/to/venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/path/to/venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/path/to/venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/path/to/venv/lib/python3.8/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/path/to/venv/lib/python3.8/site-packages/fastapi/applications.py", line 136, in openapi
    self.openapi_schema = get_openapi(
  File "/path/to/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 392, in get_openapi
    result = get_openapi_path(route=route, model_name_map=model_name_map)
  File "/path/to/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 181, in get_openapi_path
    route_response_media_type: Optional[str] = current_response_class.media_type
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py", line 759, in __getattr__
    return getattr(self.__origin__, attr)
AttributeError: '_SpecialForm' object has no attribute 'media_type'

```

### Operating System

macOS

### FastAPI Version

0.68.1

### Python Version

Python 3.8.11

**Comment by firattamur** [comment]
Hello,

I was getting same error and after debugging for an hour then I realized that I was using response_class instead of response_model in @app.get() function. After I solved my problem, I wanted to check yours and if you make changes below it works. I think the problem is same with mine, using response_class causes issue.

```python
from typing import Union

from fastapi import Depends, FastAPI, Query
from fastapi.responses import Response
from pydantic import BaseModel                           # I used BaseModel instead of Response
from pydantic.dataclasses import dataclass


@dataclass
class Request:
    format: str = Query("json", regex="(^json$|^custom$)")


class JsonResponseModel(BaseModel):
    media_type = "application/json"

    def render(self, content) -> bytes:
        return '{"data": "I am json"}'.encode("utf-8")


class CustomResponseModel(BaseModel):
    media_type = "application/octet-stream"

    def render(self, contet) -> bytes:
        return b"I am custom"


app = FastAPI()


# I changed response_class to response_model
@app.get("/", response_model=Union[JsonResponseModel, CustomResponseModel])
def base(params: Request = Depends()):
    if params.format == "json":
        return JsonResponseModel()
    return CustomResponseModel()
```
