### ISSUE TITLE
FileNotFoundError when building docs.py

### ISSUE THREAD

**Issue by rogerbrinkmann** [tiangolo/fastapi#4521]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
The problem can be reproduced by running the command:
`python ./scripts/docs.py build-all`
```

### Description

When running the above command the following output occurs (part)

Building docs for: sq
Building docs for: uk
Building docs for: zh
WARNING:mkdocs.structure.nav:A relative path to 'index.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING:mkdocs.structure.pages:Documentation file 'deployment\docker.md' contains a link to 'deployment\tutorial\bigger-applications.md' which is not found in the documentation files.
ERROR:mdx_include-1.4.1:E: Could not find file: ..\..\docs_src\app_testing\main_b.py
Traceback (most recent call last):
  File "C:\Users\roger\source\fastapi\env\lib\site-packages\mdx_include\mdx_include.py", line 75, in get_local_content_list
    with open(filename, 'r', encoding=encoding) as f:
  File "C:\Program Files\Python39\lib\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\docs_src\\app_testing\\main_b.py'
ERROR:mdx_include-1.4.1:E: Could not find file: ..\..\docs_src\app_testing\test_main_b.py
Traceback (most recent call last):
  File "C:\Users\roger\source\fastapi\env\lib\site-packages\mdx_include\mdx_include.py", line 75, in get_local_content_list
    with open(filename, 'r', encoding=encoding) as f:
  File "C:\Program Files\Python39\lib\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\docs_src\\app_testing\\test_main_b.py'
WARNING:mkdocs.structure.pages:Documentation file 'tutorial\security\first-steps.md' contains a link to 'tutorial\security\...\advanced\behind-a-proxy.md' which is 
not found in the documentation files.
Successfully built docs for: zh
Successfully built docs for: sq
Successfully built docs for: es

### Operating System

Windows

### FastAPI Version

0.73.0

### Python Version

Python 3.9.4

### Additional Context

Some of the Japanese translations contain incorrect links.
I'd be happy to provide a PR for fixing the issue.

**Comment by rogerbrinkmann** [comment]
I'd like to propose this PR as solution for the issue: #4522
