### ISSUE TITLE
Raising an FastAPI `HTTPException` results in an Internal Server Error regardless of the supplied status code or content

### ISSUE THREAD

**Issue by j-suchard** [tiangolo/fastapi#4653]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI, Request, Path, HTTPException

geo_data_rest = FastAPI()

@geo_data_rest.middleware('http')
async def check_user_scope(request, call_next):
    # Check if the headers contain the 'Authorization' header
    _authorization_header: Optional[str] = request.headers.get('Authorization', None)
    if _authorization_header is None:
        _logger.warning('%s:%s - %s - The request did not contain a "Authorization" header. [REJECTED REQUEST]',
                        request.client.host, request.client.port, _req_id)
        raise HTTPException(
            status_code=400,
            detail={
                "error": "missing_authorization_header"
            }
        )
    response = await call_next(request)
    return response

@geo_data_rest.get(
    path='/{layer_name}/{layer_resolution}',
    status_code=200
)
async def get_layer(
        layer_name: str = Path(default=..., title='Name of the Layer'),
        layer_resolution: str = Path(default=..., title='Resolution of the Layer')
):
    # Get the configuration of the requested layer, if it exits
    return "Sending layer"
```

### Description

* Open the browser and make a call to `/test/test`
* It returns an Internal Server Error (500) since the HTTPException is not handled by FastAPI or Starlette
  <details>
    <summary>Click to see stacktrace</summary>

  ```stacktrace
    ERROR    | 2022-03-05 15:33:20,921 | uvicorn.error | Exception in ASGI application
  Traceback (most recent call last):
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
      result = await app(self.scope, self.receive, self.send)
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
      return await self.app(scope, receive, send)
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\venv\lib\site-packages\fastapi\applications.py", line 259, in __call__
      await super().__call__(scope, receive, send)
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
      await self.middleware_stack(scope, receive, send)
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
      raise exc
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
      await self.app(scope, receive, _send)
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\venv\lib\site-packages\starlette\middleware\base.py", line 63, in __call__
      response = await self.dispatch_func(request, call_next)
    File "C:\Users\eikes\Arbeit\WISdoM OSS\services\geo-data-rest\api\__init__.py", line 56, in check_user_scope
      raise HTTPException(
  fastapi.exceptions.HTTPException
  ```
</details>

* I expected an `Bad Request 400` with the body being `{"error": "missing_authorization_header"}`

### Operating System

Windows

### Operating System Details

I'm using PyCharm for the development on a Surface Pro 7 with Windows 11. The whole project runs in an virtual environment, managed by `venv`:
```
PyCharm 2021.3.2 (Professional Edition)
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    io.github.aveenstra.run-anything (1.7)
    com.intellij.swagger (213.6777.8)
    com.intellij.ideolog (203.0.27.0)
    com.github.jk1.ytplugin (2021.4.144)
    com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1)
    String Manipulation (9.2.0)
    mobi.hsz.idea.gitignore (4.3.0)
    com.mallowigi (54.1.0)
    com.almightyalpaca.intellij.plugins.discord (1.8.0)
    ru.meanmail.plugin.requirements (2022.3-2021.3)
    net.ashald.envfile (3.2.2)
    izhangzhihao.rainbow.brackets (6.21)
    com.koxudaxi.pydantic (0.3.11)
    com.chrisrm.idea.MaterialThemeUI (6.13.0)
    ru.adelf.idea.dotenv (2022.1)
```

### FastAPI Version

0.75.0

### Python Version

Python 3.9.9

### Additional Context

I already tried switching the versions of the underlying starlette to `0.18.0` which did not change the error. Furthermore, I also tried using FastAPI `0.74.1` which also produces the same error.

**Comment by Kludex** [comment]
`HTTPException` is not meant to be used inside of a middleware. That's expected.

**Comment by j-suchard** [comment]
Okay, I did not find any documentation that indicated otherwise. 
Therefore this is mainly my mistake for thinking that it would work.

I'll close the issue since this answered by question
