### ISSUE TITLE
openapi render crashes with response_class of Tuple

### ISSUE THREAD

**Issue by toppk** [tiangolo/fastapi#466]
**Describe the bug**
openapi schema generation crashes  when given a tuple as response_class.  all the other behavior is working properly, just the openapi renderer.  I think this is because tuples in openapi aren't supported that well.   see this comment for a suggestion

https://github.com/OAI/OpenAPI-Specification/issues/1026#issuecomment-434953167

There should be some way to properly degrade this.

**To Reproduce**
1) run this code:
====
from fastapi import FastAPI
from pydantic import BaseModel
from typing import Tuple

class Test(BaseModel):
    name: str

app = FastAPI()

@app.get("/", response_model=Tuple[bool,Test])
async def root():
    return True, {'name': 'Ken'}
====
2) navigate to h**p://localhost:8000/docs

**Expected behavior**

I'd expect openapi docs

>>> import fastapi
>>> print(fastapi.__version__)
0.35.0
>>> 
(fastapi) [toppk@static fastapi]$ python --version
Python 3.6.9

- Python version, get it with:

```bash
python --version
```

**Additional context**

For reference here is the ouput I'm getting on the console:

$ uvicorn test-fastapi:app
INFO: Started server process [1976904]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 56070) - "GET / HTTP/1.1" 200
INFO: ('127.0.0.1', 56070) - "GET /docs HTTP/1.1" 200
INFO: ('127.0.0.1', 56070) - "GET /openapi.json HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/middleware/errors.py", line 177, in __call__
    raise exc from None
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/middleware/errors.py", line 155, in __call__
    await self.app(scope, receive, _send)
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/routing.py", line 592, in __call__
    await route(scope, receive, send)
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/home/toppk/.local/share/virtualenvs/fastapi-R7xES2y_/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "./fastapi/applications.py", line 87, in openapi
    return JSONResponse(self.openapi())
  File "./fastapi/applications.py", line 79, in openapi
    openapi_prefix=self.openapi_prefix,
  File "./fastapi/openapi/utils.py", line 272, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, include_none=False)
  File "pydantic/main.py", line 270, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 697, in pydantic.main.validate_model
pydantic.error_wrappers.ValidationError: 7 validation errors
paths -> / -> get -> responses -> default
  field required (type=value_error.missing)
content -> application/json -> schema -> items
  value is not a valid dict (type=type_error.dict)
content -> application/json -> schema -> items
  value is not none (type=type_error.none.allowed)
content -> application/json -> schema -> $ref
  field required (type=value_error.missing)
content -> application/json -> schema
  value is not none (type=type_error.none.allowed)
responses -> 200 -> content
  value is not none (type=type_error.none.allowed)
paths -> / -> get
  value is not none (type=type_error.none.allowed)

**Comment by toppk** [comment]
here is a copy of the test case for reference.  
[test-fastapi.py.txt](https://github.com/tiangolo/fastapi/files/3539636/test-fastapi.py.txt)

**Comment by haizaar** [comment]
@toppk 
It will really help if you apply a proper formatting to your issue.

**Comment by tiangolo** [comment]
@toppk as @dmontagu , tuples with exact values inside are explicitly unsupported by OpenAPI (there are notes stating that in the spec).

So, yeah, I think the best you can do is something like what @dmontagu suggests. Or better, if you can, make it a Pydantic model with 2 fields. It would also probably be a lot easier to use for your API users.
