### ISSUE TITLE
Cannot start FastAPI: AttributeError 'Data' object has no attribute 'data'

### ISSUE THREAD

**Issue by QuinnBast** [tiangolo/fastapi#4732]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def healthCheck():
    return {"active": True}
```

### Description

Running the code above on a Windows x84 machine results in the following error:

Interestingly, this was working for a few sample runs but has since corrupted itself somehow.

<pre>
$uvicorn otherMain:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\<user>\\Documents\\Coding\\MemoryMapper\\Server\\src']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [16252] using statreload
WARNING:  The --reload flag should not be used in production on Windows.
INFO:     Started server process [21584]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:62042 - "GET / HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\Qu<user>nn\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\routing.py", line 64, in app
    await response(scope, receive, send)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\responses.py", line 156, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\exceptions.py", line 68, in sender
    await send(message)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\starlette\middleware\errors.py", line 156, in _send
    await send(message)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 462, in send
    output = self.conn.send(event)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\h11\_connection.py", line 510, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\h11\_connection.py", line 543, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\Users\<user>\Documents\Coding\MemoryMapper\Server\venv\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
AttributeError: 'Data' object has no attribute 'data'
</pre>

### Operating System

Windows

### Operating System Details

Windows x86

### FastAPI Version

0.75.0

### Python Version

3.10

### Additional Context

![image](https://user-images.githubusercontent.com/22599103/160323671-eff692fc-2d35-4329-b8fd-27b142cb6509.png)

**Comment by QuinnBast** [comment]
Deleting my virual environment and re-installing it seems to have fixed the issue. The imports look the exact same as in the screenshot above. Not sure how but I'm guess something in fastapi must have corrupted some of the `/venv/lib/` files somehow 🤷
