### ISSUE TITLE
Can't use frozen native dataclass

### ISSUE THREAD

**Issue by dimaqq** [tiangolo/fastapi#4763]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from dataclasses import dataclass
from fastapi import FastAPI

app = FastAPI()

@dataclass(frozen=True)
class Mod:
    foo: str


@app.get("/", response_model=Mod)
async def get_mod():
    return {"foo": "bar"}
```

### Description

* access http://localhost:8000/openapi.json
* see the crash

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/fastapi/applications.py", line 216, in openapi
    return JSONResponse(self.openapi())
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/fastapi/applications.py", line 191, in openapi
    self.openapi_schema = get_openapi(
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 412, in get_openapi
    flat_models = get_flat_models_from_routes(routes)
  File "/home/dima/.cache/pypoetry/virtualenvs/mre-frozen-dataclass-3kNYbFrL-py3.11/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 377, in get_flat_models_from_routes
    flat_models = callback_flat_models | get_flat_models_from_fields(
  File "pydantic/schema.py", line 448, in pydantic.schema.get_flat_models_from_fields
  File "pydantic/schema.py", line 421, in pydantic.schema.get_flat_models_from_field
  File "pydantic/dataclasses.py", line 255, in pydantic.dataclasses.dataclass
  File "pydantic/dataclasses.py", line 250, in pydantic.dataclasses.dataclass.wrap
  File "pydantic/dataclasses.py", line 159, in pydantic.dataclasses._process_class
  File "/usr/lib/python3.8/dataclasses.py", line 1019, in dataclass
    return wrap(cls)
  File "/usr/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib/python3.8/dataclasses.py", line 891, in _process_class
    raise TypeError('cannot inherit non-frozen dataclass from a '
TypeError: cannot inherit non-frozen dataclass from a frozen one
```

### Operating System

Linux

### Operating System Details

Linux

### FastAPI Version

0.75.1

### Python Version

3.10, 3.11

### Additional Context

pydantic 1.9.0

### Workarounds:

1. remove `frozen=True`, or
2. `from pyndatic.dataclasses impotr dataclass` -- the pydantic version works.

It could be a bug in pydantic for all I know, or even a limitation, in which case `fastapi` docs need to be updated.

**Comment by jonatasoli** [comment]
In this case I think the response_model statement expect a pydantic object and not a dataclass.

**Comment by dimaqq** [comment]
Note that `dataclasses.dataclass` can be used if they are not frozen.
My gut tells me that pydantic attempts to convert my dataclass into their kind in order to generate the schema and/or to validators, in which case this is not a FastAPI problem per se.

If this is indeed a limitation, let's note this in FastAPI docs 🙏🏿

**Comment by jonatasoli** [comment]
Why in your case, use a dataclass instead of a pydantic object?

**Comment by dimaqq** [comment]
A couple of reasons, though perhaps neither is super important:
1. simplicity, if I can use stdlib dataclass, why not?
2. exporting data in a shape that's defined in a 3p package

**Comment by dimaqq** [comment]
I wonder if https://github.com/samuelcolvin/pydantic/issues/3469 is related.
Conceivably, generating the OpenAPI schema for the entire API could use a BaseModel somewhere in pydantic 🤔

**Comment by dimaqq** [comment]
Or maybe this: https://github.com/samuelcolvin/pydantic/issues/2555

**Comment by dimaqq** [comment]
Or this? https://github.com/samuelcolvin/pydantic/issues/2065

**Comment by jonatasoli** [comment]
It looks like something would be more related to pydantic than actually fastapi from the data examples.

**Comment by dimaqq** [comment]
Indeed it is. All I'm proposing is for FastAPI to document this limitation for the time being.

**Comment by dimaqq** [comment]
OT: looks like my issue comments are breaking GHA:
> github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for installation ID 3370073.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
https://github.com/tiangolo/fastapi/runs/6257027940?check_suite_focus=true

**Comment by haf** [comment]
It seems to be specific to something fastapi might do when it converts normal dataclasses to pydantic dataclasses?

**Comment by haf** [comment]
https://github.com/samuelcolvin/pydantic/pull/2557
