### ISSUE TITLE
Need a wrapped exception when jsonable_encoder throws an exception

### ISSUE THREAD

**Issue by dg-ow** [tiangolo/fastapi#4835]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI
import requests

app = FastAPI()

@app.get("/")
def read_root():
    return requests.get('https://api.github.com/thisodesntexist')
```

### Description

See #4834 .

The exception trace from FastAPI was:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 127, in serialize_response
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 57, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/site-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'property' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

In order to find out what API had the exception, I had to use the debugger.  I think wrapping exceptions from `serialize_response` in `routing.py` at  line 127 with information about what the request is will help others debug problems like this.

### Operating System

Linux

### FastAPI Version

0.65.1

### Python Version

3.8.8

**Comment by tomy0000000** [comment]
The right way of doing this is

```python
@app.get("/")
def read_root():
    return requests.get('https://api.github.com/thisodesntexist').json()
```

Regarding whether FastAPI's json encoder should have the ability to automatically encoding `requests.models.Response`, see my explanation in [#4834](https://github.com/tiangolo/fastapi/issues/4834#issuecomment-1149036531).

But yes, I do agree this ValueError is a bit confusing, and we probably should just have a clear message saying that the encoder could not find a way to encode it.
