### ISSUE TITLE
Response model using Python Dataclasses with One-to-Many relationship results in error in openapi.json

### ISSUE THREAD

**Issue by InzamamAnwar** [tiangolo/fastapi#4944]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import List
from dataclasses import dataclass, field

from fastapi import FastAPI

app = FastAPI()


@dataclass
class Student:
    name: str = 'John Doe'
    age: int = 12


@dataclass
class Class:
    students: List[Student] = field(default_factory=list)
    name: str = 'Computer Science'


@app.get('/class/', response_model=Class)
async def get_class():
    cs_class = Class()
    cs_class.students = [Student()]
    return cs_class
```

### Description

When `dataclass` is used as response model with one-to-many relationship, it results in error while generating `openapi.json`. Otherwise, the endpoint works as intended. 

Stack trace for the error:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/fastapi/applications.py", line 224, in openapi
    return JSONResponse(self.openapi())
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/fastapi/applications.py", line 209, in openapi
    servers=self.servers,
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 419, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "/home/user/anaconda3/envs/nlpserver/lib/python3.7/site-packages/fastapi/utils.py", line 29, in get_model_definitions
    model, model_name_map=model_name_map, ref_prefix=REF_PREFIX
  File "pydantic/schema.py", line 617, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 658, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 258, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 498, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 848, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 736, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 563, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 947, in pydantic.schema.field_singleton_schema
ValueError: Value not declarable with JSON Schema, field: name='_students' type=Student required=True

```

### Operating System

Linux

### FastAPI Version

Version: 0.77.1

### Python Version

Python 3.7.9

### Additional Context

From stack trace it looks like the issue is related to fastAPI while generating the openapi documentation.

**Comment by aboubacs** [comment]
This is documented: https://fastapi.tiangolo.com/advanced/dataclasses/#dataclasses-in-nested-data-structures

> In some cases, you might still have to use Pydantic's version of dataclasses. For example, if you have errors with the automatically generated API documentation.
