### ISSUE TITLE
default HTTPException handler adds content when there should be none

### ISSUE THREAD

**Issue by bentheiii** [tiangolo/fastapi#4946]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI, HTTPException
from starlette.requests import Request

app = FastAPI()

@app.get('/foo')
async def route(request: Request):
    raise HTTPException(status_code=304)


def main():
    import uvicorn

    uvicorn.run(app, debug=True, host="0.0.0.0", port=8888,)


if __name__ == "__main__":
    main()
```

### Description

* open the browser and GET endpoint "/foo"
* the response is supposedly OK but an error is logged
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/uvicorn/middleware/debug.py", line 96, in __call__
    raise exc from None
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/uvicorn/middleware/debug.py", line 93, in __call__
    await self.app(scope, receive, inner_send)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 104, in __call__
    await response(scope, receive, sender)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/starlette/responses.py", line 162, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 79, in sender
    await send(message)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/uvicorn/middleware/debug.py", line 90, in inner_send
    await send(message)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 462, in send
    output = self.conn.send(event)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/h11/_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/h11/_connection.py", line 501, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/h11/_writers.py", line 58, in __call__
    self.send_data(event.data, write)
  File "/home/bena/.cache/pypoetry/virtualenvs/ruleservice-r2airgVQ-py3.8/lib/python3.8/site-packages/h11/_writers.py", line 78, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

This appears to be an issue where the default FastAPI handler for HTTPExceptions always returns content even for status codes (304, 204), where no content should be specified.

### Operating System

Linux

### FastAPI Version

0.78.0

### Python Version

3.8.12

**Comment by aboubacs** [comment]
Hi,

The default handler for HTTPException will always construct a JSONResponse with content. https://github.com/tiangolo/fastapi/blob/22528373bba6a654323de416ad5c867cbadb81bb/fastapi/exception_handlers.py#L9-L16

This behavior is documented in the tip here: https://fastapi.tiangolo.com/tutorial/handling-errors/#the-resulting-response

This is incompatible with returning HTTP status codes that shouldn't have any content. Whether or not fastapi should choose whether to send a JSONResponse or not based on the status code is debatable, but since this behavior isn't implemented today, you can build it with your own exception handler. Some sample code would be:

```python
from fastapi import FastAPI, HTTPException, Response
from starlette.requests import Request

app = FastAPI()


class NotModifiedException(Exception):
    pass


@app.exception_handler(NotModifiedException)
async def not_modified_exception_handler(request: Request, exc: NotModifiedException):
    return Response(status_code=304)


@app.get('/foo')
async def route(request: Request):
    raise NotModifiedException()

```

**Comment by bentheiii** [comment]
Thanks @aboubacs, your suggestion is more or less what I already implemented. This is about changing the default handler so user's wouldn't have to add their own.

BTW I prefer a more generic handler
```
@app.exception_handler(HTTPException)
async def ret(request: Request, exc: HTTPException) -> Response:
    # fastapi's default event handler is bugged (https://github.com/tiangolo/fastapi/issues/4946)
    headers = getattr(exc, "headers", None)
    if exc.status_code in {204, 304}:
        if headers:
            return Response(status_code=exc.status_code, headers=headers)
        else:
            return Response(status_code=exc.status_code)
    if headers:
        return JSONResponse(
            {"detail": exc.detail}, status_code=exc.status_code, headers=headers
        )
    else:
        return JSONResponse({"detail": exc.detail}, status_code=exc.status_code)
```
