### ISSUE TITLE
Model example + OpenAPI = TypeError("'ObjectId' object is not iterable")

### ISSUE THREAD

**Issue by sy6sy2** [tiangolo/fastapi#5059]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from bson import ObjectId
from fastapi import FastAPI
from pydantic import BaseModel, Field


class PyObjectId(ObjectId):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if not ObjectId.is_valid(v):
            raise ValueError("Invalid ObjectId")
        return ObjectId(v)
    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema.update(type="string")


class MyBaseModel(BaseModel):
    pass

    class Config:
        json_encoders = {
            ObjectId: lambda oid: str(oid)
        }


class Model2(MyBaseModel):
    a: PyObjectId


class Model1(MyBaseModel):
    a: str = Field(example="Foo")
    b: Model2 = Field(example=Model2(a="62960507a3f31888572152e2"))


app = FastAPI()


@app.get("/", response_model=Model1)
def read_root():
    model2 = Model2(
        a="62960507a3f31888572152e2"
    )
    model1 = Model1(
        a="Fii",
        b=model2
    )
    return model1
```

### Description

Using the `Field(example= ......)` feature in my model definition in combination with an `ObjectId` attribute caused the OpenAPI generation to be broken.

To reproduce, simply copy past the example code given below in `main.py`, run `uvicorn main:app --reload`, now open you browser on http://127.0.0.1:8000/docs then you will obtain this error:

```
INFO:     127.0.0.1:53373 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 137, in jsonable_encoder
    data = dict(obj)
TypeError: 'ObjectId' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 216, in openapi
    return JSONResponse(self.openapi())
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 191, in openapi
    self.openapi_schema = get_openapi(
  File "/usr/local/lib/python3.10/site-packages/fastapi/openapi/utils.py", line 443, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 66, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  [Previous line repeated 4 more times]
  File "/usr/local/lib/python3.10/site-packages/fastapi/encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'ObjectId' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

To fix this issue, simply remove the `Field(example=Model2(a="62960507a3f31888572152e2"))` text in the example code.

### Operating System

macOS

### Operating System Details

macOS 12.2.1

### FastAPI Version

0.75.2

### Python Version

3.9.12

**Comment by JarroVGIT** [comment]
The `example` parameter only takes simple values or dicts (or something that can be construed as a dict). That is because, the `openapi.json` is basically just one going JSON document that describes your API and does not do 'in-depth' decoding. The `json_encoders` you defined are only used when serialising a response. 

So, it doesn't magically create an example based on your `BaseModel`, it just parses it as JSON for the purpose of putting it into the `openapi.json`. This is not a bug. 

Also, you can't fix this by adding a `__dict__` method to your `PyObjectId` class. That is because you use that object in a model (model2), that is nested in another model (model1). The example that you are giving is the request example of `Model2`, and it doesn't make sense to define that in `PyObjectId`. If you were to use `Model1` in a request parameter, you also needed to demonstrate that the input is like `"a": "62960507a3f31888572152e2"` and not bother the user with the type of object (as they cannot post objects, only json).

So, for your use case above, the only thing to make sense is to add an example as follows:
```python
class Model1(MyBaseModel):
    a: str = Field(example="Foo")
    b: Model2 = Field(example={"a":"62960507a3f31888572152e2"})
```

which results in: 
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/13659033/175575484-c9331680-896f-4f46-a341-9777a313cecc.png">

When putting such a model in a request param, it then would look like this:
```python
@app.get("/path")
def read_path(input: Model1):
    return input
```
results in (Note: it looks the same but it defines the request **body**):

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/13659033/175576140-f1137f1d-8521-435d-8b80-3c0f8160b691.png">


Hope this clarifies for you :)

**Comment by sy6sy2** [comment]
Thank you for your clear and detailed answer!

I followed your advice and it works well with the example in dict type. Thank you!
