### ISSUE TITLE
Calling a function by key from a dictionary as background task raises `TypeError: 'dict' object is not callable` despite actually running the required function

### ISSUE THREAD

**Issue by atiabbz** [tiangolo/fastapi#5085]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```
lib/
├─ functions.py
├─ fancy_unit/
│  ├─ core.py
main.py
```

```python
# /main.py
from fastapi import FastAPI
from fastapi.background import BackgroundTasks

from lib.functions import FUNCTIONS

app = FastAPI()


@app.get("/background", status_code=status.HTTP_202_ACCEPTED)
async def background(key: str, arg: str, background_tasks: BackgroundTasks):
    if key in FUNCTIONS:
        background_tasks.add_task(FUNCTIONS[key](arg))
        return {"message": "Accepted for processing"}
```

```python
# /lib/functions.py
from .fancy_unit.core import core

FUNCTIONS = {"fancy_unit": core}
```

```python
# /lib/fancy_unit/core.py
def core(arg: str) -> dict:
    print(f"fancy logic on {arg}")
    return {"output": "wow"}
```

### Description

I am trying to have a dictionary containing functions as values and call them as background tasks with arguments received as query parameters in requests.

Using the example code, when I make a request to the `/background?key=fancy_unit&arg=hello` path, I can see in the terminal that `fancy logic on hello` gets printed as expected but that is followed by a `TypeError: 'dict' object is not callable` exception. What is causing this exception to be raised?

```
INFO:     Started server process [4704]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
fancy logic on hello
INFO:     127.0.0.1:61531 - "GET /background?key=fancy_unit&arg=hello HTTP/1.1" 202 Accepted
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in 
run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 124, in __call__       
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__  
    raise exc
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__  
    await self.app(scope, receive, _send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 68, in app
    await response(scope, receive, send)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 165, in __call__
    await self.background()
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\background.py", line 43, in __call__
    await task()
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\background.py", line 28, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\AtiabZakaria\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: 'dict' object is not callable
```

### Operating System

Windows

### FastAPI Version

0.78.0

### Python Version

3.10.4

**Comment by atiabbz** [comment]
I see. It works as I need now, thanks. In hindsight, I should've just been more careful with the syntax.
