### ISSUE TITLE
Cannot exit the scope in Websocket Testing with TestClient

### ISSUE THREAD

**Issue by FarukOzderim** [tiangolo/fastapi#5246]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
I know this might be a little bit a hard reproduction, but I encountered this problem in this complex use-case, so it's worth it IMO.

1. Get this [state](https://github.com/gradio-app/gradio/tree/a4effa6d3ebcaed76d5f6565cbc6d0db742f192f) of the Gradio repo.
2. Remove comments from test/test_event_queue.py
3. Install dependencies by bash scripts/install_test_requirements.sh 
4. run pytest test/test_event_queue.py
```

### Description

The problem is, the test does not end because it cannot exit this scope:
`with client.websocket_connect("/queue/join") as websocket:`

Btw I was able to finish the test while debugging it line by line, so it might've worked because of debugger interrupts.

And this is what I get when I ctrl+c out of the non-ending test.

```

 % pytest test/test_event_queue.py

========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.8.2, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/hugginface-5g/Downloads/git-repos/gradio
plugins: anyio-3.6.1, asyncio-0.19.0, respx-0.19.2, cov-3.0.0
asyncio: mode=strict
collected 1 item                                                                                                                                                                                         

test/test_event_queue.py ^C^C^C

============================================================================================ warnings summary ============================================================================================
../../../../../Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py:641
  /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py:641: RuntimeWarning: coroutine 'Blocks.create_limiter' was never awaited
    self._ready.clear()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================================== 1 warning in 18.76s ===========================================================================================
Traceback (most recent call last):
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/anyio/from_thread.py", line 502, in start_blocking_portal
    run_future.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/main.py", line 347, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/runner.py", line 111, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/runner.py", line 130, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/runner.py", line 219, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/runner.py", line 258, in call_runtest_hook
    return CallInfo.from_call(
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/runner.py", line 338, in from_call
    result: Optional[TResult] = func()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/runner.py", line 259, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/runner.py", line 166, in pytest_runtest_call
    item.runtest()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/python.py", line 1761, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/python.py", line 192, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 454, in inner
    _loop.run_until_complete(task)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/test/test_event_queue.py", line 45, in test_queue_with_single_event
    break
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/starlette/testclient.py", line 328, in __exit__
    self.exit_stack.close()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 533, in close
    self.__exit__(None, None, None)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/starlette/testclient.py", line 454, in _portal_factory
    yield portal
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/anyio/from_thread.py", line 502, in start_blocking_portal
    run_future.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 636, in __exit__
    self.shutdown(wait=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/main.py", line 315, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/main.py", line 282, in wrap_session
    config.hook.pytest_keyboard_interrupt(excinfo=excinfo)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/terminal.py", line 832, in pytest_keyboard_interrupt
    self._keyboardinterrupt_memo = excinfo.getrepr(funcargs=True)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/code.py", line 666, in getrepr
    return fmt.repr_excinfo(self)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/code.py", line 926, in repr_excinfo
    reprtraceback = self.repr_traceback(excinfo_)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/code.py", line 867, in repr_traceback
    reprentry = self.repr_traceback_entry(entry, einfo)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/code.py", line 810, in repr_traceback_entry
    source = self._getentrysource(entry)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/code.py", line 718, in _getentrysource
    source = entry.getsource(self.astcache)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/code.py", line 260, in getsource
    astnode, _, end = getstatementrange_ast(
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/source.py", line 187, in getstatementrange_ast
    start, end = get_statement_startend2(lineno, astnode)
  File "/Users/hugginface-5g/Downloads/git-repos/gradio/venv/lib/python3.8/site-packages/_pytest/_code/source.py", line 151, in get_statement_startend2
    if isinstance(x, (ast.stmt, ast.ExceptHandler)):
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt


```

### Operating System

macOS

### FastAPI Version

0.79.0

### Python Version

3.8.2

**Comment by Kludex** [comment]
The `TestClient` is on Starlette.

**Comment by FarukOzderim** [comment]
Oh shoot, should've checked that. Moving it to starlette repo then ty!
