### ISSUE TITLE
Fastapi run with poetry with .env file have conflict with python-dotenv 

### ISSUE THREAD

**Issue by apexbb** [tiangolo/fastapi#5361]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
in core/config.py
from pydantic import BaseSettings
import os

class Settings_es(BaseSettings):
    ES_HOST  : str 
    ES_LOGIN : str
    ES_PW    : str

    class Config:
        env_file = ".env"

In db.database.py
from elasticsearch import Elasticsearch
from core.config import Settings_es

def get_es():
    setting = Settings_es() #must put in here! cannot put n global
    es = Elasticsearch(hosts=setting.ES_HOST, http_auth=(setting.ES_LOGIN,setting.ES_PW))
    return es


if __name__ == "__main__":
    print("test db")
```

### Description

I am using poetry as project package dependency,

the pyproject.toml have:
[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.82.0"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
elasticsearch = "7.14.0"
pydantic = {extras = ["dotenv"], version = "^1.10.2"}
python-dotenv = "^0.21.0"

i RUN OK with poetry run python3 main.py
But not ok with uvicorn main:app --reload
When running with  uvicorn main:app --reload,

i got error :
INFO:     127.0.0.1:59934 - "GET /device/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 298, in pydantic.env_settings.read_env_file
ModuleNotFoundError: No module named 'dotenv'
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/user/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/Jeff/Software/metering_api_gateway/metering_api_gateway/./crud/device.py", line 9, in env_test
    con = get_es()
  File "/home/user/Jeff/Software/metering_api_gateway/metering_api_gateway/./db/database.py", line 5, in get_es
    setting = Settings_es() #must put in here! cannot put n global
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 169, in pydantic.env_settings.EnvSettingsSource.__call__
  File "pydantic/env_settings.py", line 300, in pydantic.env_settings.read_env_file
ImportError: python-dotenv is not installed, run `pip install pydantic[dotenv]`
INFO:     127.0.0.1:59936 - "GET /favicon.ico HTTP/1.1" 200 OK

However, i have already added python-dotenv = "^0.21.0"

### Operating System

Linux

### FastAPI Version

0.82

### Python Version

3.8

### Additional Context

the file structure tree
![Screenshot from 2022-09-08 11-03-55](https://user-images.githubusercontent.com/76148283/189025288-65a052f9-d448-46eb-8c3f-7df996dd35e4.jpg)

the error screen & project package installed
![Screenshot from 2022-09-08 11-08-41](https://user-images.githubusercontent.com/76148283/189025371-a42fff4f-8444-4eff-bfb8-84413145dfd2.png)

**Comment by apexbb** [comment]
thanks you ! @mbroton @BilalAlpaslan

**Comment by tiangolo** [comment]
Thanks for the help here @mbroton and @BilalAlpaslan ! 👏  🙇 

Thanks for reporting back and closing the issue @apexbb  👍
