### ISSUE TITLE
Gunicorn keeps booting workers when onstartup raises exception

### ISSUE THREAD

**Issue by alexanderluiscampino** [tiangolo/fastapi#5370]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI

app = FastAPI()

items = {}


@app.on_event("startup")
async def startup_event():
    items["foo"] = {"name": "Fighters"}
    items["bar"] = {"name": "Tenders"}

    raise Exception


@app.get("/items/{item_id}")
async def read_items(item_id: str):
    return items[item_id]

"""
gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
"""
```

### Description

I am using the example straight from [here](https://fastapi.tiangolo.com/advanced/events/) starting the server locally using [server-workers](https://fastapi.tiangolo.com/deployment/server-workers/)

I have checked the following issues/threads for solutions, but somehow don't see any, perhaps I am missing on something obvious:

1. https://github.com/tiangolo/fastapi/issues/253
2. https://github.com/encode/uvicorn/issues/1031
3. https://github.com/encode/uvicorn/issues/1066

Ideally, I'd like to use the onstartup event to check all my DBs are reachable. And fail to start-up the app if not. But this just keepings on spinning up workers, never actually failing. 

### Operating System

Linux

### Operating System Details

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### FastAPI Version

0.68.2

### Python Version

Python 3.10.6

**Comment by JarroVGIT** [comment]
Could you update to the most recent version of FastAPI?

**Comment by iudeen** [comment]
Also latest version of Uvicorn!

**Comment by alexanderluiscampino** [comment]
Thank you guys, you're correct, updated versions of the 3 libs:

- FastAPI: 0.83.0
- Uvicorn: 0.18.3
- Gunicorn: 20.1.0

resulted in the following output:
```
[2022-09-11 20:06:57 +0000] [2270] [INFO] Starting gunicorn 20.1.0
[2022-09-11 20:06:57 +0000] [2270] [INFO] Listening at: http://0.0.0.0:80 (2270)
[2022-09-11 20:06:57 +0000] [2270] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-09-11 20:06:57 +0000] [2271] [INFO] Booting worker with pid: 2271
[2022-09-11 20:06:57 +0000] [2271] [INFO] Started server process [2271]
[2022-09-11 20:06:57 +0000] [2271] [INFO] Waiting for application startup.
[2022-09-11 20:06:57 +0000] [2271] [ERROR] Traceback (most recent call last):
  File "/usr/local/pip-global/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/pip-global/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/usr/local/pip-global/starlette/routing.py", line 612, in startup
    await handler()
  File "/workspaces/vscode-remote-try-python/app.py", line 13, in startup_event
    raise Exception
Exception

[2022-09-11 20:06:57 +0000] [2271] [ERROR] Application startup failed. Exiting.
[2022-09-11 20:06:57 +0000] [2271] [INFO] Worker exiting (pid: 2271)
[2022-09-11 20:06:57 +0000] [2270] [INFO] Shutting down: Master
[2022-09-11 20:06:57 +0000] [2270] [INFO] Reason: Worker failed to boot.
```

Now I just need to convince my organization to use the latest FastAPI and the other modules.

**Comment by tiangolo** [comment]
Thanks for the help here @JarroVGIT and @iudeen ! 👏  🙇 

Thanks for reporting back and closing the issue @alexanderluiscampino  👍
