### ISSUE TITLE
Error while opening swagger docs while uploading file in APIRouter

### ISSUE THREAD

**Issue by Shrijeeth** [tiangolo/fastapi#5425]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
router = APIRouter(
    prefix='/predict',
    tags=["Prediction"],
    responses={404: {"description": "Not Found"}}
)


@router.post("/")
async def predict(file: UploadFile = File(...)):
    extension = file.filename.split(".")[-1] in ("jpg", "jpeg", "png")
    if not extension:
        raise HTTPException(status_code=400, detail="File Format Error : Uploaded file must be a JPG, JPEG or PNG file")
    image = read_image_file(await file.read())
    result = predict_pneumonia(image)
    if result > 0.6:
        return JSONResponse(content={"prediction": "pneumonia"})
    return JSONResponse(content={"prediction": "no pneumonia"})
```

### Description

I am just trying to create a ML prediction application using FastAPI. While uploading images, swagger docs doesn't load and its showing the below mentioned error. But the endpoint works perfectly when tried with Postman.

![image](https://user-images.githubusercontent.com/58306412/192039571-1eed5f98-cd67-49ec-97ec-364b28ace0f9.png)
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\fastapi\applications.py", line 225, in openapi
    return JSONResponse(self.openapi())
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\fastapi\applications.py", line 200, in openapi
    self.openapi_schema = get_openapi(
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\fastapi\openapi\utils.py", line 423, in get_openapi
    definitions = get_model_definitions(
  File "D:\Programming_Languages\Anaconda\envs\Medaignostic-Playground\lib\site-packages\fastapi\utils.py", line 39, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.Body_predict_predict__post'>
```

### Operating System

Windows

### FastAPI Version

0.85.0

### Python Version

3.9

**Comment by JarroVGIT** [comment]
There are quite a few issues that are similar. Examples are:

https://github.com/tiangolo/fastapi/issues/2724
https://github.com/tiangolo/fastapi/issues/1505
https://github.com/tiangolo/fastapi/issues/5138

It would depend on the rest of your code if the issues are similar though, maybe it helps point you in the right direction?

**Comment by Shrijeeth** [comment]
Thank you, I am able to resolve my issue by changing code inside routing.py file in fastapi (Line 593). I updated the code in routing.py line 593, as given below. Now it works perfectly.

```
if route not in self.routes:
            self.routes.append(route)
```

**Comment by JarroVGIT** [comment]
Interesting, so there is another route that already is in your APIRouter then? Did you name the routes as the same?

**Comment by Shrijeeth** [comment]
Yeah, I think so that's the issue here. I had same variable name for APIRouter object in another file but the prefixes are different though. I then imported both the files in my main.py and I added using app.include_router

**Comment by tiangolo** [comment]
Thanks for the help here @JarroVGIT ! 👏  🙇 

If that solves the original problem, then you can close this issue @Shrijeeth  ✔️
