### ISSUE TITLE
How to use Pydantic BaseModels with numpy.ndarray as the response_model

### ISSUE THREAD

**Issue by mariannasb** [tiangolo/fastapi#5514]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class ControlValueExt(BaseModel):
    value: Union[int, str, numpy.ndarray]

    class Config:
        arbitrary_types_allowed = True

...

    @staticmethod
    def get_control(
        ctrl_id_or_name: Union[int, str], device: str = DEF_DEVICE
    ) -> ControlValueExt:
        """Get v4l2 control value from video device"""
        try:
            cam = Camera._get_camera(device)
            ctrl_val = cam.get_ext_control(ctrl_id_or_name)
        except Exception as e:
            raise e

        return ControlValueExt(value=ctrl_val.value)

...

@app.get(
    V4L2_ROUTE + "control/{ctrl_id_or_name}",
    response_model=ControlValueExt,
    tags=[Tags.controls],
)
def get_control(
    ctrl_id_or_name: Union[int, str] = Path(  # noqa: B008
        description="Id or Name of v4l2 control",
    ),
    params: CommonParams = Depends(),
) -> JSONResponse:
    """Get v4l2 control"""
    return Camera.get_control(ctrl_id_or_name, params.dev)
```

### Description

If I use the `response_model=ControlValueExt`
I get the following error:
```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/fastapi/utils.py", line 78, in create_response_field
    return response_field(field_info=field_info)
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'numpy.ndarray'>, see `arbitrary_types_allowed` in Config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 234, in prepare
    _fixup_main_from_name(data['init_main_from_name'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 258, in _fixup_main_from_name
    main_content = runpy.run_module(mod_name,
  File "/usr/lib/python3.10/runpy.py", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/root/quark_backend/app.py", line 404, in <module>
    def get_control(
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 626, in decorator
    self.add_api_route(
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 565, in add_api_route
    route = route_class(
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 405, in __init__
    ] = create_cloned_field(self.response_field)
  File "/usr/lib/python3.10/site-packages/fastapi/utils.py", line 104, in create_cloned_field
    use_type.__fields__[f.name] = create_cloned_field(
  File "/usr/lib/python3.10/site-packages/fastapi/utils.py", line 107, in create_cloned_field
    new_field = create_response_field(name=field.name, type_=use_type)
  File "/usr/lib/python3.10/site-packages/fastapi/utils.py", line 80, in create_response_field
    raise fastapi.exceptions.FastAPIError(
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that typing.Union[int, str, numpy.ndarray] is a valid pydantic field type
```

If I comment it out it partially works.
However when I try to retrieve a `control` which has the return type of `ndarray` I get:
```shell
2022-10-18 08:02:32 - fast_api_app ERROR    (MainThread) - Unknown Exception: [TypeError('cannot convert dictionary update sequence element #0 to a sequence'), TypeError('vars() argument must have __dict__ attribute')]
INFO:     10.100.7.3:45896 - "GET /api/v4l2/control/Fixed%20Pattern%20Noise%20Correction?dev=%2Fdev%2Fqtec%2Fvideo0 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/fastapi/encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: cannot convert dictionary update sequence element #0 to a sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/fastapi/encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 249, in app
    content = await serialize_response(
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/lib/python3.10/site-packages/fastapi/encoders.py", line 66, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/lib/python3.10/site-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/lib/python3.10/site-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError('cannot convert dictionary update sequence element #0 to a sequence'), TypeError('vars() argument must have __dict__ attribute')]
```

I had also tried the solution from https://github.com/pydantic/pydantic/issues/380#issuecomment-620378743 of creating my custom `Array` class with validators.
But that gives the following error when trying to load `/docs`:
```shell
2022-10-18 08:09:46 - fast_api_app ERROR    (MainThread) - Unknown Exception: Value not declarable with JSON Schema, field: name='value_Array' type=Array required=True
INFO:     10.100.7.3:45964 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 225, in openapi
    return JSONResponse(self.openapi())
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 200, in openapi
    self.openapi_schema = get_openapi(
  File "/usr/lib/python3.10/site-packages/fastapi/openapi/utils.py", line 423, in get_openapi
    definitions = get_model_definitions(
  File "/usr/lib/python3.10/site-packages/fastapi/utils.py", line 35, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 580, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 621, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 254, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 526, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 847, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 742, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 526, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 946, in pydantic.schema.field_singleton_schema
ValueError: Value not declarable with JSON Schema, field: name='value_Array' type=Array required=True
```

What is the correct way to handle response models with numpy arrays?

### Operating System

Linux

### FastAPI Version

0.85.0

### Python Version

Python 3.10.5

**Comment by Dustyposa** [comment]
Pydantic not support ndarray, you need change ndarray to list.

**Comment by tiangolo** [comment]
Yep, what @Dustyposa said 👆
