### ISSUE TITLE
StreamingResponse not streaming when using httpx.AsyncClient()

### ISSUE THREAD

**Issue by maretodoric** [tiangolo/fastapi#5600]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import APIRouter

router = APIRouter(dependencies=[Depends(get_token_cookie)])
dccapi_auth = {...}

async def getwflogs(serverip):
    async with AsyncClient(headers=dccapi_auth) as client:
        req = client.build_request("POST", f"http://{serverip}:3322/api/service/getlog/3e170885-c0e4-469a-bc73-c598d99e9de1")
        r = await client.send(req, stream=True)
        async for i in r.aiter_text():
            yield i

@router.get("/getwflogs")
async def GET_getwflogs():
    return StreamingResponse(getwflogs(serverip), media_type="text/plain")
```

### Description

* Call /getwflogs endpoint from linux curl
* Get no response until timeout occurs on AsyncClient, then i get a full, not streaming response
* RuntimeError was raised (by httpx) after timeout expired

```
Traceback (most recent call last):
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/responses.py", line 273, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/responses.py", line 269, in wrap
    await func()
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/starlette/responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
  File "/home/mtodoric/pythoniranje/fastapi-playground/dccwebserver/./app/pages/wildfly_debugger.py", line 49, in getwflogs
    yield i
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/httpx/_client.py", line 1997, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/httpx/_transports/default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "/home/mtodoric/pythoniranje/fastapi-playground/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 1 HTTP requests/responses were still in-flight.
```

Endpoint being called in function `getwflogs()` (http://{serverip}:3322/api/service/getlog/3e170885-c0e4-469a-bc73-c598d99e9de1") is also written in FastApi, when calling that from curl directly i get regular StreamingResponse. So it has to be something between httpx and FastApi or I'm doing something wrong. Code for that endpoint

```python
class JSONError(JSONResponse):
    def __init__(self, content: Any, status_code: int = 503, headers: Optional[Dict[str, str]] = None, media_type: Optional[str] = None, background: Optional[BackgroundTask] = None) -> None:
        super().__init__(content, status_code, headers, media_type, background)

async def getlog(procuuid):
    proc = await create_subprocess_shell("tail -f /opt/wildfly/standalone/log/server.log", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    PROCCONTAINER.update({procuuid: proc})

    async for i in proc.stdout:
        if procuuid not in PROCCONTAINER:
            proc.terminate()
            return
        yield i.decode()

@router.post("/service/{getorkill}/{procuuid}", description="Stream WildFly Logs")
async def POST_getlog(getorkill: str, procuuid: str):
    if getorkill == "getlog":
        return StreamingResponse(getlog(procuuid), media_type="text/plain")
    elif getorkill == "killlog":
        proc = PROCCONTAINER[procuuid]
        proc.send_signal(2)
        del PROCCONTAINER[procuuid]
    else:
        return JSONError({"error": "Unknown action."})
```

Sure, i can rewrite code to call the original endpoint but i would like to avoid that as i would have to grant users full access to that port and it may cause security concerns as this will later be called from browser javascript. 

### Operating System

Linux

### FastAPI Version

0.86.0

### Python Version

Python 3.9.5

### Additional Context

If i rewrite original `getwflogs()` function to print instead of yield, it will work just fine and it will print the output in console while being generated by aiter_text . But i would like it to yield the response, not print it to console

**Comment by tiangolo** [comment]
Is `dccapi_auth = {...}` expected to contain that?

Can you update the code example so that I can copy paste it and run it here to understand your error?

**Comment by maretodoric** [comment]
It's not, i have masked true value since it contains authorization header.
I figured it out (eventually).

Problem is:
- When calling endpoint from http://{serverip}:3322/api/service/getlog/3e170885-c0e4-469a-bc73-c598d99e9de1 works fine since it directly reaches fastapi and so i get a valid StreamingResponse
- When calling /getwflogs that's supposed to fetch response from above endpoint it fails, and i receive whole response immidiately or upon httpx timeout - because that endpoint is behind nginx proxy. Configuring `proxy_buffering  off;` on nginx fixes this issue and i get a valid StreamingResponse. Neat :)

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍
