### ISSUE TITLE
[TypeError] `guess_type` of media raising `Exception`

### ISSUE THREAD

**Issue by Pk13055** [tiangolo/fastapi#5625]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI, File, UploadFile
from fastapi.responses import FileResponse
import pandas as pd

from config import failure_path


app = FastAPI()

@app.post("/infer", tags=["inference"], response_class=FileResponse)
async def infer(input: UploadFile = File(...)) -> Union[FileResponse, dict]:
    data = None

    # Convert from CSV to pandas
    if input.content_type == "text/csv":
        data = await input.read()
        temp_io = io.StringIO(data.decode("utf-8"))
        data = pd.read_csv(temp_io)
    else:
        return {
            "success": False,
            "message": f"Content type {input.content_type} not supported (only CSV, 'text/csv' data allowed)",
        }

    print(f"Invoked with {data.shape[0]} records")

    # Do the prediction
    try:
        predictions = model_server.predict(data, data_schema)
        # Convert from dataframe to CSV
        with NamedTemporaryFile() as temp:
            predictions.to_csv(temp.name, index=False)
            temp.seek(0)
            return FileResponse(temp.name, media_type="text/csv")
    except Exception as err:
        # Write out an error file. This will be returned as the failureReason to the client.
        trc = traceback.format_exc()
        with open(failure_path, "w") as s:
            s.write("Exception during inference: " + str(err) + "\n" + trc)
        # Printing this causes the exception to be in the training job logs, as well.
        print("Exception during inference: " + str(err) + "\n" + trc, file=sys.stderr)
        # A non-zero exit code causes the training job to be marked as Failed.
        return {
            "success": False,
            "message": f"Exception during inference: {str(err)} (check failure file for more details)",
        }
```

### Description

- run the server (using docker)
- Open postman and make call to `/infer` with the appropriate `csv` as input.
- Returns output as `Internal Server Error`

(PS - in order to test it, you can just use any random csv data, since the failing line should be caught by the exception anyways)

### Operating System

Linux, macOS

### FastAPI Version

0.86.0

### Python Version

Python 3.10.8

### Additional Context

Essentially, when I try to run this with some sample data, the line:
```python
predictions = model_server.predict(data, data_schema)
```
throws an `Exception`, which _should_ be caught by `except` block and subsequently return a JSON with the error message. However, I run into an `Internal Server Error`, with the following traceback:
```python
172.17.0.1 - - [12/Nov/2022:15:14:11 +0000] "POST /infer HTTP/1.1" 500 21 "-" "curl/7.84.0"
Invoked with 17 records
Exception during inference: "['nan'] not in index"
Traceback (most recent call last):
  File "/opt/app/./inference_app.py", line 74, in infer
    predictions = model_server.predict(data, data_schema)
  File "/opt/app/./algorithm/model_server.py", line 76, in predict
    preds_df["prediction"] = pd.DataFrame(preds_df[class_names], columns = class_names).idxmax(axis=1)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 3810, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6111, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6174, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['nan'] not in index"

INFO:      - "POST /infer HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 264, in app
    response = actual_response_class(content, **response_args)
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 299, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 35, in guess_type
    return mimetypes_guess_type(url, strict)
  File "/usr/local/lib/python3.10/mimetypes.py", line 307, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/local/lib/python3.10/mimetypes.py", line 122, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not dict
```

Now, I can/will fix the issue with the `predict` function, but even then, this error shows up (ie, circumventing the function for the time being). I don't understand where exactly the "type" of the response is being used, and what "url" is in this context.

**Comment by JarroVGIT** [comment]
where does `failure_path` comes from? I suspect that is failing..

**Comment by tiangolo** [comment]
Good catch @JarroVGIT ! 🤓😎

Yep, it seems you have an error in your exception handling with the `failure_path`.

**Comment by Pk13055** [comment]
@JarroVGIT No that is not failing since failure path is just a global variable imported from another config. (I have edited the code sample to reflect this)

**Comment by JarroVGIT** [comment]
Fair point. Unfortunately, I am unable to reproduce it on my end, so I am at a loss. It might help to set a breakpoint on starlette/responses.py line 35, to see what the value of `url` is when this error occurs. Maybe that would give a pointer on why that is a dict rather than a URL?

**Comment by Pk13055** [comment]
@JarroVGIT Okay this is very odd, but fixing the issue with the `predictions` function seems to have solved the problem. Additionally, there was an issue with the `NamedTemporaryFile` being out of context when returned, so I had to inject the file as a dependency. But apart from that, the error seems to have magically disappeared. 
(PS - below is the temp file injection, as a reference for anyone who stumbles across this)

```python
async def gen_temp_file(ext: str = ".csv"):
    """Generate a temporary file with a given extension"""
    with NamedTemporaryFile(suffix=ext, delete=True) as temp_file:
        yield temp_file.name

@app.post("/infer", tags=["inference"], response_class=FileResponse)
async def infer(
    input: UploadFile = File(...), temp=Depends(gen_temp_file)
) -> Union[FileResponse, dict]:
    """Do an inference on a single batch of data. In this sample server, we take data as CSV, convert
    it to a pandas data frame for internal use and then convert the predictions back to CSV (which really
    just means one prediction per line, since there's a single column.
    """
    data = None
    # rest of the function remains the same
    ...
```

(Closing the issue)

**Comment by tiangolo** [comment]
Thanks for the help here @JarroVGIT ! 👏  🙇 

Thanks for reporting back and closing the issue @Pk13055  👍
