### ISSUE TITLE
Failed to load API definition due to local variable 'status_code' referenced before assignment in openapi/utils.py line 267

### ISSUE THREAD

**Issue by karenlaw** [tiangolo/fastapi#5651]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Instruction on how to fix the problem is in additional context but I don't know what is causing it so I cannot create a short program that shows the problem and the code I am working on is proprietary so I cannot post it here.
```

### Description

Browse to <url>/docs

### Operating System

macOS

### Operating System Details

Also appear in a linux docker environment

### FastAPI Version

0.76.0

### Python Version

3.8.13

### Additional Context

From openapi/utils.py line 261 

 261               status_code_param = response_signature.parameters.get("status_code")
 262               if status_code_param is not None:
 263                   if isinstance(status_code_param.default, int):
 264                       status_code = str(status_code_param.default)
                       **else:
                               status_code = None**
 265           operation.setdefault("responses", {}).setdefault(status_code, {})[
 266               "description"
 267           ] = route.response_description

The doc load successully if I added the bold text between line 264-265

The following is the error trace:
2022-11-15 17:04:04,518 - uvicorn.access - INFO - 127.0.0.1:61081 - "GET /openapi.json HTTP/1.1" 500
2022-11-15 17:04:04,519 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/applications.py", line 216, in openapi
    return JSONResponse(self.openapi())
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/applications.py", line 191, in openapi
    self.openapi_schema = get_openapi(
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 425, in get_openapi
    result = get_openapi_path(
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 267, in get_openapi_path
    operation.setdefault("responses", {}).setdefault(status_code, {})[
UnboundLocalError: local variable 'status_code' referenced before assignment
2022-11-15 17:05:16,098 - uvicorn.access - INFO - 127.0.0.1:61094 - "GET /docs HTTP/1.1" 200
2022-11-15 17:05:16,195 - uvicorn.access - INFO - 127.0.0.1:61094 - "GET /openapi.json HTTP/1.1" 500
2022-11-15 17:05:16,196 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/applications.py", line 216, in openapi
    return JSONResponse(self.openapi())
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/applications.py", line 191, in openapi
    self.openapi_schema = get_openapi(
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 425, in get_openapi
    )
  File "/Users/karenlaw/.conda/envs/livecheck/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 267, in get_openapi_path
    ] = route.response_description
UnboundLocalError: local variable 'status_code' referenced before assignment

**Comment by yinziyan1206** [comment]
your response class should have a default status_code.

**Comment by karenlaw** [comment]
I added status_code to my response class, it didn't help, still have the error.

Here is my response class:
class ServiceResponse(JSONResponse):
    status_code = 200

    def __init__(self, status: str, message: str, data: Optional[Any] = None):
        self.status = status
        self.message = message
        self.status_code = 200
        if isinstance(data, dict) or (isinstance(data, list) and all(map(isinstance, data, [dict] * len(data)))):
            super(ServiceResponse, self).__init__(data)
        else:
            super(ServiceResponse, self).__init__(str(data))

    def render(self, content: Optional[Any] = None):
        if content:
            if isinstance(content, dict) or (isinstance(content, list) and all(map(isinstance, content, [dict] * len(content)))):
                self.data = content
            else:
                self.data = str(content)
        else:
            self.data = None
        return super(ServiceResponse, self).render({'status': self.status, 'message': self.message, 'data': self.data})

**Comment by yinziyan1206** [comment]
if this is your default response class. you should change your args for __init__ method.

**Comment by tiangolo** [comment]
Thanks for the help here @ycd ! 👏  🙇 

If that solves the original problem, then you can close this issue @karenlaw  ✔️
