### ISSUE TITLE
fastapi0.87.0 - ModuleNotFoundError: No module named 'httpx' while import TestClient from fastapi.testclient

### ISSUE THREAD

**Issue by anoopks12** [tiangolo/fastapi#5656]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
pip insall fastapi

>>> print(fastapi.__version__)
0.87.0

>>> from fastapi.testclient import TestClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\fastapi\testclient.py", line 1, in <module>
    from starlette.testclient import TestClient as TestClient  # noqa
  File "C:\ProgramData\Anaconda3\lib\site-packages\starlette\testclient.py", line 15, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

### Description

Getting error ModuleNotFoundError: No module named 'httpx' while import TestClient from fastapi.testclient.
It looks like an issue specific to the version 0.87.0 (which is released on 13-Nov-2022)
Its working in version 0.86.0

### Operating System

Windows

### FastAPI Version

0.87.0

### Python Version

3.8

**Comment by jgould22** [comment]
Yes, starlette has changed the TestClient to use HTTPX instead of requests and 0.87.0 upgrades starlette.

https://github.com/tiangolo/fastapi/releases/tag/0.87.0

The docs have been updated here https://fastapi.tiangolo.com/tutorial/testing/ to reflect the change.

**Comment by iudeen** [comment]
Just do `pip install httpx` or `pip install fastapi [all] —upgrade`

**Comment by tiangolo** [comment]
Yep, install HTTPX, that's it 🚀

**Comment by ShantanuKumar** [comment]
yeah we use tool like [pants](https://www.pantsbuild.org/) which relies on transitive dependencies being explicit and hence it complains that it can't find `httpx`.  So installing manually transitive dependencies isn't great.

**Comment by iudeen** [comment]
You don't have to manually install if you had used `fastapi[all]`. Check `project.toml` for more understanding on optional dependencies.

Also, since `TestClient` is not needed for "normal" operations, `httpx` is optional as well. 

On a side note, it was clearly mentioned in release notes of both `FastAPI` and `starlette` about transitioning from `requests` to `httpx`

**Comment by pamelafox** [comment]
In terms of best practices, does it seem reasonable to put 'fastapi[all]' in requirements-dev.txt but just 'fastapi' in requirements.txt, so that additional libraries needed for testing are only pulled in development mode? That's my new approach.

**Comment by waderoberts123** [comment]
@pamelafox if you use a package manager like poetry, pdb, or pipenv, you can specify development dependencies so that you can exclude certain dependencies from production instances.
