### ISSUE TITLE
Traceback stack does not show exact place of error

### ISSUE THREAD

**Issue by NewSouthMjos** [tiangolo/fastapi#5740]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import uvicorn
from fastapi import FastAPI, Depends


app = FastAPI()


def get_something_sync():
    yield True


async def get_something_async():
    yield True


@app.get('/1')
def router_func(dependency=Depends(get_something_sync)):
    raise ValueError
    return


@app.get('/2')
def router_func(dependency=Depends(get_something_async)):
    raise ValueError
    return


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=5600, workers=1)
```

### Description

If dependency function uses yield, injecting dependency with sync def function (get_something_sync), the error traceback will broke - it doesn't locate the place where it was rise (should be "/app/main.py", line 24)
calling endpoint /1:
```
fastapi_dependency  | INFO:     10.77.78.83:60070 - "GET /1 HTTP/1.1" 500 Internal Server Error
fastapi_dependency  | ERROR:    Exception in ASGI application
fastapi_dependency  | Traceback (most recent call last):
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
fastapi_dependency  |     result = await app(  # type: ignore[func-returns-value]
fastapi_dependency  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
fastapi_dependency  |     return await self.app(scope, receive, send)
fastapi_dependency  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
fastapi_dependency  |     await super().__call__(scope, receive, send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
fastapi_dependency  |     await self.middleware_stack(scope, receive, send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
fastapi_dependency  |     raise exc
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
fastapi_dependency  |     await self.app(scope, receive, _send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
fastapi_dependency  |     raise exc
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
fastapi_dependency  |     await self.app(scope, receive, sender)
fastapi_dependency  |   File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
fastapi_dependency  |     await self.gen.athrow(typ, value, traceback)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/fastapi/concurrency.py", line 36, in contextmanager_in_threadpool
fastapi_dependency  |     raise e
fastapi_dependency  | ValueError
```

When injecting dependency with async def function (get_something_async), the error traceback seems to be right
endpoint /2:
```
fastapi_dependency  | INFO:     10.77.78.83:60067 - "GET /2 HTTP/1.1" 500 Internal Server Error
fastapi_dependency  | ERROR:    Exception in ASGI application
fastapi_dependency  | Traceback (most recent call last):
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
fastapi_dependency  |     result = await app(  # type: ignore[func-returns-value]
fastapi_dependency  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
fastapi_dependency  |     return await self.app(scope, receive, send)
fastapi_dependency  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
fastapi_dependency  |     await super().__call__(scope, receive, send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
fastapi_dependency  |     await self.middleware_stack(scope, receive, send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
fastapi_dependency  |     raise exc
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
fastapi_dependency  |     await self.app(scope, receive, _send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
fastapi_dependency  |     raise exc
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
fastapi_dependency  |     await self.app(scope, receive, sender)
fastapi_dependency  |   File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
fastapi_dependency  |     await self.gen.athrow(typ, value, traceback)
fastapi_dependency  |   File "/app/main.py", line 13, in get_something_async
fastapi_dependency  |     yield True
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
fastapi_dependency  |     raise e
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
fastapi_dependency  |     await self.app(scope, receive, send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
fastapi_dependency  |     await route.handle(scope, receive, send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
fastapi_dependency  |     await self.app(scope, receive, send)
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
fastapi_dependency  |     response = await func(request)
fastapi_dependency  |                ^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 235, in app
fastapi_dependency  |     raw_response = await run_endpoint_function(
fastapi_dependency  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
fastapi_dependency  |     return await run_in_threadpool(dependant.call, **values)
fastapi_dependency  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
fastapi_dependency  |     return await anyio.to_thread.run_sync(func, *args)
fastapi_dependency  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
fastapi_dependency  |     return await get_asynclib().run_sync_in_worker_thread(
fastapi_dependency  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
fastapi_dependency  |     return await future
fastapi_dependency  |            ^^^^^^^^^^^^
fastapi_dependency  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
fastapi_dependency  |     result = context.run(func, *args)
fastapi_dependency  |              ^^^^^^^^^^^^^^^^^^^^^^^^
fastapi_dependency  |   File "/app/main.py", line 24, in router_func
fastapi_dependency  |     raise ValueError
fastapi_dependency  | ValueError
```

On python 3.10 there were no such a problem. 
Created repo for reproduce the problem: [https://github.com/NewSouthMjos/fastapi_dependency_test](https://github.com/NewSouthMjos/fastapi_dependency_test)
So, should the sync way to inject dependecy show exact plase of where is was raised?

### Operating System

Linux

### Operating System Details

Running in a docker

### FastAPI Version

0.88.0

### Python Version

3.11

### Additional Context

uvicorn[standard]==0.20.0

**Comment by extreme4all** [comment]
The /1 endpoint does not throw a ValueError because the get_something_sync function is a generator function that uses yield instead of return. When a function uses yield, it becomes a generator and the code inside the function is not executed until the generator is iterated over. In this case, the get_something_sync function is never actually called, so the ValueError is never raised.

If you want the /1 endpoint to raise a ValueError, you should either use a return statement instead of yield in the get_something_sync function, or you should call the generator and iterate over it to execute the code inside the function. 

When you use Depends() with a synchronous generator function, it is not able to handle the generator object returned by the function, and this can cause errors. In contrast, when you use Depends() with an asynchronous generator function, it is able to automatically handle the asynchronous nature of the function and await on the generator object, allowing it to be executed correctly.

**Comment by NewSouthMjos** [comment]
1 - but the code actually throws ValueError, we can see it in last row of logs
2 - func get_something_async is generator too, but it works as espected

>In this case, the get_something_sync function is never actually called, so the ValueError is never raised.

I don't think so:

```
import uvicorn
from fastapi import FastAPI, Depends


app = FastAPI()


def get_something_sync():
    yield 'get_something_sync was executed'


async def get_something_async():
    yield True


@app.get('/1')
def router_func(dependency=Depends(get_something_sync)):
    return dependency


@app.get('/2')
def router_func(dependency=Depends(get_something_async)):
    raise ValueError
    return


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=5600, workers=1)
```

Now /1 returns text "get_something_sync was executed"

From FastAPI docs: 
https://fastapi.tiangolo.com/tutorial/dependencies/#to-async-or-not-to-async
>You can use async def or normal def

https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/
but all the examples with yield consctructs with `async def`

**Comment by sombek** [comment]
@NewSouthMjos I think it's not related to async functions

I am facing the same issue with python 3.11.1
After testing I found that it's related `yield` in the dependency.

I tried to run the same setup with python 3.10.8, I am able to see the exception to the exact statement.

Having `yield` in the dependency is important for me, since I am using sessions with `sqlalchemy`. To be able to rollback the session in case of exception. and closing the session.

**Comment by sombek** [comment]
@NewSouthMjos Any idea about how to get this fixed?

**Comment by azhard4int** [comment]
I am facing the same issue with Python 3.11.  Previously, it was showing the exact stack trace.

```
File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/fastapi/concurrency.py", line 36, in contextmanager_in_threadpool
    raise e
IndexError: list index out of range
```
