### ISSUE TITLE
RuntimeError using asynpcg and fastapi running async function: Task attached to a different loop

### ISSUE THREAD

**Issue by stefanodvx** [tiangolo/fastapi#5790]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# api.py
from fastapi import FastAPI

class API:
    def __init__(self, client):
        self.app = FastAPI()
        self.client = client

    async def get_user_locker(self, user_id: int):
        locker = await self.client.database.get_user_locker(user_id)
        characters = self.client.characters.get_by_id(locker)
        return characters

# main.py
from telegram import TelegramClient
from api import API

from threading import Thread

import asyncio
import uvicorn
import sys

async def start():

    client = TelegramClient("test")
    await client.start()

    api = API(client)
    api.app.add_api_route("/locker/{user_id}", api.get_user_locker)

    Thread(target=lambda: uvicorn.run(
            api.app, host="0.0.0.0", port=5002
    ), daemon=True).start()
 
    await client.database.init()
    print("Client started as @{}".format(client.me.username))   
    while True:
        await asyncio.sleep(600)

if __name__ == "__main__":
    try:
        asyncio.run(start())
    except KeyboardInterrupt:
        print("Shutting down...")
        sys.exit(0)

# telegram.py
from characters import Characters
from database import Database

import pyrogram
import json

class TelegramClient(pyrogram.Client):
    def __init__(self, name):
        super().__init__(
            name="sessions/" + name,
            api_id="123",
            api_hash="abc",
            plugins=dict(root="handlers")
        )
        self.banned_list = []
        self.translations = json.load(open("translations.json"))
        self.database = Database(database="waifu")
        self.characters = Characters("char.json", lambda x: x.likes >= 50)

    def get_translation(self, name, language):
        try:
            return self.translations[name][language]
        except:
            return "TRANSLATION_NOT_FOUND"

    async def spawn(self, group: dict):
        chat_id = group["chat_id"]
        character = await self.characters.get_random()
        await self.database.set_current(chat_id, character.id)
        return await self.send_photo(chat_id, character.image,
            caption=self.get_translation("character_spawned", group["language"]), 
        )
```

### Description

I run the script. Everything works fine. But, when i reach the endpoint `/locker/user_id`, I get an Internal Error. Checking the shell i see a huge traceback. The database i use is PosgteSQL with asyncpg module. The error raises when an async function is ran in the FastAPI handler. I can run the same function totally fine outside of FastAPI:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/wicked/.local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/wicked/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/wicked/.local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/wicked/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/wicked/.local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/wicked/.local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/wicked/.local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/wicked/.local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/wicked/bots/waifu/api.py", line 9, in get_user_locker
    locker = await self.client.database.get_user_locker(user_id)
  File "/home/wicked/bots/waifu/database.py", line 31, in get_user_locker
    query = await self.conn.fetchrow("SELECT locker FROM users WHERE user_id = $1;", user_id)
  File "/home/wicked/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 678, in fetchrow
    data = await self._execute(
  File "/home/wicked/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "/home/wicked/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
  File "/home/wicked/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 1710, in _do_execute
    stmt = await self._get_statement(
  File "/home/wicked/.local/lib/python3.9/site-packages/asyncpg/connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
RuntimeError: Task <Task pending name='Task-52' coro=<RequestResponseCycle.run_asgi() running at /home/wicked/.local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py:419> cb=[set.discard()]> got Future <Future pending cb=[Protocol._on_waiter_completed()]> attached to a different loop
```

### Operating System

Linux

### Operating System Details

Debian 11

### FastAPI Version

0.88.0

### Python Version

Python 3.9.2

**Comment by jgould22** [comment]
You are spawning running uvicorn in a different thread and it is starting a different loop from the one your database client which is probably starting its own loop.

Then you are trying to access your database from the thread you spawned uvicorn on and it doesnt work because you essentially awaiting tasks from one loop on another.

Either dont spawn the uvicorn instance in another thread or figure out how to get the current loop and pass it to both ( I am not sure if you can set the loop for Uvicorn or the Telegram client.

**Comment by stefanodvx** [comment]
@jgould22 hi. thank you for replying. i ran uvicorn using another Thread so it won't block my code and make the other stuff execute normally :D 

I'm very noob with asyncio, so I have no clue about how get the loop and use it. I'll be glad if you could help me more 😁

**Comment by jgould22** [comment]
Are you actually doing anything in that 
```
    while True:
        await asyncio.sleep(600)
```
or is it just part of the example you have here ?

**Comment by stefanodvx** [comment]
@jgould22 i do it to "idle" the script so it wont block, but its not cause of the problem

**Comment by stefanodvx** [comment]
@jgould22 i can't run uvicorn directly. this code here:
```py
async def start():

    client = TelegramClient("test")
    await client.start()

    api = API(client)
    api.app.add_api_route("/locker/{user_id}", api.get_user_locker)

    # Thread(target=lambda: uvicorn.run(
    #         api.app, host="0.0.0.0", port=5002
    # ), daemon=True).start()
 
    await client.database.init()
    print("Client started as @{}".format(client.me.username))

    uvicorn.run(api.app, host="0.0.0.0", port=5002) 
    # while True:
    #     await asyncio.sleep(600)
```

will give me this error:
```
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'Server.serve' was never awaited
```

**Comment by jgould22** [comment]
Sorry I was not clear, I mean like  they describe here in the uvicorn docs 
https://www.uvicorn.org/#config-and-server-instances

**Comment by stefanodvx** [comment]
This worked. Now everything works fine. Thank you so much :D
