### ISSUE TITLE
Relationship fails with 

### ISSUE THREAD

**Issue by KamilKleina** [tiangolo/fastapi#5909]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
class OccupyReasonBase(BaseModel):
    group_id: Optional[int] = None
    tenant_id: Optional[int] = None
    other: Optional[str] = None


class OccupyReasonCreate(OccupyReasonBase):
    pass


class OccupyReasonUpdate(BaseModel):
    group_id: Optional[int] = None
    tenant_id: Optional[int] = None
    other: Optional[str] = None


class OccupyReason(OccupyReasonBase):
    id: int

    class Config:
        orm_mode = True


class EventBase(BaseModel):
    start: int
    end: int
    repeat: str
    occupy_reason: list[OccupyReason]
    hall_id: int
    title: Optional[str] = ""
    comment: Optional[str] = ""


class EventCreate(EventBase):
    pass


class EventUpdate(BaseModel):
    start: Optional[int] = None
    end: Optional[int] = None
    repeat: Optional[str] = None
    occupy_reason: Optional[list[OccupyReason]] = None
    hall_id: Optional[int] = None
    title: Optional[str] = ""
    comment: Optional[str] = ""


class Event(EventBase):
    id: int
    approved: bool
    created_by_admin: bool

    class Config:
        orm_mode = True

class OccupyReason(Base):
    __tablename__ = "occupy_reasons"

    id = Column(Integer, primary_key=True, index=True)
    event = relationship("Event", back_populates="occupy_reason")
    event_id = Column(Integer, ForeignKey("events.id"))
    group_id = Column(Integer)
    tenant_id = Column(Integer)
    other = Column(String)


class Event(Base):
    __tablename__ = "events"

    id = Column(Integer, primary_key=True, index=True)
    start = Column(Integer)
    end = Column(Integer)
    repeat = Column(String)
    title = Column(String)
    comment = Column(String)
    approved = Column(Boolean)
    created_by_admin = Column(Boolean)
    occupy_reason = relationship("OccupyReason", back_populates="event")
    school_owner_id = Column(Integer, ForeignKey("schools.id"))
    school_owner = relationship("School", back_populates="events")
    hall_id = Column(Integer, ForeignKey("halls.id"))
```

### Description

I am trying to create a relationship to send nested JSON:
```
{
  "start": 0,
  "end": 0,
  "repeat": "string",
  "occupy_reason": [
    {
      "group_id": 0,
      "tenant_id": 0,
      "other": "string",
      "id": 0
    }
  ],
  "hall_id": 1,
  "title": "",
  "comment": ""
}
```
 But it fails with the below error:

```
INFO:     Will watch for changes in these directories: ['/code']

INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

INFO:     Started reloader process [7] using StatReload

INFO:     Started server process [9]

INFO:     Waiting for application startup.

INFO:     Application startup complete.

INFO:     172.19.0.2:60650 - "GET /docs HTTP/1.1" 200 OK

INFO:     172.19.0.2:60650 - "GET /openapi.json HTTP/1.1" 200 OK

INFO:     172.19.0.2:56336 - "POST /token HTTP/1.1" 200 OK

INFO:     172.19.0.2:50890 - "POST /users/me/schools/events/?school_id=1 HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__

    await super().__call__(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__

    raise exc

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__

    await self.app(scope, receive, _send)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__

    await self.simple_response(scope, receive, send, request_headers=headers)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__

    raise exc

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__

    await self.app(scope, receive, sender)

  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__

    raise e

  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__

    await route.handle(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app

    response = await func(request)

  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app

    raw_response = await run_endpoint_function(

  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(

  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread

    return await future

  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run

    result = context.run(func, *args)

  File "/code/calendars/main.py", line 110, in create_event_for_school

    return crud.create_event_for_school(db=db, item=item, school_id=school_id)

  File "/code/calendars/api/crud.py", line 189, in create_event_for_school

    db_event = models.Event(**item.dict(), school_owner_id=school_id, approved=True, created_by_admin=True)

  File "<string>", line 4, in __init__

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance

    with util.safe_reraise():

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

    compat.raise_(

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_

    raise exception

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance

    return manager.original_init(*mixed[1:], **kwargs)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1200, in _declarative_constructor

    setattr(self, k, kwargs[k])

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 460, in __set__

    self.impl.set(

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1609, in set

    collections.bulk_replace(

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/collections.py", line 843, in bulk_replace

    appender(member, _sa_initiator=initiator)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/collections.py", line 1169, in append

    item = __set(self, item, _sa_initiator)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/collections.py", line 1134, in __set

    item = executor.fire_append_event(item, _sa_initiator)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/collections.py", line 753, in fire_append_event

    return self.attr.fire_append_event(

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1430, in fire_append_event

    value = fn(state, value, initiator or self._append_token)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1772, in emit_backref_from_collection_append_event

    child_state, child_dict = instance_state(child), instance_dict(child)

AttributeError: 'dict' object has no attribute '_sa_instance_state'
```

I am not sure where I go wrong since that relationship, If I comment out everything about OccupancyReason, it does work. 

### Operating System

Linux

### FastAPI Version

0.89.1

### Python Version

3.10.9

**Comment by ThirVondukr** [comment]
Seems like you're trying to create a sqlalchemy model by simply destructuring pydantic model via `BaseModel.dict`, this won't work with a relationship (`EventBase.occupy_reason`).
You need to create your related model manually:
```py
schema = EventCreate(...)

occupy_reason = OccupyReason(**schema.occupy_reason.dict())
event = Event(
    **schema.dict(exclude={"occupy_reason"},
    occupy_reason=occupy_reason,
)
```

**Comment by KamilKleina** [comment]
@ThirVondukr Thank you for that. It does work now :) 

So my next question would be about update:

```
def update_event_for_school(db: Session, event_id: int, event: models.Event, school_id: int, user_id: int):
    # TODO should check if school_id belongs to current_user?
    db_event = get_event_by_id(db, school_id, event_id)
    if not db_event:
        raise HTTPException(status_code=404, detail="Event not found.")
    event_data = event.dict(exclude_unset=True)
    for key, value in event_data.items():
        setattr(db_event, key, value)

    db.add(db_event)
    try:
        db.commit()
        db.refresh(db_event)
    except exc.SQLAlchemyError as error:
        print(error)
        credentials_exception = HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Provided data are not correct.",
            headers={"WWW-Authenticate": "Bearer"},
        )
        raise credentials_exception
    return db_even
    
    
@app.patch("/users/me/schools/events/{event_id}", response_model=schemas.Event)
def update_event_for_school(
    school_id: int,
    event_id: int,
    event: schemas.EventUpdate,
    current_user: schemas.User = Depends(crud.get_current_user),
    db: Session = Depends(get_db),
):
    db_event = crud.update_event_for_school(db, event_id, event, school_id, current_user.id)
    return db_even
```

On /docs I can see that it has "id" for some reason, how do I change that?
```
{
  "start": 0,
  "end": 0,
  "repeat": "string",
  "occupy_reason": {
    "group_id": 0,
    "tenant_id": 0,
    "other": "yes",
    "id": 0
  },
  "hall_id": 0,
  "title": "",
  "comment": ""
}
```

Also How do I change my code to make update also work?

**Comment by moadennagi** [comment]
The example [ThirVondukr](https://github.com/ThirVondukr) provided includes everything you need to do, you would have to exclude the related_field on the update also. 
```python
event_data = event.dict(exclude_unset=True, exclude={'occupy_reason')
    for key, value in event_data.items():
        setattr(db_event, key, value)
if event.occupy_reason:
    occupy_reason = OccupyReason(**event.occupy_reason.dict())
    db_event.occupy_reason = occupy_reason
# session add, commit and refresh
```
