### ISSUE TITLE
Assertion error when connecting to Websocket

### ISSUE THREAD

**Issue by mturoci** [tiangolo/fastapi#5939]
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import os
from fastapi import FastAPI, WebSocket
from fastapi.staticfiles import StaticFiles

app = FastAPI()
curr_dir = os.path.dirname(os.path.abspath(__file__))
app.mount("/", StaticFiles(directory=os.path.join(curr_dir, 'folder'), html=True), name="/")


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        await websocket.send_text(f"Message text was: {data}")
```

### Description

Probably a config error. I am trying to serve a static directory which also contains an index.html. The index.html includes a JS to connect to a WS. I used code from the [docs](https://fastapi.tiangolo.com/advanced/websockets/?h=webso#websockets-client). Although the scenario is super simple, I get:

```sh
(venv)  uvicorn foo:app --reload
INFO:     Will watch for changes in these directories: ['/Users/martinturoci/go/src/github.com/h2oai/telesync/py/h2o_wavelite/examples']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [29798] using StatReload
INFO:     Started server process [29802]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:57550 - "GET /index.html HTTP/1.1" 304 Not Modified
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 238, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/martinturoci/go/src/github.com/h2oai/telesync/py/venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 94, in __call__
    assert scope["type"] == "http"
AssertionError
INFO:     connection open
INFO:     connection closed
```

Folder structure:

`foo.py` contains the code referenced above. A directory named `folder` next to the `foo.py`, containing `index.html`.

Index.html contents

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Foo</title>
</head>
<body>
  <h1>WebSocket Chat</h1>
  <form action="" onsubmit="sendMessage(event)">
    <input type="text" id="messageText" autocomplete="off" />
    <button>Send</button>
  </form>
  <ul id='messages'>
  </ul>
  <script>
    var ws = new WebSocket("ws://localhost:8000/ws")
    ws.onmessage = function (event) {
      var messages = document.getElementById('messages')
      var message = document.createElement('li')
      var content = document.createTextNode(event.data)
      message.appendChild(content)
      messages.appendChild(message)
    }
    function sendMessage(event) {
      var input = document.getElementById("messageText")
      ws.send(input.value)
      input.value = ''
      event.preventDefault()
    }
  </script>
</body>
</html>
```

Possibly related to https://github.com/elastic/apm-agent-python/issues/1186

### Operating System

macOS

### FastAPI Version

0.89.1

### Python Version

Python 3.9.13

**Comment by yinziyan1206** [comment]
You should mount the statistic file after the function `websocket_endpoint`. The router matches '/' when you send the websocket

**Comment by mturoci** [comment]
Thanks @yinziyan1206. This indeed resolved the issue, just wondering if the registration order should matter. Is this a common practice when developing APIs?

**Comment by Kludex** [comment]
https://fastapi.tiangolo.com/tutorial/path-params/?h=order+matters#order-matters

**Comment by mturoci** [comment]
Thanks @Kludex!
