### ISSUE TITLE
[BUG] openapi generation crashes for Models with nested `None`

### ISSUE THREAD

**Issue by lutostag** [tiangolo/fastapi#776]
First off I wanted to say thanks for a great project, took it for a spin, and found this tiny thing. Hope I can help to get it fixed correctly upstream so others don't run into it :)

### Describe the bug

openapi fails to generate in certain cases -- where there is a None inside of another structure for the models exposed via openapi

### To Reproduce

1. Create a file with:

```Python
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class Model(BaseModel):
    state = [None]

@app.post("/")
def post(model: Model):
    return {}
```
2. Run it with `uvicorn main:app`
3. Open the browser and call the endpoint `/openapi.json`.
4. It raises a 500 Internal Server Error.
5. But I expected it to return a valid openapi.json

### Expected behavior

Add a clear and concise description of what you expected to happen.

### Logs

```
Traceback (most recent call last):
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/fastapi/applications.py", line 97, in openapi
    return JSONResponse(self.openapi())
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/fastapi/applications.py", line 89, in openapi
    openapi_prefix=self.openapi_prefix,
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 281, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "/home/lutostag/.virtualenvs/fastapi/lib/python3.7/site-packages/fastapi/utils.py", line 76, in get_model_definitions
    model, model_name_map=model_name_map, ref_prefix=REF_PREFIX
  File "pydantic/schema.py", line 465, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 494, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 191, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 745, in genexpr
  File "pydantic/schema.py", line 745, in genexpr
  File "pydantic/schema.py", line 749, in pydantic.schema.encode_default
  File "pydantic/json.py", line 59, in pydantic.json.pydantic_encoder
TypeError: Object of type 'NoneType' is not JSON serializable
```

### Environment

- OS: Ubuntu 18.04.3
- fastapi version = 0.44.1
- Python 3.7.4

pip freeze
```bash
Click==7.0
fastapi==0.44.1
h11==0.8.1
httptools==0.0.13
pydantic==1.2
starlette==0.12.9
uvicorn==0.10.8
uvloop==0.14.0
websockets==8.1
```
### Additional context
I can fix the bug by making the following changes internal to pydantic -- https://github.com/samuelcolvin/pydantic/compare/master...lutostag:json_None

I wanted to drop you a line first in case they do not want to extend the code that way, seems like the `json_encoder` is supposed to be used as a fallback rather than a first round of coercion. Do you think it is better fixed in this repo, because it is a pydantic internal method being used, and I cannot reproduce the issue with just pydantic on its own?

Thanks again for a great project!

**Comment by dmontagu** [comment]
This is interesting; not sure why that change to pydantic fixes it; @samuelcolvin any thoughts?

**Comment by dmontagu** [comment]
Okay, this definitely looks to be a bug in pydantic and not FastAPI, but I'm having a hard time understanding why things are misbehaving. In particular, using a default of `None` doesn't raise an issue; it's not immediately obvious to me where the divergence in logic would be.

@samuelcolvin It looks like it needs a change to either `pydantic_encoder` or `encode_default`, so that `None` can be handled by `encode_default`.

**Comment by dmontagu** [comment]
By the way, here is a minimal reproduction of the issue:
```python
from pydantic import BaseModel

class Model(BaseModel):
    state = [None]

Model.schema()
```

@lutostag if you'd like to submit a PR to pydantic making the change to `pydantic.schema.encode_default` (and adding a test that the above snippet stops raising an error), that would be great! Otherwise, let us know and I'll take care of it at some point soon.

**Comment by lutostag** [comment]
Cool, will do. Thanks for digging in a bit further! Will close this one for now. And submit it properly up there. 👍

**Comment by tiangolo** [comment]
Awesome, thanks for the discussion here and for implementing the fix in Pydantic! :bow: :clap:
