### ISSUE TITLE
[QUESTION] OAuth2: how to store the access_token in a cookie

### ISSUE THREAD

**Issue by nskalis** [tiangolo/fastapi#796]
### First check

* [ x] I used the GitHub search to find a similar issue and didn't find it.
* [ x] I searched the FastAPI documentation, with the integrated search.
* [ x] I already searched in Google "How to X in FastAPI" and didn't find any information.

### Description

How can I save the `access_token` in a cookie in case of OAuth2 ?

When we do `return {"access_token": access_token, "token_type": "bearer"}` and
we use the `OAuth2PasswordBearerWithCookie` as `oauth2_scheme` everything works based on OpenAPI client.
```
@app.post("/token", response_model=Token)
async def login_for_access_token(
    form_data: fastapi.security.OAuth2PasswordRequestForm = fastapi.Depends(),
):
    user = authenticate_user(form_data.username, form_data.password)
    if not user:
        raise fastapi.HTTPException(
            status_code=starlette.status.HTTP_400_BAD_REQUEST,
            detail="Incorrect username or password",
        )
    access_token_expires = datetime.timedelta(
        minutes=settings.JWT_ACCESS_TOKEN_EXPIRE_MINUTES
    )
    access_token = create_access_token(
        data={
            "sub": user.username,
            "scopes": settings.OAUTH2_SCHEME_SCOPES,  # form_data.scopes
        },
        expires_delta=access_token_expires,
    )
    # return {"access_token": access_token, "token_type": "bearer"}
    response = starlette.responses.Response(
        {"access_token": access_token, "token_type": "bearer"},
        status_code=starlette.status.HTTP_200_OK,
    )
    response.set_cookie(
        key="Authorization",
        value="Bearer {}".format(fastapi.encoders.jsonable_encoder(access_token)),
        httponly=True,
        max_age=60 * 60,
        expires=60 * 60,
        domain="glass.ip-spotlight.xxx.xxx",
    )
    return response
```

Is it possible to set a cookie while returning `{"access_token": access_token, "token_type": "bearer"}` so that I can test it with OpenAPI client ? 
The above fails with:
```
 File "/usr/local/lib/python3.6/site-packages/starlette/responses.py", line 42, in __init__
    self.body = self.render(content)
  File "/usr/local/lib/python3.6/site-packages/starlette/responses.py", line 54, in render
    return content.encode(self.charset)
AttributeError: 'dict' object has no attribute 'encode'
```
**Do you know perhaps why is so?**

On top of that, when I return sth like:
```
response = starlette.responses.RedirectResponse(
        url=app.url_path_for("looking_glass_applications")
    )
    response.set_cookie(
        key="Authorization",
        value="Bearer {}".format(fastapi.encoders.jsonable_encoder(access_token)),
        httponly=True,
        max_age=60 * 60,
        expires=60 * 60,
        domain="glass.ip-spotlight.aorta.net",
    )
    return response
```

and then visit:
```
@app.get("/apps/test")
async def lookup_bgp_network_prefix(
    current_user: User = fastapi.Security(get_current_active_user, scopes=["bgp"])
):
    return starlette.responses.JSONResponse(
        status_code=starlette.status.HTTP_200_OK, content={"resp": "xxx"}
    )
```
I get an error saying:
```
    response = await func(request)
  File "/usr/local/lib/python3.6/site-packages/fastapi/routing.py", line 119, in app
    dependency_overrides_provider=dependency_overrides_provider,
  File "/usr/local/lib/python3.6/site-packages/fastapi/dependencies/utils.py", line 490, in solve_dependencies
    dependency_cache=dependency_cache,
  File "/usr/local/lib/python3.6/site-packages/fastapi/dependencies/utils.py", line 490, in solve_dependencies
    dependency_cache=dependency_cache,
  File "/usr/local/lib/python3.6/site-packages/fastapi/dependencies/utils.py", line 507, in solve_dependencies
    if sub_dependant.use_cache and sub_dependant.cache_key in dependency_cache:
TypeError: unhashable type: 'OAuth2PasswordBearerWithCookie'
```

**Could you please advise how to make OAuth2 to work based on a cookie (for example) ?**

### Additional context

I am using the class described here https://github.com/tiangolo/fastapi/issues/480 is an extension of the `OAuth2PasswordBearer` class which now includes checking for an Authorization header and an Authorization cookie. This will use a header as preference and falls back to a cookie.
Furthermore, you have to create the object of `OAuth2PasswordBearerWithCookie` and use this instead of the `OAuth2PasswordBearer` class (https://github.com/tiangolo/fastapi/blob/master/fastapi/security/oauth2.py).

```
class OAuth2PasswordBearerWithCookie(fastapi.openapi.models.OAuth2):
    def __init__(
        self,
        tokenUrl: str,
        scheme_name: str = None,
        scopes: dict = None,
        auto_error: bool = True,
    ):
        if not scopes:
            scopes = {}
        flows = fastapi.openapi.models.OAuthFlows(
            password={"tokenUrl": tokenUrl, "scopes": scopes}
        )
        super().__init__(flows=flows, scheme_name=scheme_name, auto_error=auto_error)

    async def __call__(
        self, request: starlette.requests.Request
    ) -> typing.Optional[str]:
        header_authorization: str = request.headers.get("Authorization")
        cookie_authorization: str = request.cookies.get("Authorization")
        header_scheme, header_param = get_authorization_scheme_param(
            header_authorization
        )
        cookie_scheme, cookie_param = get_authorization_scheme_param(
            cookie_authorization
        )
        if header_scheme.lower() == "bearer":
            authorization = True
            scheme = header_scheme
            param = header_param

        elif cookie_scheme.lower() == "bearer":
            authorization = True
            scheme = cookie_scheme
            param = cookie_param
        else:
            authorization = False

        if not authorization or scheme.lower() != "bearer":
            if self.auto_error:
                raise HTTPException(
                    status_code=starlette.status.HTTP_401_UNAUTHORIZED,
                    detail="Not authenticated",
                    headers={"WWW-Authenticate": "Bearer"},
                )
            else:
                return None
        return param


oauth2_scheme = OAuth2PasswordBearerWithCookie(  # fastapi.security.OAuth2PasswordBearer
    tokenUrl="/token",
    scopes={
        "me": "diagnostics about the current user",
        "bgp": "capabilities about bgp route lookup",
    },
)
```

**Comment by dmontagu** [comment]
> Do you know perhaps why is so?

I think the source of your first error is using `starlette.responses.Response` instead of `JSONResponse`:

```python
    response = starlette.responses.Response(
        {"access_token": access_token, "token_type": "bearer"},
        status_code=starlette.status.HTTP_200_OK,
    )
```

If you use the base `Response` you need to pass it `bytes` instead of a json-encodable object. If you use `JSONResponse` instead, it should at least address the first traceback you are getting.

-----

For the `TypeError: unhashable type: 'OAuth2PasswordBearerWithCookie'` issue, I think it would help to see more of a self-contained reproducible example. In particular, if you could show the code for `get_current_active_user` that would help (and might be enough on its own).

**Comment by nskalis** [comment]
thanks @dmontagu for looking at it, I appreciate it a lot.

Here is a more complete sample:
```
class OAuth2PasswordBearerWithCookie(fastapi.openapi.models.OAuth2):
    def __init__(
        self,
        tokenUrl: str,
        scheme_name: str = None,
        scopes: dict = None,
        auto_error: bool = True,
    ):
        if not scopes:
            scopes = {}
        flows = fastapi.openapi.models.OAuthFlows(
            password={"tokenUrl": tokenUrl, "scopes": scopes}
        )
        super().__init__(flows=flows, scheme_name=scheme_name, auto_error=auto_error)

    async def __call__(
        self, request: starlette.requests.Request
    ) -> typing.Optional[str]:
        header_authorization: str = request.headers.get("Authorization")
        cookie_authorization: str = request.cookies.get("Authorization")
        header_scheme, header_param = get_authorization_scheme_param(
            header_authorization
        )
        cookie_scheme, cookie_param = get_authorization_scheme_param(
            cookie_authorization
        )
        if header_scheme.lower() == "bearer":
            authorization = True
            scheme = header_scheme
            param = header_param

        elif cookie_scheme.lower() == "bearer":
            authorization = True
            scheme = cookie_scheme
            param = cookie_param
        else:
            authorization = False

        if not authorization or scheme.lower() != "bearer":
            if self.auto_error:
                raise HTTPException(
                    status_code=starlette.status.HTTP_401_UNAUTHORIZED,
                    detail="Not authenticated",
                    headers={"WWW-Authenticate": "Bearer"},
                )
            else:
                return None
        return param


oauth2_scheme = fastapi.security.OAuth2PasswordBearer(  # OAuth2PasswordBearerWithCookie
    tokenUrl="/token",
    scopes={
        "me": "diagnostics about the current user",
        "bgp": "capabilities about bgp route lookup",
    },
)

app = fastapi.FastAPI()


class Token(pydantic.BaseModel):
    access_token: str
    token_type: str


class TokenData(pydantic.BaseModel):
    username: str = None
    scopes: typing.List[str] = []


class User(pydantic.BaseModel):
    username: str
    disabled: bool = None


class UserInLdap(User):
    hashed_password: str


def verify_password(plain_password, hashed_password):
    return passlib_context.verify(plain_password, hashed_password)


def get_password_hash(password):
    return passlib_context.hash(password)


def get_user(conn, username: str):
    curs = conn.cursor()
    curs.execute(queries.Q["sqlite"]["select_user"], (username,))
    records = curs.fetchone()
    if records:
        user_dict = {
            "username": records["username"],
            "hashed_password": records["hashed_password"],
            "disabled": records["disabled"],
        }
        return UserInLdap(**user_dict)


def authenticate_user(username: str, password: str):
    authn.is_user_identity_managed(username, password)
    user = get_user(db_conn, username)
    if not user:
        return False
    if not verify_password(password, user.hashed_password):
        return False
    return user


def create_access_token(*, data: dict, expires_delta: datetime.timedelta = None):
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.datetime.utcnow() + expires_delta
    else:
        expire = datetime.datetime.utcnow() + datetime.timedelta(minutes=15)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(
        to_encode, settings.JWT_SECRET_KEY, algorithm=settings.JWT_ALGORITHM
    )
    return encoded_jwt


async def get_current_user(
    security_scopes: fastapi.security.SecurityScopes,
    token: str = fastapi.Depends(oauth2_scheme),
):
    if security_scopes.scopes:
        authenticate_value = 'Bearer scope="{}"'.format(security_scopes.scope_str)
    else:
        authenticate_value = "Bearer"
    credentials_exception = fastapi.HTTPException(
        status_code=starlette.status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": authenticate_value},
    )
    try:
        payload = jwt.decode(
            token, settings.JWT_SECRET_KEY, algorithms=[settings.JWT_ALGORITHM]
        )
        username: str = payload.get("sub")
        if username is None:
            raise credentials_exception
        token_scopes = payload.get("scopes", [])
        token_data = TokenData(scopes=token_scopes, username=username)
    except (jwt.PyJWTError, pydantic.ValidationError):
        raise credentials_exception
    user = get_user(db_conn, username=token_data.username)
    if user is None:
        raise credentials_exception
    for scope in security_scopes.scopes:
        if scope not in token_data.scopes:
            raise fastapi.HTTPException(
                status_code=starlette.status.HTTP_401_UNAUTHORIZED,
                detail="Not enough permissions",
                headers={"WWW-Authenticate": authenticate_value},
            )
    return user


async def get_current_active_user(
    current_user: User = fastapi.Security(get_current_user, scopes=["me"])
):
    if current_user.disabled:
        raise fastapi.HTTPException(
            status_code=starlette.status.HTTP_400_BAD_REQUEST, detail="Inactive user"
        )
    return current_user


@app.post("/token", response_model=Token)
async def login_for_access_token(
    form_data: fastapi.security.OAuth2PasswordRequestForm = fastapi.Depends(),
):
    user = authenticate_user(form_data.username, form_data.password)
    if not user:
        raise fastapi.HTTPException(
            status_code=starlette.status.HTTP_400_BAD_REQUEST,
            detail="Incorrect username or password",
        )
    access_token_expires = datetime.timedelta(
        minutes=settings.JWT_ACCESS_TOKEN_EXPIRE_MINUTES
    )
    access_token = create_access_token(
        data={
            "sub": user.username,
            "scopes": settings.OAUTH2_SCHEME_SCOPES,  # form_data.scopes
        },
        expires_delta=access_token_expires,
    )
    # return {"access_token": access_token, "token_type": "bearer"}
    response = starlette.responses.JSONResponse(
        content={"access_token": access_token, "token_type": "bearer"},
        status_code=starlette.status.HTTP_200_OK,
    )
    # response.set_cookie(
    #     key="Authorization",
    #     value="Bearer {}".format(fastapi.encoders.jsonable_encoder(access_token)),
    #     httponly=True,
    #     max_age=60 * 60,
    #     expires=60 * 60,
    #     domain="glass.ip-spotlight.aorta.net",
    # )
    return response
```

the above `login_for_access_token` complains with an error `TypeError: Object of type 'bytes' is not JSON serializable` 

PS. the `authn.is_user_identity_managed` is just a function that queries a LDAP server and saves the `username` and `hashed_password` into SQLite

**Comment by nskalis** [comment]
ok, this worked, I am not sure if there is sth more elegant:

```
    response = starlette.responses.JSONResponse(
        content=fastapi.encoders.jsonable_encoder({"access_token": access_token, "token_type": "bearer"}),
        status_code=starlette.status.HTTP_200_OK,
    )
    response.set_cookie(
        key="Authorization",
        value="Bearer {}".format(fastapi.encoders.jsonable_encoder(access_token)),
        httponly=True,
        max_age=60 * 60,
        expires=60 * 60,
        domain="glass.ip-spotlight.xxx.xxx",
    )
    return response
```

**Comment by dmontagu** [comment]
@nskalis Can you check if adding this line fixes the problem:

```python
class OAuth2PasswordBearerWithCookie(OAuth2):
    ...
    __hash__ = lambda obj: id(obj)  # <-------- this line
```

FastAPI tries to hash dependencies so they can be looked up and reused rather than re-computed. I'm guessing the problem here is just that your dependency isn't hashable, unlike most typical dependencies (which are functions or types). Adding that `__hash__ = ...` line makes the instance hash by identity, which is the usual default implementation, and I believe is the proper semantics for your use case anyway.

-----

The reason it isn't already hashable is that pydantic provides an `__eq__` method for `BaseModel`  subclasses, but does not provide `__hash__` (presumably because not all models could/should, be treated as hashable, and so it is your responsibility to implement it yourself if you know it should be okay to do so). Python makes a type unhashable specifically when it implements `__eq__` but not `__hash__`.

**Comment by dmontagu** [comment]
Regarding whether there is a better way to handle adding the cookie to the response -- I think we could modify the `fastapi.dependencies.utils.solve_dependencies` function to read cookies off the injected `Response`-type argument. It already does this with headers and status code; I'm assuming adding support for cookies would be straightforward.

@tiangolo is there a good reason we don't support cookies on the injected response argument?

**Comment by nskalis** [comment]
@dmontagu thank you so much for the eye-opener.

Now, the class definition `OAuth2PasswordBearerWithCookie` and `oauth2_scheme` look like this:
```
class OAuth2PasswordBearerWithCookie(fastapi.openapi.models.OAuth2):

    __hash__ = lambda obj: id(obj)

    def __init__(
        self,
        tokenUrl: str,
        scheme_name: str = None,
        scopes: dict = None,
        auto_error: bool = True,
    ):
        if not scopes:
            scopes = {}
        flows = fastapi.openapi.models.OAuthFlows(
            password={"tokenUrl": tokenUrl, "scopes": scopes}
        )
        super().__init__(flows=flows, scheme_name=scheme_name, auto_error=auto_error)

    async def __call__(
        self, request: starlette.requests.Request
    ) -> typing.Optional[str]:
        header_authorization: str = request.headers.get("Authorization")
        cookie_authorization: str = request.cookies.get("Authorization")
        header_scheme, header_param = fastapi.security.utils.get_authorization_scheme_param(
            header_authorization
        )
        cookie_scheme, cookie_param = fastapi.security.utils.get_authorization_scheme_param(
            cookie_authorization
        )
        if header_scheme.lower() == "bearer":
            authorization = True
            scheme = header_scheme
            param = header_param

        elif cookie_scheme.lower() == "bearer":
            authorization = True
            scheme = cookie_scheme
            param = cookie_param
        else:
            authorization = False

        if not authorization or scheme.lower() != "bearer":
            if self.auto_error:
                raise HTTPException(
                    status_code=starlette.status.HTTP_401_UNAUTHORIZED,
                    detail="Not authenticated",
                    headers={"WWW-Authenticate": "Bearer"},
                )
            else:
                return None
        return param


oauth2_scheme = OAuth2PasswordBearerWithCookie(  # fastapi.security.OAuth2PasswordBearer
    tokenUrl="/token",
    scopes={
        "me": "diagnostics about the current user",
        "bgp": "capabilities about bgp route lookup",
    },
    auto_error=False,
)
```

Would you be so kind to advise a bit further; why it complains about line `if self.auto_error:` with `AttributeError: 'OAuth2PasswordBearerWithCookie' object has no attribute 'auto_error'` ?

**Comment by dmontagu** [comment]
Presumably it is saying this because `fastapi.openapi.models.OAuth2` doesn't have that attribute, so you aren't setting it in your `__init__`. If you add `self.auto_error = auto_error` to the `__init__` maybe that will make everything work properly?

**Comment by nskalis** [comment]
most probably, I didn't understand sth well:
```
class OAuth2PasswordBearerWithCookie(fastapi.openapi.models.OAuth2):

    __hash__ = lambda obj: id(obj)

    def __init__(
        self,
        tokenUrl: str,
        scheme_name: str = None,
        scopes: dict = None,
        auto_error: bool = True,
    ):
        self.auto_error = auto_error
        if not scopes:
            scopes = {}
        flows = fastapi.openapi.models.OAuthFlows(
            password={"tokenUrl": tokenUrl, "scopes": scopes}
        )
        super().__init__(flows=flows, scheme_name=scheme_name, auto_error=auto_error)
```
when uvicorn boots it complains about:
```
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/subprocess.py", line 73, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/main.py", line 341, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/site-packages/uvicorn/main.py", line 348, in serve
    config.load()
  File "/usr/local/lib/python3.6/site-packages/uvicorn/config.py", line 274, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.6/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./glass.py", line 95, in <module>
    auto_error=False,
  File "./glass.py", line 46, in __init__
    self.auto_error = auto_error
  File "pydantic/main.py", line 281, in pydantic.main.BaseModel.__setattr__
ValueError: "OAuth2PasswordBearerWithCookie" object has no field "auto_error"
```

**Comment by dmontagu** [comment]
Try the following: 

```python
class OAuth2PasswordBearerWithCookie(fastapi.openapi.models.OAuth2):

    __hash__ = lambda obj: id(obj)

    def __init__(
        self,
        tokenUrl: str,
        scheme_name: str = None,
        scopes: dict = None,
        auto_error: bool = True,
    ):
        self.auto_error = auto_error
        if not scopes:
            scopes = {}
        flows = fastapi.openapi.models.OAuthFlows(
            password={"tokenUrl": tokenUrl, "scopes": scopes}
        )
        self.auto_error = auto_error  # <-------- add this line
        super().__init__(flows=flows, scheme_name=scheme_name, auto_error=auto_error)
```

-----

I think the problem is that you are trying to use a subclass of `OAuth2` to accomplish something similar to how `OAuth2PasswordRequestForm` works, but that isn't a subclass of `OAuth2`. So you might run into some issues. But it wouldn't surprise me if the above works.

**Comment by nskalis** [comment]
Thank you so much for looking into it @dmontagu
(I don't understand how the above is different from the previous snippet, the error persists.)

Any idea ?

**Comment by ViviLearns2Code** [comment]
@nskalis Not an expert, but I played around a bit and it seems like importing `OAuth2` from `fastapi.security` instead of `fastapi.openapi.models` does not lead to the error messages you are seeing anymore.

**Comment by polokk** [comment]
> @nskalis Not an expert, but I played around a bit and it seems like importing `OAuth2` from `fastapi.security` instead of `fastapi.openapi.models` does not lead to the error messages you are seeing anymore.

@ViviLearns2Code   Good Idea!
I have the same trouble as @sk, when I update "from fastapi.openapi.models import OAuth2" to "from fastapi.security import OAuth2", It works. Thx!

**Comment by polokk** [comment]
my code:

<pre><code>#from fastapi.openapi.models import OAuth2
from fastapi.security import OAuth2
from fastapi.openapi.models import OAuthFlows as OAuthFlowsModel
from fastapi.security.utils import get_authorization_scheme_param
from starlette.status import HTTP_401_UNAUTHORIZED, HTTP_403_FORBIDDEN
from typing import Any, Dict, List, Union

class OAuth2PasswordBearerWithCookie(OAuth2):
    def __init__(
        self,
        tokenUrl: str,
        scheme_name: Optional[str] = None,
        scopes: Optional[Dict[str, str]] = None,
        auto_error: bool = True,
    ):
        if not scopes:
            scopes = {}
        flows = OAuthFlowsModel(password={"tokenUrl": tokenUrl, "scopes": scopes})
        super().__init__(flows=flows, scheme_name=scheme_name, auto_error=auto_error)
    
    async def __call__(self, request: Request) -> Optional[str]:
        authorization: str = request.cookies.get("access_token")
        scheme, param = get_authorization_scheme_param(authorization)
        if not authorization or scheme.lower() != "bearer":
            if self.auto_error:
                raise HTTPException(
                    status_code=HTTP_401_UNAUTHORIZED,
                    detail="Not authenticated",
                    headers={"WWW-Authenticate": "Bearer"},
                )
            else:
                return None
        return param

</code></pre>
