### ISSUE TITLE
How to disable automatic docs

### ISSUE THREAD

**Issue by joegihu** [tiangolo/fastapi#846]
Hi, the autocreation of the openapi doc is a cool feature, but there are situations when it is better disabled. This should be possible according docu on https://fastapi.tiangolo.com/tutorial/application-configuration/:
"If you want to disable the OpenAPI schema completely you can set openapi_url=None"

However, when using it in this way: app = FastAPI(openapi_url=None)
I get:
    Traceback (most recent call last):
      File "C:\dev\registry\serial numbers\server\app.py", line 12, in <module>
        app = FastAPI(openapi_url=None)
      File "C:\dev\Python37\lib\site-packages\fastapi\applications.py", line 77, in __init__
        assert self.openapi_url, "The openapi_url is required for the docs"
    AssertionError: The openapi_url is required for the docs

I am using the latest version fastapi==0.46.0

Any help is appreciated!

**Comment by dmontagu** [comment]
You’re getting this error because you haven’t also set docs_url and redoc_url to None. If you change that it should work.

**Comment by dmontagu** [comment]
If the docs weren’t clear and this was confusing, a pull request updating the docs might be a good idea!

**Comment by joegihu** [comment]
Thanks, that works! I am impressed of the lightning fast response ;-)

**Comment by tiangolo** [comment]
Yep. Agreed, @dmontagu rocks! Thanks for all the help here. :fist_oncoming: :bowing_man: :rocket: 

I think that solves your problem, right @joegihu ? If so, you can close the issue.

**Comment by kalzoo** [comment]
Hey, to follow along on this, I'd say the docs aren't _confusing_ per se as just incorrect: https://fastapi.tiangolo.com/advanced/conditional-openapi/ . If you follow the provided example, the app fails to start.

FastAPI v0.54.1

```
app: FastAPI = FastAPI(openapi_url="/openapi.json" if app_settings.development else "")
File "/.../lib/python3.7/site-packages/fastapi/applications.py", line 86, in __init__
assert self.openapi_url, "The openapi_url is required for the docs"
```

Is there a situation in which you'd want to set `openapi_url` but not the other two, and this error is desired? If I make a PR, it seems like it might be better to fix the bug rather than the docs, but happy to do either.

Thanks all.

**Comment by Kludex** [comment]
@kalzoo We don't have that issue in the current version anymore.

FastAPI version: 0.59.0

**Comment by Kludex** [comment]
@kalzoo We don't have that issue in the current version anymore.

FastAPI version: 0.59.0

**Comment by kalzoo** [comment]
True! Should have double-checked my work. Thanks :)
