### ISSUE TITLE
app.route is broken

### ISSUE THREAD

**Issue by devonhk** [tiangolo/fastapi#912]
### Describe the bug

Making HTTP requests to functions with `@Fastapi.route` always raise exceptions 

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

1. Create a file with:

```Python
from fastapi import FastAPI

app = FastAPI()


@app.route("/", methods=['POST', 'GET'])
async def root():
    return 'ok'
```

Alternate version of route that also fails:
```python
@app.route("/", methods=['POST', 'GET'])
async def root(arg):
    return 'ok'
```

2. Run the dev server `main:app --reload --port 5000`
3. Run `curl localhost:5000 -X POST` and `curl localhost:5000`
4. It returns a 500 because of an uncaught exception.

### Expected behavior

Add a clear and concise description of what you expected to happen.

### Actual behavior

First error when `root()` is defined without a parameter

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
TypeError: root() takes 0 positional arguments but 1 was given
```

Second error when `root(arg)` is defined with a parameter

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/home/user/coding/telegram_video_uploader/env/lib/python3.7/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
TypeError: 'str' object is not callable
```

### Environment

- OS: Linux
- python version: 3.7.6
- Version: `fastapi==0.47.1`

### Additional context

`FastpiAPI.get` and `FastAPI.post` behave normally. They both implicitly return a plain text response and a 200 response without raising errors.

**Comment by dmontagu** [comment]
`@app.route(...)` is the api used by `starlette`, so if you use that decorator, the function you decorate has to take the arguments expected by starlette.

The decorator you are looking for is actually `@app.api_route`, and should work in the example you've provided.

**Comment by pydo** [comment]
@dmontagu Thanks so much for the quick reply. I created a new ticket for adding this to the documentation https://github.com/tiangolo/fastapi/issues/913

**Comment by tiangolo** [comment]
Thanks for the help here @dmontagu! :cake: :bowing_man: 

Thanks @pydo for reporting back and closing the issue :+1:
