### ISSUE TITLE
custom response not work？

### ISSUE THREAD

**Issue by kaybinwong** [tiangolo/fastapi#9216]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

1. create custom response as below
```
import time
import json
import datetime
import logging
import numpy as np
import pandas as pd

from typing import Callable, Any, Optional, Dict
from fastapi import Request, Response
from starlette.background import BackgroundTask
from fastapi.routing import APIRoute

from models.tick import Tick

class DataEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime.datetime):
            return obj.strftime("%Y-%m-%d %H:%M:%S")
        elif isinstance(obj, datetime.date):
            return obj.strftime("%Y-%m-%d")
        elif isinstance(obj, type(bytes)):
            return str(obj, encoding='utf-8')
        elif isinstance(obj, type(np.ndarray)):
            return obj.tolist()
        elif isinstance(obj, UUID):
            return obj.hex
        elif isinstance(obj, Tick):
            return obj.to_dict()
        else:
            return super(DataEncoder, self).default(obj)

def _serial(result):        
    _t = type(result)
    _rt = 'text/html'
    if _t is str:
        _s = result
    elif _t is pd.DataFrame or _t is pd.Series:
        _s = result.to_csv()
        _rt = 'text/csv'
    elif _t is np.ndarray:
        _s = json.dumps(result.tolist(), 
            ensure_ascii=False,
            allow_nan=False,
            indent=None,
            separators=(",", ":"), 
            cls=DataEncoder
        )
        _rt = 'application/json'
    else:
        _s = json.dumps(result, 
            ensure_ascii=False,
            allow_nan=False,
            indent=None,
            separators=(",", ":"), 
            cls=DataEncoder
        )
        _rt = 'application/json'
    return _s, _rt

class CustomResponse(Response):    
    def __init__(
        self,
        content: Any,
        status_code: int = 200,
        headers: Optional[Dict[str, str]] = None,
        media_type: Optional[str] = None,
        background: Optional[BackgroundTask] = None,
    ) -> None:
        super().__init__(content, status_code, headers, media_type, background)

    def render(self, content: Any) -> bytes:
        print("render for type {}", type(content))
        logging.info("render for type {}", type(content))
        _c, _t = _serial(content)
        self.media_type = _t
        return _c.encode("utf-8")
```

2. and using it when create FastAPI app
```
app = FastAPI(
    title="test",
    description="test",
    version="0.0.1",
    terms_of_service="http://example.com/terms/",
    contact={
        "name": "Deadpoolio the Amazing",
        "url": "http://x-force.example.com/contact/",
        "email": "dp@x-force.example.com",
    },
    license_info={
        "name": "Apache 2.0",
        "url": "https://www.apache.org/licenses/LICENSE-2.0.html",
    },
    default_response_class=CustomResponse
)
```

but it seems not work as expected, and errors occur when function return ndarray or pd objs.
```
INFO:     Started server process [29228]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     127.0.0.1:58214 - "GET /api/test?type_=str HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: cannot convert dictionary update sequence element #0 to a sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\routing.py", line 264, in app
    is_coroutine=is_coroutine,
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\routing.py", line 152, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\okay\AppData\Local\Programs\Python\Python37\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError('cannot convert dictionary update sequence element #0 to a sequence'), TypeError('vars() argument must have __dict__ attribute')]
```

 i want to abstract a api layer，how could i do to make custom serialize easily?

**Comment by kaybinwong** [comment]
it seems raw_data will be serialized by jsonable_encoder, then error occurs.

so it will be more friendly by using,
1/custom serialize
2/pass it from app to encoders
