### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'send'

### ISSUE THREAD

**Issue by Technerder** [tiangolo/fastapi#936]
### Describe the bug

Getting the following error:
```error
ERROR:waitress:Exception while serving /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 172, in service
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 440, in execute
    app_iter = self.channel.server.application(environ, start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
```

### To Reproduce

```Python
import waitress
from fastapi import FastAPI

app = FastAPI()

@app.get("/move/{direction_char}")
def read_root(direction_char: str):
    return {"DirectionChar": direction_char}

waitress.serve(app)
```
### Expected behavior

Expected a JSON response along the lines of {"DirectionChar": "A"}

### Environment

- OS: Debian 10
- FastAPI Version: 0.47.1

- Python version: 3.7.3

**Comment by phy25** [comment]
fastapi only supports ASGI, not WSGI.

**Comment by tiangolo** [comment]
Thanks @phy25 !

Yep, @Technerder you would normally use Uvicorn, Daphne, Hypercorn. Or something like Gunicorn running Uvicorn.

**Comment by Technerder** [comment]
That makes sense, thanks!
