### ISSUE TITLE
Using PEP 649 annotations with status code `204 No Content` and return type `None` raises `AssertionError`

### ISSUE THREAD

**Issue by hofrob** [tiangolo/fastapi#9424]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

# Reproduce

1. create FastAPI app
2. create route with status code `204 No Content`
3. add return type `None` to said route
4. add future annotations ([PEP 649](https://peps.python.org/pep-0649/))

```py
from __future__ import annotations

import http
import logging

from fastapi import FastAPI


app = FastAPI()


@app.post("/", status_code=http.HTTPStatus.NO_CONTENT)
async def root() -> None:
    logging.info("endpoint called.")
```

## Repo to quickly try different versions of python/FastAPI

https://github.com/hofrob/fastapi-future-annotations

## Expected

The file above should boot up fine when running `uvicorn filename:app --reload`

## Actual

This raises an error: `AssertionError: Status code 204 must not have a response body`

### full traceback

```
Traceback (most recent call last):
  File "/<python_location>/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/<python_location>/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/<project_dir>/venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/<project_dir>/venv/lib/python3.11/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<python_location>/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/<python_location>/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/<project_dir>/venv/lib/python3.11/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/<project_dir>/venv/lib/python3.11/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<project_dir>/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<python_location>/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/<project_dir>/main.py", line 12, in <module>
    @app.post("/", status_code=http.HTTPStatus.NO_CONTENT)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<project_dir>/venv/lib/python3.11/site-packages/fastapi/routing.py", line 661, in decorator
    self.add_api_route(
  File "/<project_dir>/venv/lib/python3.11/site-packages/fastapi/routing.py", line 600, in add_api_route
    route = route_class(
            ^^^^^^^^^^^^
  File "/<project_dir>/venv/lib/python3.11/site-packages/fastapi/routing.py", line 401, in __init__
    assert is_body_allowed_for_status_code(
AssertionError: Status code 204 must not have a response body
```

# Current workarounds

* remove `from __future__ import annotations`
* or remove the return type `None`

# PRs

There was a PR posted in the discussion https://github.com/tiangolo/fastapi/discussions/6060#discussioncomment-5102253

After stepping through the code, I think it might make sense to return early in `fastapi.dependencies.utils.get_typed_annotation` if `annotation == "None"` (PR incoming).

**Comment by Munalula-Sikazwe** [comment]
According to the referenced link  in the issue #9424, you're returning  a string in the body " "

``` python 
@app.post("/", status_code=http.HTTPStatus.NO_CONTENT)
async def root() -> str:
    logging.info("endpoint called.")
    return ""
```
Even if this was edit the code to 
``` python 
@app.post("/", status_code=http.HTTPStatus.NO_CONTENT)
async def root() -> None:
    logging.info("endpoint called.")
    return None
```
The error is thrown because you are still returning something  in  body  as json though it may not be valid 
e.g null
With the third approach of not returning anything like 
``` python 
@app.post("/", status_code=http.HTTPStatus.NO_CONTENT)
async def root() -> None:
    logging.info("endpoint called.")
```
The server does not seem to complain one bit , maybe there's a special case or more information should be provided to resolve this issue .

**Comment by hofrob** [comment]
I already submitted a PR and it was approved (#9425). You can try the test there (with and without the change). The test fails on my machine as expected.

I deleted the repo (it wasn't up-to-date and I don't think it adds anything). The code in the issue already tells the whole story.

**Comment by Munalula-Sikazwe** [comment]
Oh ok I think this issue should be closed then .

**Comment by linpan** [comment]
just like NoReturn will have same error.

**Comment by hofrob** [comment]
Did you test this with my PR? I can add a test later and see if that's also fixed.

No idea when or if this will be merged though.

**Comment by HariAcharya80** [comment]
@hofrob This is indeed an intended behavior. The `-> None` syntax is used to indicate that the function **does not return anything**. This is different from returning `None`, which is a **value**.

In your case, you are trying to return a 204 No Content response, which is used to indicate that the request was successful, but there is no content to return.

However, you are also using the `-> None` syntax, which is causing the response body to be set to None. This is not allowed for the status code 204, so you are getting an `AssertionError`.

To fix this error, you need to remove the `-> None` syntax from the root function. Here is an example:
```python
@app.get("/", status_code = 204)
async def root():
    logging.info('endpoint called.')
```
This code will define a route that returns a 204 No Content response without a response body. 

@Munalula-Sikazwe The server does not have a problem probably because of not using the annotations?
```python
from __future__ import annotations
```

**Comment by hofrob** [comment]
> The -> None syntax is used to indicate that the function does not return anything. This is different from returning None, which is a value.

This is incorrect.

1. every function in python returns something; there are no real `void` functions in Python
2. annotating the return value of a function is more correct than not annotating it; even if it's `None`

So the conclusion should be:

- accept `None` as return annotation
- allow it for http status 204

Please reconsider.

**Comment by HariAcharya80** [comment]
> annotating the return value of a function is more correct than not annotating it; even if it's None

I don't disagree but in the this scenario, allowing the `-> None` syntax for HTTP status `204` will introduces ambiguity regarding the presence or absence of a response body.  For clarity and HTTP compliance, excluding response body for status 204, ensures consistency and avoids client confusion.

**Comment by hofrob** [comment]
Well, let's see what the FastAPI devs think.

**Comment by HariAcharya80** [comment]
> Well, let's see what the FastAPI devs think.

Yeah, that's cool this way we have a guideline further because you know this is quite controversial and I follow what my team or the project requires me to personally.

**Comment by Kludex** [comment]
I think None should be a valid return type hint for 204 endpoints.

I also think that anything different than None (or lack of return statement, which conceptually is the same, but since we retrieve the type hints at runtime, is a bit different, and that's why not using a type hint works as expected here) should raise an error.

**Comment by jrobbins-LiveData** [comment]
An explicit `return NONE`, a bare `return`, or "falling off the end of the function" all return `None`, and since the return type hint is really about what the function returns (and not, strictly speaking) about the function's role as a 204 endpoint, `-> None` should be the required return type hint on such a function.  See [this discussion](https://github.com/python/typing/issues/695#issuecomment-566742632).

**Comment by lev-blit** [comment]
can we revisit this? no fix seems to have been merged and this is still happening :(
