### ISSUE TITLE
I get TypeError: StopIteration interacts badly with generators and cannot be raised into a Future

### ISSUE THREAD

**Issue by fj-sanchez** [tiangolo/fastapi#966]
Hi,

lately I've started to see in the logs this error:
```
[2020-02-10 12:34:40 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-02-10 12:34:40 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-02-10 12:34:40 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2020-02-10 12:34:40 +0000] [13] [INFO] Booting worker with pid: 13
[2020-02-10 12:34:41 +0000] [13] [INFO] Started server process [13]
[2020-02-10 12:34:41 +0000] [13] [INFO] Waiting for application startup.
[2020-02-10 12:34:41 +0000] [13] [INFO] Application startup complete.
Exception in callback <function _chain_future.<locals>._set_state at 0x7fdd9e719f70>
handle: <Handle _chain_future.<locals>._set_state>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.8/asyncio/futures.py", line 356, in _set_state
    _copy_future_state(other, future)
  File "/usr/local/lib/python3.8/asyncio/futures.py", line 332, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```
It doesn't show up straight away, but after a few queries. After a few more queries I get:

```
[2020-02-10 12:12:49 +0000] [13] [ERROR] Exception in ASGI application
....
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3355, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3388, in _execute_and_instances
    conn = self._get_bind_args(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3403, in _get_bind_args
    return fn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3382, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1130, in connection
    return self._connection_for_bind(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 432, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 127, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

Any idea what could be happening?

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue! :+1:

**Comment by maximmarakov** [comment]
I got the same traceback, and found that any `StopIteration` exception will kill your request handling.
For example, this server: 

```
from fastapi import FastAPI
app = FastAPI()

@app.get("/")
def root():
    next(a for a in [])
    return {"message": "Hello World"}
```
will raise 
```
Exception in callback <function _chain_future.<locals>._set_state at 0x7fb9a5ab9c10>
handle: <Handle _chain_future.<locals>._set_state>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/lib/python3.8/asyncio/futures.py", line 353, in _set_state
    _copy_future_state(other, future)
  File "/usr/lib/python3.8/asyncio/futures.py", line 329, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```
and request will look like "infinity loading".

So, if you had this exception, check if there was an unhandled `StopIteration` exception

**Comment by meshantz** [comment]
I ran into another version of this that was particularly hard to track down. It resulted in my test suite hanging without any feedback at all (because logging is captured by default, and does not show unless the test completes with an error, so the above error is never displayed).

Test examples that hang:
```
def test_thingum1():
    route = "/test"
    dep_response = mock.MagicMock()
    # calls after the second one raise StopIteration
    dep_response.side_effect = ["first", "second"]

    def dependency_fake():
        return dep_response()

    fastapi_app = FastAPI()

    @fastapi_app.get(f"{route}")
    def fake_endpoint(things: bool = Depends(dependency_fake)):
        return {"has": things}

    client = TestClient(fastapi_app)

    call1 = client.get(f"{route}")
    call2 = client.get(f"{route}")
    call3 = client.get(f"{route}")

    assert call1.status_code == 200
    assert call2.status_code == 200
    assert call3.status_code == 500


def test_thingum2():
    route = "/test"

    fastapi_app = FastAPI()

    @fastapi_app.get(f"{route}")
    def fake_endpoint():
        raise StopIteration("oh no!")

    client = TestClient(fastapi_app)

    call1 = client.get(f"{route}")

    assert call1.status_code == 500
```

It would be nice if something could be done about this but I really don't know what form that should take. Perhaps documentation around the use of mock side-effects would help? Perhaps something can be done at the `TestClient` to intercept/transform this kind of exception?

Maybe this is better to address upstream at Starlette, but I've mentioned it here since my use case was related to FastAPI's dependency injection system.

**Comment by NCarteazy** [comment]
Hey @tiangolo, we ran across this today and I'm wondering if there is a path to actually resolve this in this library. A `StopIteration` exception does get raised if calling `next` on an empty generator inside of a FastAPI request and the request hangs from there. We managed to resolve it in the code but this does feel like something that the library could catch? Let me know.

**Comment by valen-spi3pl** [comment]
Hi beloved FastAPI community,
I encountered with this same issue. Seems related to starlette TestClient. One way to prevent this to happen is to make sure the side_effect list has one more item than needed. Like this:

```
MyController.my_method = MagicMock(side_effect=[
    'first_mocked_response',
    'second_mocked_response',
    'unused_mocked_response_that_prevents_StopIteration'
])
```

Hope this helps someone.

**Comment by sjaq** [comment]
@tiangolo I'm running into the same problem. If a sync route handler raises a StopIteration somewhere in the code the entire process hangs. I've been trying to resolve this by inserting dependencies, exception handlers or middleware to catch the error but it seems impossible to find a generalized way to translate a StopIteration exception into a regular 500 server side error without breaking the server process. This really seems like something that should be handled by the library? Or maybe inside starlette?

**Comment by tiangolo** [comment]
This actually goes deep down to asyncio. It was recently fixed in AnyIO: https://github.com/agronholm/anyio/pull/477

The fix will be available in AnyIO 4.0.0 (not yet released).

Meanwhile, you could install from the git repo. But you would have to monkey patch a removed attribute used in Starlette.
