### ISSUE TITLE
`RecursionError` when using self-referencing Pydantic models/schemas

### ISSUE THREAD

**Issue by Toreno96** [tiangolo/fastapi#982]
### Describe the bug

FastAPI raises `RecursionError` when application contains self-referencing Pydantic models/schemas:  
<https://pydantic-docs.helpmanual.io/usage/postponed_annotations/#self-referencing-models>

It breaks the FastAPI's promise that:  
<https://fastapi.tiangolo.com/features/#pydantic-features>
> FastAPI is fully compatible with (and based on) Pydantic. So, any additional Pydantic code you have, will also work.

### To Reproduce

1. Create a file `main.py` with:

```Python
from __future__ import annotations

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class User(BaseModel):
    id: int
    best_friend: User = None


User.update_forward_refs()


@app.get("/users/<user_id>", response_model=User)
def get_user(user_id: int):
    return User(id=42)
```

1. Start the application with:

```shell
$ uvicorn main:app
```

1. Application raises unhandled exception `RecursionError`. Full traceback:
```
Traceback (most recent call last):
  File "/Users/dstasczak/development/spikes/fastapi/.venv/bin/uvicorn", line 10, in <module>
    sys.exit(main())
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/uvicorn/main.py", line 331, in main
    run(**kwargs)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/uvicorn/main.py", line 354, in run
    server.run()
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/uvicorn/main.py", line 389, in serve
    config.load()
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/uvicorn/config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 17, in <module>
    @app.get("/users/<user_id>", response_model=User)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 494, in decorator
    callbacks=callbacks,
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 438, in add_api_route
    callbacks=callbacks,
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 275, in __init__
    ] = create_cloned_field(self.response_field)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/fastapi/utils.py", line 98, in create_cloned_field
    use_type.__fields__[f.name] = create_cloned_field(f)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/fastapi/utils.py", line 98, in create_cloned_field
    use_type.__fields__[f.name] = create_cloned_field(f)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/fastapi/utils.py", line 98, in create_cloned_field
    use_type.__fields__[f.name] = create_cloned_field(f)
  [Previous line repeated 945 more times]
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/fastapi/utils.py", line 96, in create_cloned_field
    use_type = create_model(original_type.__name__, __base__=original_type)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/pydantic/main.py", line 789, in create_model
    return type(model_name, (__base__,), namespace)
  File "/Users/dstasczak/development/spikes/fastapi/.venv/lib/python3.7/site-packages/pydantic/main.py", line 162, in __new__
    fields.update(deepcopy(base.__fields__))
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 238, in _deepcopy_dict
    memo[id(x)] = y
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Expected behavior

Application should start successfully and self-referenced models should be handled by the FastAPI.

### Environment

- OS: macOS
- FastAPI Version: 0.48.0
- Python version: 3.7.5

### Additional context

I also tried without the `from __future__ import annotations` and with `best_friend: 'User' = None` (self-referenced type as string), but it didn't change anything.

It is possible to make some workarounds for this, e.g.:
```python
class _User(BaseModel):
    id: int
    best_friend: Any = None


class User(BaseModel):
    id: int
    best_friend: _User = None
```

But it makes implementation more cumbersome than it should be, and autogenerated documentation is less precise.

**Comment by merowinger92** [comment]
Looks for me like a duplicate to #894

**Comment by zamiramir** [comment]
[Issue is solved](https://github.com/tiangolo/fastapi/issues/894#issuecomment-605671389)

@Toreno96 This should be closed.

**Comment by Toreno96** [comment]
@zamiramir Awesome, thanks for the reminder.

**Comment by tiangolo** [comment]
Thanks for the help here @merowinger92 and @zamiramir ! :bowing_man: 

Thanks @Toreno96 for coming back to close the issue :+1:
